src/objects/Additional_Debt__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Debts</relationshipLabel>
        <relationshipName>Additional_Debts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Civil_Litigation__c</fullName>
        <label>Civil Litigation</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Credit_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Assessment</label>
        <referenceTo>Credit_Assessment__c</referenceTo>
        <relationshipLabel>Debts</relationshipLabel>
        <relationshipName>Debts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Debt_Type__c</fullName>
        <label>Debt Type</label>
        <picklist>
            <picklistValues>
                <fullName>Personal Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overdraft</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <label>Legal Entity</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_Repayment__c</fullName>
        <label>Monthly Repayment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Filter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 2) AND 3</booleanFilter>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.Primary_Contact__c</valueField>
            </filterItems>
            <filterItems>
                <field>Opportunity.StageName</field>
                <operation>equals</operation>
                <value>In Progress, Pending Signature, Application Revised, Assessment In Progress</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Debts (Opportunity Name)</relationshipLabel>
        <relationshipName>Debts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Debts</relationshipLabel>
        <relationshipName>Debts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Debt_Amount__c</fullName>
        <label>Original Debt Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outstanding_Amount__c</fullName>
        <label>Outstanding Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Debts</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AMPSales_DebtsController.cls
public with sharing class AMPSales_DebtsController {
    public Additional_Debt__c Debt  {get; set;}{
        Debt = new Additional_Debt__c();
    }
    public string ReturnURL {get; set;}
    public string SObjectType {get; set;}
    public boolean DisableSaveBtn	{get; set;}{
    	DisableSaveBtn = false;
    }   
    
    public AMPSales_DebtsController(ApexPages.StandardController StdCntlr_Debt){
        if(StdCntlr_Debt != null){
            Additional_Debt__c ContexttRecord = (Additional_Debt__c)StdCntlr_Debt.getRecord();
            Debt = this.getDebtRecord(ContexttRecord.Id);
            Debt.Opportunity_Filter__c = Debt.Opportunity__c;
            ReturnURL = ApexPages.currentPage().getParameters().get('retURL');
            
            
            if(ReturnURL.contains('a02')){
            	this.ReferenceObject(Debt.Credit_Assessment__c);
            	SObjectType = string.valueOf(Debt.Credit_Assessment__c).substring(0,3);
            }else if(ReturnURL.contains('001')){
            	SObjectType = string.valueOf(Debt.Account__c).substring(0,3);
            	this.ReferenceObject(Debt.Opportunity__c);
            }else if(ReturnURL.contains('006')){
            	SObjectType = string.valueOf(Debt.Opportunity__c).substring(0,3);
            	this.ReferenceObject(Debt.Opportunity__c);
            }
        }
    }
    
    private void ReferenceObject(string SObjectId){
    	if(SObjectId.substring(0,3) == '006'){
            Opportunity Opp = [select StageName from Opportunity where Id =:SObjectId];
            
            if(Opp.StageName != 'In Progress'
					&& Opp.StageName != 'Pending Signature'
					&& Opp.StageName != 'Assessment In Progress' 
					&& Opp.StageName != 'Application Revised'){
				DisableSaveBtn = true;
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'You can not update Debt record when Opportunity is in '+Opp.StageName+' stage.'));							
			}           
            
        }else if(SObjectId.substring(0,3) == 'a02'){
        	Credit_Assessment__c CA = [Select Status__c From Credit_Assessment__c where Id =:SObjectId];
        	
        	if(CA.Status__c == 'Approved' || CA.Status__c == 'Rejected'){
				DisableSaveBtn = true;
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'You can not update Debt record when Credit Assessment is '+CA.Status__c));								
			}
        
        }
    }
    
    private Additional_Debt__c getDebtRecord(ID RecordId){
        try{
            return [Select a.RecordTypeId,                       
                        a.Owner.Name, 
                        a.Outstanding_Amount__c, 
                        a.Original_Debt_Amount__c, 
                        a.Opportunity__c,
                        a.Opportunity_Filter__c, 
                        a.Name, 
                        a.Monthly_Repayment__c, 
                        a.Legal_Entity__c, 
                        a.Id, 
                        a.Debt_Type__c, 
                        a.DWH_Status__c, 
                        a.DWH_Last_Sync__c, 
                        a.Credit_Assessment__c, 
                        a.Civil_Litigation__c, 
                        a.Account__c,
                        a.Account__r.Associated_Business__c 
                    From Additional_Debt__c a where Id =:RecordId limit 1];         
        }catch(QueryException ex){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getmessage()));
        }
        return null;
    }
    
    public PageReference UpdateDebt(){
        try{
            Debt.Opportunity__c = Debt.Opportunity_Filter__c;
            Debt.Opportunity_Filter__c = null;
            string CurrencyCode = this.OpportunityCurrencyCode(Debt.Opportunity__c);
            if(CurrencyCode != null)
            	Debt.CurrencyIsoCode = CurrencyCode;
            database.update(Debt);
        }catch(DMLException ex){
            return null;
        }
        return new Pagereference(ReturnURL);
    }
    
    private string OpportunityCurrencyCode(ID OpportunityId){
    	try{
    		Opportunity Opp = [Select o.CurrencyIsoCode From Opportunity o where Id =: OpportunityId];
    		return Opp.CurrencyIsoCode;    		
    	}catch(QueryException ex){}
    	return null;    	
    } 
}