src/objects/Additional_Debt__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Debts</relationshipLabel>
        <relationshipName>Additional_Debts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Assessment</label>
        <referenceTo>Credit_Assessment__c</referenceTo>
        <relationshipLabel>Debts</relationshipLabel>
        <relationshipName>Debts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Filter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 2) AND 3</booleanFilter>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.Primary_Contact__c</valueField>
            </filterItems>
            <filterItems>
                <field>Opportunity.StageName</field>
                <operation>equals</operation>
                <value>In Progress, Pending Signature, Application Revised, Assessment In Progress</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Debts (Opportunity Name)</relationshipLabel>
        <relationshipName>Debts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Debts</relationshipLabel>
        <relationshipName>Debts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Debts</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AMPSales_CreateDebts.cls
public with sharing class AMPSales_CreateDebts {
    public Additional_Debt__c Debt  {get; set;}{
        Debt = new Additional_Debt__c();
    }    
    public string ReturnURL {get; set;}
    public string SObjectType    {get; set;}
    private string LookupId;
    private string AccountId;
    private string OppId;
    
    
    public AMPSales_CreateDebts(){                  
        ReturnURL = ApexPages.currentPage().getParameters().get('retURL');
        LookupId = ApexPages.currentPage().getParameters().get('id');
        AccountId = ApexPages.currentPage().getParameters().get('aid');
        OppId = ApexPages.currentPage().getParameters().get('oid');                     
        SObjectType = LookupId.substring(0,3);
        
        if(SObjectType == '006'){
            Debt.Opportunity_Filter__c = LookupId;
            Debt.Account__c = AccountId; 
            
        }else if(SObjectType == 'a02'){
            Debt.Credit_Assessment__c = LookupId;
            Debt.Account__c = AccountId;
            Debt.Opportunity_Filter__c = OppId;
        
        }else if(SObjectType == '001'){
            Debt.Account__c = LookupId;
            Debt.Opportunity_Filter__c = OppId;
        } 
    }
    
    public PageReference SaveDebt(){
        try{                
            Debt.Opportunity__c = Debt.Opportunity_Filter__c;
            Debt.Opportunity_Filter__c = null;
            string CurrencyCode = this.OpportunityCurrencyCode(Debt.Opportunity__c);
            if(CurrencyCode != null)
            	Debt.CurrencyIsoCode = CurrencyCode;
            Database.insert(Debt);          
        }catch(DMLException ex){
            return null;
        }       
        return new Pagereference(ReturnURL);
    }
    
    private string OpportunityCurrencyCode(ID OpportunityId){
    	try{
    		Opportunity Opp = [Select o.CurrencyIsoCode From Opportunity o where Id =: OpportunityId];
    		return Opp.CurrencyIsoCode;    		
    	}catch(QueryException ex){}
    	return null;    	
    }   
}