src/objects/Additional_Debt__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Debts</relationshipLabel>
        <relationshipName>Additional_Debts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Assessment</label>
        <referenceTo>Credit_Assessment__c</referenceTo>
        <relationshipLabel>Debts</relationshipLabel>
        <relationshipName>Debts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Debts</relationshipLabel>
        <relationshipName>Debts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Debts</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AMPSales_DelDebtController.cls
public with sharing class AMPSales_DelDebtController {
	private Additional_Debt__c Debt;       
    public string ReturnURL {get; set;} 
    private Additional_Debt__c ContexttRecord;    
    
    public AMPSales_DelDebtController(ApexPages.StandardController StdCntlr_Debt){
        if(StdCntlr_Debt != null){
            ContexttRecord = (Additional_Debt__c)StdCntlr_Debt.getRecord(); 
            Debt = DebtRecordToDel(ContexttRecord.Id);          
        }
		ReturnURL = ApexPages.currentPage().getParameters().get('retURL');
    }
    
    public PageReference DelDebt(){
    	
    	if(Debt == null)
    		return new PageReference(ReturnURL);
    	system.debug('Debt >>> '+Debt);	
    	if(ReturnURL.contains('a02') && Debt.Credit_Assessment__c != null){
        	Credit_Assessment__c CA = [Select Status__c From Credit_Assessment__c where Id =:Debt.Credit_Assessment__c];
        	
        	if(CA.Status__c == 'Approved' || CA.Status__c == 'Rejected'){				
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'You can not delete Debt record when Credit Assessment is '+CA.Status__c));
				return null;								
			}else{
				 database.delete(Debt);				 
        	}
    	
    	}else {            
            Opportunity Opp = [select StageName from Opportunity where Id =:Debt.Opportunity__c];
            
            if(Opp.StageName != 'In Progress'
					&& Opp.StageName != 'Pending Signature'
					&& Opp.StageName != 'Assessment In Progress' 
					&& Opp.StageName != 'Application Revised'){
				
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'You can not delete Debt record when Opportunity is in '+Opp.StageName+' stage.'));
				return null;							
			}else{
				 database.delete(Debt);				 
			}
        }
        
        return new PageReference(ReturnURL); 
    }
    
    private Additional_Debt__c DebtRecordToDel(ID RecordId){
        try{
            system.debug('RecordId >>> '+RecordId);
            return [Select a.Id,a.Opportunity__c,                       
                        a.Credit_Assessment__c,                       
                        a.Account__c 
                    From Additional_Debt__c a where Id =:RecordId limit 1];         
        }catch(QueryException ex){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getmessage()));
        }
        return null;
    }
}