src/objects/Additional_Debt__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Debts</relationshipLabel>
        <relationshipName>Additional_Debts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Assessment</label>
        <referenceTo>Credit_Assessment__c</referenceTo>
        <relationshipLabel>Debts</relationshipLabel>
        <relationshipName>Debts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Debts</relationshipLabel>
        <relationshipName>Debts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Debts</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Philippines</fullName>
        <active>true</active>
        <description>Campaigns for Philippines</description>
        <label>Philippines</label>
    </recordTypes>
    <recordTypes>
        <fullName>Singapore</fullName>
        <active>true</active>
        <description>Campaigns for Singapore</description>
        <label>Singapore</label>
    </recordTypes>
    <recordTypes>
        <fullName>UK</fullName>
        <active>true</active>
        <description>Campaigns for UK</description>
        <label>UK</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Operation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operation</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Select to add a new contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program_Product_ASO__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program_Product_ASO__c.Rules_Engine__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Guarantors__c.object
<CustomObject>
    <description>AMP Guarantors Custom Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Guarantors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credit_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Assessment</label>
        <referenceTo>Credit_Assessment__c</referenceTo>
        <relationshipLabel>Owners/Directors/Guarantors</relationshipLabel>
        <relationshipName>Owners_Directors_Guarantors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Guarantors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Owner/Director/Guarantor</label>
    <nameField>
        <displayFormat>ODG-{000000}</displayFormat>
        <label>Owners/Directors/Guarantors</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Owners/Directors/Guarantors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Program__c.Country_Mapping__c</field>
                <operation>equals</operation>
                <valueField>$Source.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Philippines</fullName>
        <active>true</active>
        <businessProcess>Lead Process</businessProcess>
        <description>Lead belongs to PP</description>
        <label>Philippines</label>
    </recordTypes>
    <recordTypes>
        <fullName>Singapore</fullName>
        <active>true</active>
        <businessProcess>Lead Process</businessProcess>
        <description>Lead belongs to SG</description>
        <label>Singapore</label>
    </recordTypes>
    <recordTypes>
        <fullName>UK</fullName>
        <active>true</active>
        <businessProcess>Lead Process</businessProcess>
        <description>Lead belongs to UK</description>
        <label>UK</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loan_Ledger__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Ledgers</relationshipLabel>
        <relationshipName>Loan_Ledgers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Product ASO</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Loan Ledgers</relationshipLabel>
        <relationshipName>Loan_Ledgers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan Ledger</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_Management__c.object
<CustomObject>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <label>Program Product ASO</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipName>Loan_Management</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Program_Product_ASO__r.Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <label>Rules Engine</label>
    <nameField>
        <displayFormat>LM-{000}</displayFormat>
        <label>Loan Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules Engines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Management_Event__c.object
<CustomObject>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Loan</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Loan Management Events</relationshipLabel>
        <relationshipName>Loan_Management_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Loan Management Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Management Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Program__c</field>
                <operation>equals</operation>
                <valueField>Program_Product_ASO__c.Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program_Product_ASO__c.Rules_Engine__c</field>
                <operation>notEqual</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>contains</operation>
                <valueField>Program__c.Country_Mapping__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <recordTypes>
        <fullName>Singapore</fullName>
        <active>true</active>
        <label>Singapore</label>
    </recordTypes>
    <recordTypes>
        <fullName>UK</fullName>
        <active>true</active>
        <label>UK</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>PPAS</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reward__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reward</label>
        <type>Checkbox</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reward__c.object
<CustomObject>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <label>Program Product ASO</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CRMS_Constants.cls
/**
    Class for storing constant values
    Author: Saket Joshi
*/

public without sharing class CRMS_Constants {

    public static final String DWH_STATUS_QUEUED = 'Queued';
    public static final String DWH_STATUS_SYNCED = 'Synced';
    public static final String SYNC_QUEUE_STATUS_PENDING = 'Pending';
    public static final String SYNC_QUEUE_STATUS_SUCCESS = 'Success';
    public static final String DWH_DATA_TYPE_CASE = 'Case';
    public static final String DWH_DATA_TYPE_ODG = 'ODG';
    public static final String DWH_DATA_TYPE_USER = 'User';
    public static final String DWH_DATA_TYPE_CONTACT = 'Contact';
    public static final String DWH_DATA_TYPE_LEAD = 'Lead';
    public static final String DWH_DATA_TYPE_TASK = 'Task';
    public static final String DWH_DATA_TYPE_ACCOUNT = 'Account';
    public static final String DWH_DATA_TYPE_OPPORTUNITY = 'Opportunity';
    public static final String DWH_DATA_TYPE_OPERATION = 'Operation';
    public static final String DWH_DATA_TYPE_CREDIT_ASSESSMENT = 'Credit Assessment';
    public static final String DWH_DATA_TYPE_CAMPAIGN = 'Campaign';
    public static final String DWH_DATA_TYPE_PROGRAM = 'Program';
    public static final String DWH_DATA_TYPE_PRODUCT = 'Product';
    public static final String DWH_DATA_TYPE_PPAS = 'Program Product Association';
    public static final String DWH_DATA_TYPE_REWARD = 'Reward';
    public static final String DWH_DATA_TYPE_LOAN_MANAGEMENT = 'Loan Management';
    public static final String DWH_DATA_TYPE_LOAN_LEDGER = 'Loan Ledger';
    public static final String DWH_DATA_TYPE_LOAN_MANAGEMENT_EVENT = 'Loan Management Event';
    public static final String SYNC_STATUS_DELETE = 'Delete';
    public static final String SYNC_STATUS_STALE = 'Stale';
    public static final String DWH_CREATED_BY_TRIGGER = ' DWH Created by Trigger';
    public static final String DWH_DELETE_TRIGGER = ' DWH Delete by Trigger';
    public static final String SYNC_ACTION_DELETE = 'Delete';
    public static final String SYNC_ACTION_UPDATE = 'Update';
    public static final String SYNC_ACTION_INSERT = 'Insert';
    public static final String SYNC_ACTION_CREATE = 'Create';
    public static final String SYNC_STATUS_CONTACT_DELETED = ': Contact deleted';
    public static final String SYNC_STATUS_LEAD_DELETED = ': Lead deleted';
    public static final String SYNC_STATUS_TASK_DELETED = ': Task deleted';
    public static final String SYNC_STATUS_ODG_DELETED = ': O/D/G deleted';
    public static final String SYNC_STATUS_ACCOUNT_DELETED = ': Account deleted';
    public static final String SYNC_STATUS_OPPORTUNITY_DELETED = ': Opportunity deleted';
    public static final String SYNC_STATUS_OPERATION_DELETED = ': Operation deleted';
    public static final String SYNC_STATUS_CREDIT_ASSESSMENT_DELETED = ': Credit Assessment deleted';
    public static final String SYNC_STATUS_PROGRAM_DELETED = ': Program deleted';
    public static final String SYNC_STATUS_PRODUCT_DELETED = ': Product deleted';
    public static final String SYNC_STATUS_PPAS_DELETED = ': Program Product Combination deleted';
    public static final String SYNC_STATUS_REWARD_DELETED = ': Reward deleted';
    public static final String SYNC_STATUS_LOAN_MANAGEMENT_DELETED = ': Rules Engine deleted';
    public static final String SYNC_STATUS_LOAN_LEDGER_DELETED = ': Loan Ledger deleted';
    public static final String SYNC_STATUS_LOAN_MANAGEMENT_EVENT_DELETED = ': Loan Management Event deleted';
    public static final String CALLOUT_METHOD_GET = 'GET';
    public static final String CALLOUT_METHOD_POST = 'POST';
    public static final String CALLOUT_METHOD_PUT = 'PUT';
    public static final String CALLOUT_METHOD_PATCH = 'PATCH';
    public static final String CALLOUT_METHOD_DELETE = 'DELETE';
    public static final String CALLOUT_PARAM_JSON_DATA = 'jsonData';
    public static final String CONTENT_TYPE = 'content-type';
    public static final String CONTENT_TYPE_JSON = 'application/json';
    public static final String AMP_ENDPOINT_URL = 'https://test.salesforce.com';
    public static final String CALLOUT_RESPONSE_SUCCESS = 'SUCCESS';
    public static final String CALLOUT_RESPONSE_JSON_PARAM_MISSING = 'JSON DATA MISSING';
    public static final String CALLOUT_RESPONSE_ERROR = 'ERROR';
    public static final Integer CALLOUT_DEFAULT_TIMEOUT = 30000;
    public static final Integer CALLOUT_RESPONSE_OK = 200;
    public static final String LEAD_CREATED_RESPONSE = ' Callout response: ';
    public static final String BATCH_RESPONSE_ERROR = ' XYXY XXX by batch, callout response: ';
    public static final String BATCH_RESPONSE_SUCCESS = ' XYXY XXX by batch ';
    public static final String BATCH_NO_ACTION_NEEDED = ' DWH no action needed by batch';
    public static final String API_ENDPOINT_LEADS = 'Lead';
    public static final String SHAREPOINT_DEV_ENDPOINT = 'https://advancedpay.sharepoint.com/sites/ampdev/';
    public static final String SHAREPOINT_QA_ENDPOINT = 'https://advancedpay.sharepoint.com/sites/QA/';
    public static final String SHAREPOINT_PROD_ENDPOINT = 'https://sharepoint.amp-creditech.com/sites/clientdocs/'; 
   
    // Inline send Email 
    public static final string docName = 'Application Document Alert';
    public static final string hongKong = 'Hong Kong';
    public static final string hk = 'HK';
    public static final string hkTemplate = 'Application Document Alert HK';
    
    public static final string uk = 'UK';
    public static final string ukTemplate = 'Application Document Alert UK';
    
    public static final string singapore = 'Singapore';
    public static final string sg = 'SG';
    public static final string sgTemplate = 'Application Document Alert SG';
    
    public static final string philippines = 'Philippines';
    public static final string ph = 'PH';
    public static final string phTemplate = 'Application Document Alert PH';
    
    public static final Map<String, String> mapDataTypeObjectName;
    public static final Map<String, String> mapDataTypeObjectApiName;
    public static final Map<String, String> mapApiNameDataType;
    public static final Map<String, String> mapObjectNameFieldSet;
    static {
        mapDataTypeObjectName = new Map<String, String> { 'Account' => 'Account__c',
                                                    'Case' => 'Case__c',
                                                    'Contact' => 'Contact__c',
                                                    'Credit Assessment' => 'Credit_Assessment__c',
                                                    'Lead' => 'Lead__c',
                                                    'ODG' => 'ODG__c',
                                                    'Operation' => 'Operation__c',
                                                    'Opportunity' => 'Opportunity__c',
                                                    'User' => 'User__c',
                                                    'Campaign' => 'Campaign__c',
                                                    'Task' => 'Task_Id__c',
                                                    'Additional Debt' => 'Additional_Debt__c',
                                                    'Product' => 'Product2' ,
                                                    'Program' => 'Program__c' ,
                                                    'Program Product Association' => 'Program_Product_ASO__c',
                                                    'Reward' => 'Reward__c',            
            										'Loan Management'  => 'Loan_Management__c',
            										'Loan Ledger' => 'Loan_Ledger__c',
            										'Loan Management Event' => 'Loan_Management_Event__c'
            };
        
        mapDataTypeObjectApiName =  new Map<String, String> { 'Account' => 'Account',
                                                    'Case' => 'Case',
                                                    'Contact' => 'Contact',
                                                    'Credit Assessment' => 'Credit_Assessment__c',
                                                    'Lead' => 'Lead',
                                                    'ODG' => 'Guarantors__c',
                                                    'Operation' => 'Operation__c',
                                                    'Opportunity' => 'Opportunity',
                                                    'User' => 'User',
                                                    'Campaign' => 'Campaign',
                                                    'Task' => 'Task',
                                                    'Additional Debt' => 'Additional_Debt__c',
                                                    'Product' => 'Product2' ,
                                                    'Program' => 'Program__c' ,
                                                    'Program Product Association' => 'Program_Product_ASO__c',
                                                    'Reward' => 'Reward__c',            
            										'Loan Management'  => 'Loan_Management__c',
            										'Loan Ledger' => 'Loan_Ledger__c',
            										'Loan Management Event' => 'Loan_Management_Event__c'
            };
        
        mapApiNameDataType = new Map<String, String> { 'Account' => 'Account',
                                                    'Case' => 'Case',
                                                    'Contact' => 'Contact',
                                                    'Credit_Assessment__c' => 'Credit Assessment',
                                                    'Lead' => 'Lead',
                                                    'Guarantors__c' => 'ODG',
                                                    'Operation__c' => 'Operation',
                                                    'Opportunity' => 'Opportunity',
                                                    'User' => 'User',
                                                    'Campaign' => 'Campaign',
                                                    'Task' => 'Task',
                                                    'Additional_Debt__c' => 'Additional Debt',
                                                    'Product2' => 'Product' ,
                                                    'Program__c' => 'Program' ,
                                                    'Program_Product_ASO__c' => 'Program Product Association',
                                                    'Reward__c' => 'Reward',
            										'Loan_Management__c'  => 'Loan Management',
            										'Loan_Ledger__c' => 'Loan Ledger',
            										'Loan_Management_Event__c' => 'Loan Management Event'
            };
                                                    
        mapObjectNameFieldSet = new Map<String, String>{
                                                    'Lead' => 'DWH_Lead',
                                                    'Account' => 'DWH_Account',
                                                    'Case' => 'DWH_Case',
                                                    'Contact' => 'DWH_Contacts',
                                                    'Credit_Assessment__c' => 'DWH_Credit_Assessment',
                                                    'Operation__c' => 'DWH_Operations',
                                                    'Opportunity' => 'DWH_Opportunity',
                                                    'Guarantors__c' => 'DWH_ODG',
                                                    'User' => 'DWH_User',
                                                    'Campaign' => 'DWH_Campaign',
                                                    'Task' => 'DWH_Task',
                                                    'PersonAccount' => 'DWH_PersonAccount', 
                                                    'Additional_Debt__c' => 'Additional_Debt',
                                                    'Product2' => 'DWH_Product',
                                                    'Program__c' => 'DWH_Program',
                                                    'Program_Product_ASO__c' => 'DWH_Product_Program_Combination',
                                                    'Reward__c' => 'DWH_Reward',
                                                    'Loan_Management__c' => 'DWH_Loan_Management',
                                                    'Loan_Ledger__c' => 'DWH_Loan_Ledger',
                                                    'Loan_Management_Event__c' => 'DWH_Loan_Management_Event'   
                                                    };
    }
    
    public static final String REQUEST_HEADER_DATE = 'x-amp-date';
    public static final String REQUEST_HEADER_AUTH = 'x-amp-auth';
    
}