src/objects/Additional_Debt__c.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Debts</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Select to add a new contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Guarantors__c.object
<CustomObject>
    <description>AMP Guarantors Custom Object</description>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Owner/Director/Guarantor</label>
    <nameField>
        <displayFormat>ODG-{000000}</displayFormat>
        <label>Owners/Directors/Guarantors</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Owners/Directors/Guarantors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loan_Ledger__c.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Loan Ledger</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_Management__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <formula>HYPERLINK(&apos;/apex/Loan_RulesEngine?ID=&apos;+Program_Product_ASO__c, &apos;Edit&apos;, &apos;_self&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Action</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rules Engine</label>
    <nameField>
        <displayFormat>LM-{000}</displayFormat>
        <label>Loan Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules Engines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Management_Event__c.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Loan Management Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Management Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <formula>HYPERLINK(&apos;/apex/Loan_Product?ID=&apos;+Id, &quot;Edit&quot; ,&quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Action</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <formula>HYPERLINK(&apos;/apex/Loan_Program?ID=&apos;+ Id , &quot;Edit&quot; ,&quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Action</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reward__c.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Additional_Debt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Debt</label>
        <referenceTo>Additional_Debt__c</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Incentive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission/Incentive</label>
        <referenceTo>Reward__c</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sync_Status__c</fullName>
        <label>Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sync Queue</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Sync Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CRMS_SObjectUtility.cls
/*
* Class for utilities for all SObjects
*
* Revision History: 

* Functionality :
*1. Add extra check in dymanic query for task (generateQuery function)
*
* Version       Author             Date           Description 
*  1.0           CRMS                             Initial Draft 
*
* Version       Author             Date           Description 
*  1.1           CRMS             13-07-2013     Functionality(1) 
*/

public without sharing class CRMS_SObjectUtility {

    //Method to generate query for all fields for Sync_Queue object
    public static String generateQueryForQueue() {
        String query = 'SELECT ';
        Map<String, Schema.SObjectField> mapQueueFields = Sync_Queue__c.getSObjectType().getDescribe().fields.getMap();
        for(String strField : mapQueueFields.keySet()) {
            Schema.DescribeFieldResult objField = mapQueueFields.get(strField).getDescribe();
            if(objField.isAccessible())
                query += objField.getName() + ', ';
        } //End of for loop for fields
        
        query = query.removeEnd(', ') + ' FROM Sync_Queue__c';
        return query;
    }
    
    //Method to get all the info for Sync_Queue records incl. parent fields
    public static String generateQueryForQueueParents() {
        String query = 'SELECT ';
        Map<String, Schema.SObjectField> mapQueueFields = Sync_Queue__c.getSObjectType().getDescribe().fields.getMap();
        for(String strField : mapQueueFields.keySet()) {
            Schema.DescribeFieldResult objField = mapQueueFields.get(strField).getDescribe();
            if(objField.isAccessible()) {
                if(objField.getRelationshipName() != null && objField.getReferenceTo()[0].getDescribe().fields.getMap().containsKey('DWH_Status__c')) {
                    query += objField.getRelationshipName() + '.DWH_Status__c, ';
                }
                query += objField.getName() + ', ';
            }
        } //End of for loop for fields
        query = query.removeEnd(', ') + ' FROM Sync_Queue__c';
        return query;
    }
/*
    //Method to generate dynamic query for Lead with all fields
    public static String generateQueryForLead() {
        String query = 'SELECT ';
        Map<String, Schema.SObjectField> mapLeadFields = Lead.getSObjectType().getDescribe().fields.getMap();
        for(String strField : mapLeadFields.keySet()) {
            Schema.DescribeFieldResult objField = mapLeadFields.get(strField).getDescribe();
            if(objField.isAccessible())
                query += objField.getName() + ', ';
        } //End of for loop for lead fields
        
        query += '(SELECT Lead__c, Action__c, Notes__c, Sync_Status__c FROM Sync_Queues__r) ';
        //query = query.removeEnd(', ');
        query += ' FROM Lead';
        
        return query;
    }
    */
    //Method used to create the dynamic query for object based on the id passed
    public static String generateQuery(ID objectID) {
        String query = '';
        Map<String, String> mapOfObjectNames = new Map<String, String>{
                                                                    'Lead' => 'Lead__c',
                                                                    'Account' => 'Account__c',
                                                                    'Case' => 'Case__c',
                                                                    'Contact' => 'Contact__c',
                                                                    'Credit_Assessment__c' => 'Credit_Assessment__c',
                                                                    'Operation__c' => 'Operation__c',
                                                                    'Opportunity' => 'Opportunity__c',
                                                                    'Guarantors__c' => 'ODG__c',
                                                                    'User' => 'User__c',
                                                                    'Campaign' => 'Campaign__c',
                                                                    'Task' => 'Task_Id__c',
                                                                    'Additional_Debt__c' => 'Additional_Debt__c',
                                                                    'Reward__c' => 'Reward__c',
                                                                    'Product2' => 'Product__c',
                                                                    'Program__c' => 'Program__c',
                                                                    'Program_Product_ASO__c' => 'Program_Product_ASO__c',
                                                                    'Loan_Management__c'   => 'Loan_Management__c',
                                                                    'Loan_Ledger__c'   => 'Loan_Ledger__c',
                                                                    'Loan_Management_Event__c' => 'Loan_Management_Event__c'
                                                                    };
        
        List<Account> lstAccount = new List<Account> ();
        if(Account.getSObjectType() == objectId.getSObjectType())
            lstAccount = [SELECT isPersonAccount 
                                FROM Account
                                WHERE Id =: objectId
                                LIMIT 1];
        
        String objectAPIName = objectID.getSObjectType().getDescribe().getName();
        if( objectAPIName != null ){
            query = 'SELECT ';
            Map<String, Schema.SObjectField> mapFieldNames = Id.valueOf(objectId).getSObjectType().getDescribe().fields.getMap();
            List<Schema.FieldSetMember> lstFields = Id.valueOf(objectID).getSObjectType().getDescribe().fieldsets.getMap().get(CRMS_Constants.mapObjectNameFieldSet.get(objectAPIName)).getFields();
            
            //If account is a person account then add every field from account to the query
            if(lstAccount != null && !lstAccount.isEmpty() && lstAccount.get(0).isPersonAccount) {
                for(String fieldName : mapFieldNames.keySet()) {
                    Schema.DescribeFieldResult objField = mapFieldNames.get(fieldName).getDescribe();
                    if(objField.isAccessible())
                        query += objField.getName() + ',';
                } //End of for loop for every field
            } //End of if account is a person account
            else {
                for(Schema.FieldSetMember strField : lstFields) {
                    if(mapFieldNames.get(strField.getFieldPath()) != null && mapFieldNames.get(strField.getFieldPath()).getDescribe().isAccessible())
                        query += strField.getFieldPath() + ',';
                    //if(objField.isAccessible() && objField.isUpdateable())
                      //  query += objField.getName() + ',';
                } //End of for loop for fields
            } //End of if record is not a person account
            query = query .substring(0,query.length()-1);
             if(objectID.getSObjectType() != Task.getSObjectType()) {
                query += ',(SELECT ' + mapOfObjectNames.get(objectAPIName); 
                query += ', Action__c, Notes__c, Sync_Status__c FROM Sync_Queues__r WHERE Sync_Status__c = \'Pending\') ';       
             }
            query += ' FROM ' + objectAPIName;
            
        }
        system.debug('query  ------>'+query );
        //System.debug(Logginglevel.ERROR, 'Miro Debug >_> ::' + Json.serializePretty(query));
        return query;
    }
    
    //Method to generate query from object name
    public static String generateQueryFromObjectName(String objectName) {
        String query = 'SELECT ';
        String objectApiName = CRMS_Constants.mapDataTypeObjectApiName.get(objectName);
        
        Map<String, Schema.SObjectType> mapDescribeAll = Schema.getGlobalDescribe();
        Map<String, Schema.SObjectField> mapFieldNames = mapDescribeAll.get(objectApiName).getDescribe().fields.getMap();
        List<Schema.FieldSetMember> lstFields = mapDescribeAll.get(objectApiName).getDescribe().fieldsets.getMap().get(CRMS_Constants.mapObjectNameFieldSet.get(objectAPIName)).getFields();
        
        //If object is Account, add all the fields in the query
        if(objectName.equals('Account')) {
            for(String fieldName : mapFieldNames.keySet()) {
                Schema.DescribeFieldResult objField = mapFieldNames.get(fieldName).getDescribe();
                    if(objField.isAccessible())
                        query += objField.getName() + ', ';
            } //End of for all fields
        } //End of if object name is account
        else {
            for(Schema.FieldSetMember strField : lstFields) {
                if(mapFieldNames.get(strField.getFieldPath()) != null && mapFieldNames.get(strField.getFieldPath()).getDescribe().isAccessible())
                    query += strField.getFieldPath() + ', ';
            } //End of for loop for fields
            
            if(system.isBatch())
                query += 'DWH_Status__c, ';
        } //End of if object name is not account
        
        if(objectName.equals(CRMS_Constants.DWH_DATA_TYPE_TASK)) {
            return query.removeEnd(', ') + ' FROM Task';
        }
        
        query += '(SELECT ' + CRMS_Constants.mapDataTypeObjectName.get(objectName); 
        query += ', Action__c, Notes__c, Sync_Status__c FROM Sync_Queues__r WHERE Sync_Status__c = \'Pending\') ';
        query += ' FROM ' + CRMS_Constants.mapDataTypeObjectApiName.get(objectName);
        return query;
    }
    
    /*--- Danail 10/03/2016 ---- */
    /*--- Source: http://sfdc.arrowpointe.com/2011/03/28/cloning-records-in-apex/ ---*/
    
    public static String generateQueryForClone(ID objectId)
    {
        String fieldsToSelect = '';
                   
        // Get a map of field name and field token
        Map<String, Schema.SObjectField> fMap = objectId.getSobjectType().getDescribe().Fields.getMap();
        list<string> selectFields = new list<string>();
         
        if (fMap != null){
            for (Schema.SObjectField ft : fMap.values()){ // loop through all field tokens (ft)
                Schema.DescribeFieldResult fd = ft.getDescribe(); // describe each field (fd)
                if (fd.isCreateable()){ // field is creatable
                    selectFields.add(fd.getName());
                }
            }
        }
         
        if (!selectFields.isEmpty()){
            for (string s:selectFields){
                fieldsToSelect += s + ',';
            }
            if (fieldsToSelect.endsWith(','))
            {
                fieldsToSelect = fieldsToSelect.substring(0, fieldsToSelect.lastIndexOf(','));
            }
             
        }
         
        return 'SELECT ' + fieldsToSelect + ' FROM ' + objectId.getSobjectType() + ' WHERE Id=\'' + objectId + '\'';
    }
    
    /*--------------------------*/
}