src/objects/AMPSync_Queue__c.object
<CustomObject>
    <label>AMPSync Queue</label>
    <nameField>
        <displayFormat>SQ-{00000000}</displayFormat>
        <label>Queue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMPSync Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Accepts_Credit_Cards__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accepts Credit Cards</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Legal_Name__c</fullName>
        <label>Business Legal Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Nature__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Nature</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Registered_in_Hong_Kong__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Registered in Hong Kong</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Registered_in_Philippines__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Registered in Philippines</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Registered_in_Singapore__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Registered in Singapore</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Registered_in_UK__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The business must be registered in your designated country.</inlineHelpText>
        <label>Business Registered in UK</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_in_Operation_Minimum_3_months__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business in Operation Minimum 3 Months</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_in_Operation_Minimum_6_months__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business in Operation Minimum 6 months</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Callback_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Marks if the client requested a callback to express.</description>
        <inlineHelpText>Has a callback been requested to express interest?</inlineHelpText>
        <label>Callback Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Convert_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if a particular lead is assigned to a partner user or not.</description>
        <label>Convert Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Converted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DWH_Import__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DWH Import</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Do_Not_Mail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Mail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Do_Not_Txt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Txt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LE_Country__c</fullName>
        <label>LE Country</label>
        <picklist>
            <picklistValues>
                <fullName>England</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hong Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philippines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Website_Tracker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner Tracker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>Partner</value>
            </filterItems>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>Account.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Partner_Leads</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Program__c.Country_Mapping__c</field>
                <operation>equals</operation>
                <valueField>$Source.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TA_Country__c</fullName>
        <label>TA Country</label>
        <picklist>
            <picklistValues>
                <fullName>England</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hong Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philippines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trading_Address_if_different__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trading Address (if different)</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>DWH_Import__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DWH Import</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>DWH_Import__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DWH Import</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AMPSyncApp_Util_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class AMPSyncApp_Util_Test {
 
    private static final AMPSync_Queue__c[] Queue = new AMPSync_Queue__c[]{};
    private static final Lead[] Leads = new Lead[]{};    
    private static final Account[] Accounts = new Account[]{};
    private static final Program__c[] LoanPrograms = new Program__c[]{};
    private static final integer RECORDLIMIT = 10;
        
    static testMethod void TestScheduleJobToRemoveFromQueue() {
        // TO DO: implement unit test
        
       Profile testProfile = [SELECT Id 
                           FROM profile
                           WHERE Name = 'System Administrator' 
                           LIMIT 1];            
       
       User testadminuser = new User(alias = 'hasrole', email='userwithrole@roletest.com',
                                    emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                                    localesidkey='en_US', profileid = testProfile.Id, 
                                    timezonesidkey='America/Los_Angeles', username='userwithrole@testorg.com');
                  
       system.runAs(testadminuser){
            test.startTest();
            
            RecordType RecTypeAcc = [Select r.Id From RecordType r 
                            Where SobjectType = 'Account' AND DeveloperName like 'Partner_UK' limit 1];
            
            for(integer i=1; i<=1; i++){
                Accounts.add( new Account(
                    RecordTypeId = RecTypeAcc.Id, 
                    Name         = 'Standard Charted Bank Branch',              
                    Bank_Account_Number__c      = '809647175001'                
                )); 
            }
            
            Database.insert(Accounts);
            /*
            for(integer i=1; i<=RECORDLIMIT; i++){
                Leads.add( new Lead(
                    Program__c              =,
                    LastName                =,
                    FirstName               =,  
                    Company                 =,
                    Accepts_Credit_Cards__c =,
                    Convert_Lead__c         =,
                    LeadSource              =,
                    CurrencyISOCode         =,
                    HasOptedOutOfEmail      =,
                    IsConverted             =,
                    DoNotCall               =,
                    HasOptedOutOfFax        =,
                    Business_Legal_Name__c  =,
                    Converted__c            =,
                    Partner_Website_Tracker__c  =,
                    Callback_Requested__c       =,
                    Business_Nature__c          =,
                    TA_Country__c           =,
                    LE_Country__c           =,
                    IsUnreadByOwner         =,
                    Do_Not_Mail__c          =,
                    Do_Not_Txt__c           =,
                    DWH_Import__c           =,
                    Trading_Address_if_different__c             =,
                    Business_Registered_in_UK__c                =,
                    Business_Registered_In_Hong_Kong__c         =,
                    Business_Registered_In_Philippines__c       =,
                    Business_Registered_In_Singapore__c         =,
                    Business_In_Operation_Minimum_3_Months__c   =,
                    Business_In_Operation_Minimum_6_Months__c   =
                ));
            }*/             
                   
            test.stopTest();
        }
    }    
}