src/objects/Bank_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Branch_No__c</fullName>
        <label>Bank Branch No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_No__c</fullName>
        <label>Bank No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UK</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>HK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bank Detail</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Converted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hong Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philippines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Program__c.Country_Mapping__c</field>
                <operation>equals</operation>
                <valueField>$Source.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>UK</fullName>
        <active>true</active>
        <businessProcess>Lead Process</businessProcess>
        <description>Lead belongs to UK</description>
        <label>UK</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Country__c</fullName>
        <formula>IF(contains(RecordType.DeveloperName,&apos;UK&apos;),&apos;UK&apos;, 
IF(contains(RecordType.DeveloperName,&apos;Hong&apos;),&apos;HK&apos;, 
IF(contains(RecordType.DeveloperName,&apos;Singapore&apos;),&apos;SG&apos;,&apos;PP&apos;)))</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted(Written-off)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disbursed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Disbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Topped-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Hong Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philippines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Program__c</field>
                <operation>equals</operation>
                <valueField>Program_Product_ASO__c.Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program_Product_ASO__c.Rules_Engine__c</field>
                <operation>notEqual</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>contains</operation>
                <valueField>Program__c.Country_Mapping__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Operation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Operation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Operation__c.Opportunity__r.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Check_Name__c</fullName>
        <label>Check Name</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UK</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Channel_partner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It indicates whether the program is associate to a specific channel or bank partner</description>
        <label>Channel partner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Check_Name__c</fullName>
        <label>Unique Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UK</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>It determines the duration of a program’s validity</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Institution_Code__c</fullName>
        <label>Institution Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originator_Name__c</fullName>
        <label>Originator Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Salesforce account object (channel partner type)</description>
        <label>Partner Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner UK, Partner HK, Partner SG, Partner PP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <description>AMP(or partner name) “Country code”. The name cannot be manually entered but it is automatically generated</description>
        <formula>TEXT(Country__c) &amp;&quot;-&quot;&amp;  Partner_name__r.Name</formula>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Share_P__c</fullName>
        <description>Provides the percentage of revenue share agreed with the channel/bank revenue share agreement</description>
        <label>Revenue Share %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Revenue_share__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether a revenue share agreement with a channel or bank partner is in place</description>
        <label>Revenue share</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>It determines the duration of a program’s validity</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <recordTypes>
        <fullName>UK</fullName>
        <active>true</active>
        <label>UK</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Check_Name__c</fullName>
        <label>Check Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <formula>Program__r.Program_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>PPAS</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Loan_Program_Controller.cls
public class Loan_Program_Controller {
    public ID recID {get; set;}
    public boolean isStepTwo {get; set;}
    public boolean isNewRecord {get; set;}    
    public boolean isEditRecord {get; set;}
    public boolean isRecordSaved {get; set;}
    public boolean disableIsActive {get; set;}
    public boolean isDeleteActive {get; set;}
    public boolean hasErrors { get; set; }
    
    public Program__c p  {get; set;}      
    public String selectedPartner{get; set;}    
    public String selectedBankVal{get; set;} 
    public String selectedProductVal{get; set;}
    public Account partner {get; set;}
    public Integer countIdChosen{get; set;}
    
    public List<Program__c> allPrograms {get; set;}
    public List<Bank_Detail__c> banks {get; set;}
    public Map<String,Account> accMap {get; set;}
    public List<Program_Product_ASO__c> aso {get; set;} 
    public List<Program_Product_ASO__c> delItemList {get; set;}
    
    public String disableIsActiveHelpMsg {get; set;}
    
    public Loan_Program_Controller(ApexPages.StandardController stdController) {
        
        recID = ApexPages.currentPage().getParameters().get('id');
        isStepTwo = true; 
        
        
        
        if(recID == null)
        {
            this.p = (Program__c)stdController.getRecord();
            isRecordSaved = false;
        }            
        else
        {
            this.p = [Select Id, Channel_partner__c, Country__c, CreatedById, CreatedDate, CurrencyIsoCode, IsDeleted, End_Date__c,
                      LastModifiedById, LastModifiedDate, Name, OwnerId, Partner_name__c, Program_Name__c, RecordTypeId, 
                      Revenue_Share_P__c, Revenue_share__c, Start_Date__c, SystemModstamp, Check_Name__c, isActive__c,
                      Partner_name__r.Name,Partner_name__r.Bank_Account_Number__c,Partner_name__r.Bank_Name__c,
                      Partner_name__r.Bank_Account_Holder_Name__c,Partner_name__r.Bank_Name_Lookup__c,
                      Partner_name__r.Bank_No__c,Partner_name__r.Bank_Branch_No__c,Partner_name__r.Bank_Account_Sort_Code__c,
                      Originator_Name__c,Institution_Code__c                       
                      FROM Program__c Where id = :recID][0];
                      //
            isNewRecord=true;
            isRecordSaved = true;
            selectedPartner = p.Partner_name__c;
            
            partner = new Account(Name = p.Partner_name__r.Name,
                                  Bank_Account_Number__c = p.Partner_name__r.Bank_Account_Number__c,
                                  Bank_Account_Sort_Code__c = p.Partner_name__r.Bank_Account_Sort_Code__c,
                                  //Bank_No__c = p.Partner_name__r.Bank_No__c,
                                  Bank_Name_Lookup__c = p.Partner_name__r.Bank_Name_Lookup__c,
                                  Bank_Account_Holder_Name__c = p.Partner_name__r.Bank_Account_Holder_Name__c,
                                  Bank_Branch_No__c = p.Partner_name__r.Bank_Branch_No__c
                                 );
            aso = [Select Id, Name, Program__c, Product__c, Product__r.Name,
                   //(Select Status__c From Operations__r Where Status__c Not In ('Completed', 'Loan Withdrawn', 'Cancelled')),
                   //(Select IsClosed From Opportunities__r Where IsClosed = false)
                   
                   (Select Status__c From Operations__r),   //LMS-153 - hide Delete/Remove option if a program/product has been used once
                   (Select IsClosed From Opportunities__r)
                   From Program_Product_ASO__c Where Program__c = :p.Id Order By Product__r.Name];
            
            disableIsActive = true;
            
            if([select Id from Operation__c where Program_Product_ASO__r.Program__c =:p.Id and Status__c Not In ('Completed', 'Loan Withdrawn', 'Cancelled')].size() > 0)
                disableIsActiveHelpMsg = 'There is an active Loan using this Program';
            else if([select Id from Opportunity where Program__c  =:p.Id and IsClosed = false].size() > 0)
                disableIsActiveHelpMsg = 'There is a live Opportunity using this Program';
            else if([select Id from Lead where Program__c  =:p.Id and Converted__c = false].size() > 0)
                disableIsActiveHelpMsg = 'There is a live Lead using this Program';
            else 
                disableIsActive = false;
                      
            //LMS-153 - hide Delete/Remove option if a program/product has been used once
            if([select Id from Lead where Program__c  =:p.Id].size() > 0 ||
               [select Id from Opportunity where Program__c  =:p.Id].size() > 0 || 
               [select Id from Operation__c where Program_Product_ASO__r.Program__c =:p.Id].size() > 0)
                    isDeleteActive = false;
                else
                    isDeleteActive = true;
        }
        //if(p.Country__c == null)  p.Country__c = 'UK';
        //if(p.Partner_name__c == null)  {p.Partner_name__r = new Account(); p.Partner_name__r.Name = 'Partner Name';}
        if(isNewRecord != true) getAllPrograms();
        if(accMap == null){ accMap = new Map<String,Account>();}
        if(partner == null ) partner = new Account(Name='Partner Name');
        if(aso == null) aso = new List<Program_Product_ASO__c>();
        if(delItemList == null) delItemList = new List<Program_Product_ASO__c>();
        if(disableIsActive == null) disableIsActive = false;
        if(isDeleteActive == null) isDeleteActive = true;
        
        hasErrors = false;
    }
    
   
    public PageReference addAssociation()
    {
        for(Program_Product_ASO__c ppaso : aso){
            //Avoid duplicate Products
            if(ppaso.Product__c == selectedProductVal) return null;
            
        }
        
        aso.add(new Program_Product_ASO__c(Program__c = p.Id,Product__c=selectedProductVal, CurrencyISOCode = p.CurrencyIsoCode));
        
        //This is here and not in save() because else the Product Name stays empty due to using reference    
        upsert aso;        
         aso = [SELECT Id, Name, Program__c, Product__c, Product__r.Name FROM Program_Product_ASO__c where Program__c = :p.Id Order By Product__r.Name];

            Pagereference pr = new Pagereference('/apex/Loan_Program');
            pr.getParameters().put('ID',p.id);
            pr.setRedirect(true);
            return pr;
    } 
    public PageReference delRow(){
        //system.debug('countIdChosen'+ countIdChosen);
        Program_Product_ASO__c tempItem = aso.get(countIdChosen);//system.debug('tempItem'+ tempItem);
        //if(tempItem.id != null)  delItemList.add(tempItem);//system.debug('delItemList'+ delItemList);
        delete tempItem;
        
        aso = [SELECT Id, Name, Program__c, Product__c, Product__r.Name FROM Program_Product_ASO__c where Program__c = :p.Id Order By Product__r.Name];

            Pagereference pr = new Pagereference('/apex/Loan_Program');
            pr.getParameters().put('ID',p.id);
            pr.setRedirect(true);
            return pr;
    }
    
    private void getAllPrograms(){
        allPrograms = new List<Program__c>();
        allPrograms =[Select id,Name,CreatedBy.Name,CreatedBy.ID, LastModifiedDate, isActive__c from Program__c Order by LastModifiedDate DESC];
    }
    
    public List<SelectOption> getProductOptions(){
        List<SelectOption> optns = new List<SelectOption>();
        List<Product2> prodList = new List<Product2>();
        Set<Id> selectedProdList = new Set<Id>();
        for(Program_Product_ASO__c tempASO : aso){
            selectedProdList.add(tempASO.Product__c);
        }
        prodList = [Select id,Name From Product2 Where Country__c = :p.Country__c And ID NOT IN :selectedProdList Order By Name];
        for(Product2 b : prodList){
           optns.add(new selectOption(b.id, b.Name));
        }            
        return optns;
    }
    public List<SelectOption> getPartnerNameOptions(){
        List<SelectOption> optns = new List<SelectOption>();
        List<Account> accList;
        accList = new List<Account>();
        accMap = new Map<String,Account>();
        //partner = new Account();
        String recType;
        
            //Get Account Record types for Partner dropdown
            Map<String,ID> accPartnerRecTypesMap = new Map<String,ID>();
            List<RecordType> accPartnRecTypes = new List<RecordType>();
            accPartnRecTypes = [Select Name,ID from RecordType where SobjectType = 'Account' and Name like '%Partner%' ];
            for(RecordType rt : accPartnRecTypes){
                accPartnerRecTypesMap.put(rt.Name, rt.Id);
            } 
        system.debug('p.Country__c' + p.Country__c);
        
            if(p.Country__c =='UK') recType = 'Partner UK';
            else if (p.Country__c =='SG') recType = 'Partner SG';        
            else if (p.Country__c =='PH') recType = 'Partner PP';
            else if (p.Country__c =='HK') recType = 'Partner HK';       
        accList = [Select ID,Name,Bank_Account_Number__c,Bank_Account_Holder_Name__c,Bank_No__c,Bank_Branch_No__c,Bank_Account_Sort_Code__c,Bank_Name__c from Account where RecordTypeID = : accPartnerRecTypesMap.get(recType) order by Name]; //
        optns.add(new selectOption('','--None--'));
        // before getting here you must populate your queryResult list with required fields
        for(Account a : accList){
           accMap.put(a.id,a);
           optns.add(new selectOption(a.Id, a.Name));

        }
        
                
        return optns;
    }
    public PageReference getPartnerAccount(){
        if(selectedPartner!=null&&!accMap.isEmpty()){
            partner = accMap.get(selectedPartner);
             system.debug('inside:'+selectedPartner);
            
        }
        system.debug('partner:'+partner);
        
        return null; 
    } 
    
    public PageReference save (){
        
        try{
            p.Partner_name__c = selectedPartner;
            p.CurrencyIsoCode = AMP_Utils.getCurrencyISOByCountryCode(p.Country__c);
            system.debug('p'+p);
            p.Partner_name__r = null;
            upsert p;
            isStepTwo = true;  
            
            if(!delItemList.isEmpty()){
                delete delItemList;
            }
            
            isRecordSaved = true;
            //system.debug('aso:'+JSON.serializePretty(selectedProductVal));
            
            Pagereference pr = new Pagereference('/apex/Loan_Program');
            //pr.getParameters().put('ID',p.id);
            pr.setRedirect(true);
            return pr;
            
        }catch(DmlException e){
            String mess = e.getMessage();
            system.debug('mess :: '+mess);
            String existingID = mess.substringAfter('id: ').removeEnd(': []');
            system.debug('existingID:' + existingID);
            boolean checkName = mess.containsIgnoreCase('Check_Name__c');
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'A program with the same name already exists. You can open it <b><a href="Loan_Program?ID='+existingID+'" style="margin:0 0px;">here</a></b> ');
            //ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, checkName ? 'A program with the same name already exists. You can open it <b><a href="Loan_Program?ID='+existingID+'" style="margin:0 0px;">here</a></b> ' : 'Sorry :/');
            system.debug(' myMsg :: '+myMsg);
            ApexPages.addMessage(myMsg);
            if(existingID != null && existingID != '')
                hasErrors = true;
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,mess));
        }   
        return null;
        
    }
     
    public PageReference newRec()
    {
        isNewRecord = true;
        return null;
    } 
    public PageReference deleteRecord () {
        delete aso;
        delete p;
        
        Pagereference pr = new Pagereference('/apex/Loan_Program');
        pr.setRedirect(true);
        return pr;
    }    
    public PageReference cancel () {
        Pagereference pr = new Pagereference('/apex/Loan_Program');
        pr.setRedirect(true);
        return pr;
    }

}