src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Select to add a new contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DWH_Data_Type__c</fullName>
        <label>DWH Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Product Association</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission/Incentive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Ledger</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Queued_Record_ID__c</fullName>
        <label>Queued Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Status__c</fullName>
        <label>Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sync Queue</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Sync Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CRMS_DwhSyncBatch.cls
/**
    Batch class for performing synchronization with DWH
    Author: Saket Joshi
    Version: 1.0
*/

public class CRMS_DwhSyncBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
    
	private static final Integer BATCH_RUN_FREQUENCY_IN_MINUTES = 5;
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = CRMS_SObjectUtility.generateQueryForQueueParents() + ' WHERE Queued_Record_Id__c != null AND DWH_Data_Type__c != null AND Sync_Status__c = \'Pending\'';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext info, List<SObject> lstSyncQueue) {
        Map<String, List<Sync_Queue__c>> mapDataTypeSyncQueue = new Map<String, List<Sync_Queue__c>> ();
        List<Sync_Queue__c> lstQueue = new List<Sync_Queue__c> ();
        Set<Sync_Queue__c> setQueueToUpdate = new Set<Sync_Queue__c> ();
        List<String> lstOfPreference = new List<String>{ 'User', 'Campaign', 'Lead', 'Account', 'Contact', 'Opportunity', 'ODG', 'Credit Assessment', 'Operation', 'Case', 'Task' ,	
            'Program', 'Product', 'Program Product Association', 'Reward', 'Loan Management', 'Loan Ledger'}; 
        try{
        if(lstSyncQueue != null && !lstSyncQueue.isEmpty()) {
            lstQueue = (List<Sync_Queue__c>) lstSyncQueue;
            system.debug('lstQueue ----- >'+lstQueue.size());
            for(Sync_Queue__c objQueue : lstQueue) {
                system.debug(System.LoggingLevel.ERROR, 'id***********' + objQueue.Id);
                if(!mapDataTypeSyncQueue.containsKey(objQueue.DWH_Data_Type__c) || mapDataTypeSyncQueue.get(objQueue.DWH_Data_Type__c) == null) {
                    mapDataTypeSyncQueue.put(objQueue.DWH_Data_Type__c, new List<Sync_Queue__c> { objQueue });
                } //If map does not contain the data type
                else {
                    mapDataTypeSyncQueue.get(objQueue.DWH_Data_Type__c).add(objQueue);
                } //If map contains the data type
            } //End of for loop for lstQueue
        } //End of if lstSyncQueue is not empty
        
        for(String strDataType : lstOfPreference ) {
            List<Sync_Queue__c> lstTempQueue = mapDataTypeSyncQueue.get(strDataType);
            if(lstTempQueue != null && !lstTempQueue.isEmpty()) {
                List<Id> lstQueueIdToDelete = new List<Id> ();
                Map<Id, Sync_Queue__c> mapRecordIdSyncQueue = new Map<Id, Sync_Queue__c> ();
                for(Sync_Queue__c objQueue : lstTempQueue) { 
                    mapRecordIdSyncQueue.put((Id)objQueue.get(CRMS_Constants.mapDataTypeObjectName.get(objQueue.DWH_Data_Type__c)), objQueue);
                    if(objQueue.Action__c != null && objQueue.Action__c.equals(CRMS_Constants.SYNC_ACTION_DELETE) && objQueue.Queued_Record_Id__c != null)
                        lstQueueIdToDelete.add(objQueue.Queued_Record_Id__c);
                }
                
                List<SObject> lstRecords = new List<SObject> ();
                Set<Id> setQueueId = new Set<Id> (mapRecordIdSyncQueue.keySet());
                String queryStr = getQueryFromObjectType(strDataType) + 'setQueueId';
                lstRecords = Database.query(queryStr);
                
                Map<String, List<SObject>> mapActionListRecords = new Map<String, List<SObject>> ();
                mapActionListRecords.put(CRMS_Constants.SYNC_ACTION_CREATE, new List<SObject> ());
                mapActionListRecords.put(CRMS_Constants.SYNC_ACTION_UPDATE, new List<SObject> ());
                mapActionListRecords.put(CRMS_Constants.SYNC_ACTION_DELETE, new List<SObject> ());
                List<SObject> lstPersonAccountToInsert = new List<SObject> ();
                List<SObject> lstPersonAccountToUpdate = new List<SObject> ();
                
                if(lstRecords != null && !lstRecords.isEmpty()) {
                    for(SObject sObj : lstRecords) {
                        if(sObj.get('DWH_Status__c') != null && sObj.get('DWH_Status__c').equals(CRMS_Constants.DWH_STATUS_QUEUED)) {
                            if(sObj.getSObjectType() == Account.getSObjectType() && ((Boolean)sObj.get('isPersonAccount')) == true) {
                                //Check Action__c for Sync Queue record
                                if(mapRecordIdSyncQueue.get(sObj.Id).Action__c.equals(CRMS_Constants.SYNC_ACTION_CREATE)) {
                                    lstPersonAccountToInsert.add(sObj);
                                } //End of if queue action is insert
                                else if(mapRecordIdSyncQueue.get(sObj.Id).Action__c.equals(CRMS_Constants.SYNC_ACTION_UPDATE)) {
                                    lstPersonAccountToUpdate.add(sObj);
                                } //End of if queue action is update
                                else if(mapRecordIdSyncQueue.get(sObj.Id).Action__c.equals(CRMS_Constants.SYNC_ACTION_DELETE)) {
                                    mapActionListRecords.get(CRMS_Constants.SYNC_ACTION_DELETE).add(sObj);
                                } //End of if queue action is delete
                            } //End of if account is a person account
                            else {
                                //Check Action__c for Sync Queue record
                                if(mapRecordIdSyncQueue.get(sObj.Id).Action__c.equals(CRMS_Constants.SYNC_ACTION_CREATE)) {
                                    mapActionListRecords.get(CRMS_Constants.SYNC_ACTION_CREATE).add(sObj);
                                } //End of if queue action is insert
                                else if(mapRecordIdSyncQueue.get(sObj.Id).Action__c.equals(CRMS_Constants.SYNC_ACTION_UPDATE)) {
                                    mapActionListRecords.get(CRMS_Constants.SYNC_ACTION_UPDATE).add(sObj);
                                } //End of if queue action is update
                                else if(mapRecordIdSyncQueue.get(sObj.Id).Action__c.equals(CRMS_Constants.SYNC_ACTION_DELETE)) {
                                    mapActionListRecords.get(CRMS_Constants.SYNC_ACTION_DELETE).add(sObj);
                                } //End of if queue action is delete
                            } //End of if account is not a person account
                        } //End of if DWH Status of lead is Queued
                        else if(sObj.get('DWH_Status__c') != null && sObj.get('DWH_Status__c').equals(CRMS_Constants.DWH_STATUS_SYNCED)) {
                            mapRecordIdSyncQueue.get(sObj.Id).Sync_Status__c = CRMS_Constants.SYNC_STATUS_STALE;
                            if(mapRecordIdSyncQueue.get(sObj.Id).Notes__c == null)
                                mapRecordIdSyncQueue.get(sObj.Id).Notes__c = '';
                            mapRecordIdSyncQueue.get(sObj.Id).Notes__c += '\n' + Datetime.now().format() + CRMS_Constants.BATCH_NO_ACTION_NEEDED;
                            setQueueToUpdate.add(mapRecordIdSyncQueue.get(sObj.Id));
                        } //End of if DWH Status of lead is Synced
                    } //End of for loop for every lead
                    
                    if(lstPersonAccountToInsert != null && !lstPersonAccountToInsert.isEmpty()) {
                        CRMS_HttpResponseWrapper objResponseCreate = CRMS_DwhSyncHandler.doCallout(lstPersonAccountToInsert, CRMS_Constants.SYNC_ACTION_CREATE);
                        setQueueToUpdate.addAll(CRMS_DwhSyncHandler.processBatchResults(lstPersonAccountToInsert, objResponseCreate, CRMS_Constants.SYNC_ACTION_INSERT));
                    } //End of if person account to create list is NOT null
                    
                    if(lstPersonAccountToUpdate != null && !lstPersonAccountToUpdate.isEmpty()) {
                        CRMS_HttpResponseWrapper objResponseCreate = CRMS_DwhSyncHandler.doCallout(lstPersonAccountToUpdate, CRMS_Constants.SYNC_ACTION_CREATE);
                        setQueueToUpdate.addAll(CRMS_DwhSyncHandler.processBatchResults(lstPersonAccountToUpdate, objResponseCreate, CRMS_Constants.SYNC_ACTION_INSERT));
                    } //End of if person account to update list is NOT null
                    
                    if(mapActionListRecords.get(CRMS_Constants.SYNC_ACTION_CREATE) != null && !mapActionListRecords.get(CRMS_Constants.SYNC_ACTION_CREATE).isEmpty()) {
                        CRMS_HttpResponseWrapper objResponseCreate = CRMS_DwhSyncHandler.doCallout(mapActionListRecords.get(CRMS_Constants.SYNC_ACTION_CREATE), CRMS_Constants.SYNC_ACTION_CREATE);
                        setQueueToUpdate.addAll(CRMS_DwhSyncHandler.processBatchResults(mapActionListRecords.get(CRMS_Constants.SYNC_ACTION_CREATE), objResponseCreate, CRMS_Constants.SYNC_ACTION_INSERT));
                    } //End of if map for create is NOT null
                    
                    if(mapActionListRecords.get(CRMS_Constants.SYNC_ACTION_UPDATE) != null && !mapActionListRecords.get(CRMS_Constants.SYNC_ACTION_UPDATE).isEmpty()) {
                        CRMS_HttpResponseWrapper objResponseUpdate = CRMS_DwhSyncHandler.doCallout(mapActionListRecords.get(CRMS_Constants.SYNC_ACTION_UPDATE), CRMS_Constants.SYNC_ACTION_UPDATE);
                        setQueueToUpdate.addAll(CRMS_DwhSyncHandler.processBatchResults(mapActionListRecords.get(CRMS_Constants.SYNC_ACTION_UPDATE), objResponseUpdate, CRMS_Constants.SYNC_ACTION_UPDATE));
                    } //End of if map for update is NOT null
                    
                } //End of if lstRecords is NOT empty
                
                if(lstQueueIdToDelete != null && !lstQueueIdToDelete.isEmpty()) {
                    system.debug('lstQueueIdToDelete in Batch:' + lstQueueIdToDelete);
                    CRMS_HttpResponseWrapper objResponseDelete = CRMS_DwhSyncHandler.doCalloutForDelete(lstQueueIdToDelete);
                    setQueueToUpdate.addAll(CRMS_DwhSyncHandler.processBatchResultsForDelete(lstQueueIdToDelete, objResponseDelete));
                    
                    system.debug('objResponseDelete in Batch after Delete:' + JSON.serialize(objResponseDelete));
                } //End of if lstQueueIdToDelete is NOT null
                
            } //End of if lstSyncQueue is not empty
        }
        List<Sync_Queue__c> lstToUpdate = new List<Sync_Queue__c> ();
        lstToUpdate.addAll(setQueueToUpdate);
        if( lstToUpdate.size() > 0 )
            update lstToUpdate;
        }catch( Exception e){
            system.debug('------ Exception Is -------------'+e.getMessage());
        }
        
    } //end of execute

    //Method to get the dynamic query based on the object type
    private String getQueryFromObjectType(String objectName) {
        String query = CRMS_SObjectUtility.generateQueryFromObjectName(objectName);
        return query + ' WHERE Id IN :';
    }

    public void finish(Database.BatchableContext info) {
        if(!Test.isRunningTest()){
            system.scheduleBatch(new CRMS_DwhSyncBatch (), 'CRMS_DwhSyncBatch:'+system.now(),BATCH_RUN_FREQUENCY_IN_MINUTES, Integer.valueOf(Label.Batch_Record_Size));
        }
    }
}