src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DWH_Data_Type__c</fullName>
        <label>DWH Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Product Association</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission/Incentive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Ledger</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Queued_Record_ID__c</fullName>
        <label>Queued Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Status__c</fullName>
        <label>Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sync Queue</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Sync Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRMS_CampaignTriggerHandlerTest.cls
/**
    Test class for the campaign trigger
    Author: Saket Joshi
    Created Date: 31/03/2015        Version: 1.0
*/

@isTest
public with sharing class CRMS_CampaignTriggerHandlerTest {

    //Method to test the insert of campaigns
    @isTest
    static void testCampaignInsert() {
        List<Campaign> lstCampaign = new List<Campaign> ();
        lstCampaign = CRMS_Util.generateCampaignList(10, false);
        CRMS_Util.generateEndpoints();
        
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        Test.startTest();
        insert lstCampaign;
        Test.stopTest();
        
        for(Campaign objCampaign : [SELECT DWH_Status__c 
                                    FROM Campaign
                                    WHERE Id IN :lstCampaign]) {
            system.assertNotEquals(null, objCampaign.DWH_Status__c);
        } //End of for loop for all inserted campaigns
    }
    
    //Method to test the insert of synced campaigns
    @isTest
    static void testSyncedCampaigns() {
        List<Campaign> lstCampaign = new List<Campaign> ();
        lstCampaign = CRMS_Util.generateCampaignList(10, false);
        CRMS_Util.generateEndpoints();
        
        for(Campaign objCampaign : lstCampaign)
            objCampaign.DWH_Status__c = CRMS_Constants.DWH_STATUS_SYNCED;
        
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        Test.startTest();
        insert lstCampaign;
        Test.stopTest();
        
        for(Campaign objCampaign : [SELECT DWH_Last_Sync__c 
                                    FROM Campaign
                                    WHERE Id IN :lstCampaign]) {
            system.assertNotEquals(null, objCampaign.DWH_Last_Sync__c);
        } //End of for loop for all inserted campaigns
    }
    
    //Method to test the update of campaigns
    @isTest
    static void testCampaignUpdate() {
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        
        List<Campaign> lstCampaign = new List<Campaign> ();
        lstCampaign = CRMS_Util.generateCampaignList(10, true);
        
        Test.startTest();
        for(Campaign objCampaign : lstCampaign)
            objCampaign.DWH_Status__c = null;
        
        update lstCampaign;
        Test.stopTest();
        
        for(Campaign objCampaign : [SELECT DWH_Status__c 
                                    FROM Campaign
                                    WHERE Id IN :lstCampaign]) {
            system.assertNotEquals(null, objCampaign.DWH_Status__c);
        } //End of for loop for all updated campaigns
    }
    
    
    //Method to test campaign delete
    @isTest
    static void testCampaignDelete() {
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        
        List<Campaign> lstCampaign = new List<Campaign> ();
        lstCampaign = CRMS_Util.generateCampaignList(10, true);
        
        Test.startTest();
        delete lstCampaign;
        Test.stopTest();
        
        for(Sync_Queue__c objQueue : [SELECT DWH_Data_Type__c
                                      FROM Sync_Queue__c]) {
            system.assertEquals(CRMS_Constants.DWH_DATA_TYPE_CAMPAIGN, objQueue.DWH_Data_Type__c);
        } //End of for loop for all created sync queues
    }

    //Method to test campaign delete with sync queue records
    @isTest
    static void testCampaignDeleteWithQueue() {
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        
        List<Campaign> lstCampaign = new List<Campaign> ();
        List<Sync_Queue__c> lstQueueToInsert = new List<Sync_Queue__c> ();
        lstCampaign = CRMS_Util.generateCampaignList(10, true);
        
        for(Campaign objCampaign : lstCampaign) {
            lstQueueToInsert.add ( new Sync_Queue__c ( Campaign__c = objCampaign.Id,
                                                        DWH_Data_Type__c = CRMS_Constants.DWH_DATA_TYPE_CAMPAIGN,
                                                        Queued_Record_ID__c = objCampaign.Id,
                                                        Sync_Status__c = CRMS_Constants.SYNC_QUEUE_STATUS_PENDING) );
        }
        
        insert lstQueueToInsert;
        
        Test.startTest();
        delete lstCampaign;
        Test.stopTest();
        
        for(Sync_Queue__c objQueue : [SELECT Notes__c
                                      FROM Sync_Queue__c]) {
            system.assertEquals(null, objQueue.Notes__c);
        } //End of for loop for all created sync queues
    }

}