src/objects/Campaign.object
<CustomObject>
    <recordTypes>
        <fullName>UK</fullName>
        <active>true</active>
        <description>Campaigns for UK</description>
        <label>UK</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Accepts_Credit_Cards__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accepts Credit Cards</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Position__c</fullName>
        <label>Business Position</label>
        <picklist>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shareholder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarantor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CampaignID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Convert_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if a particular lead is assigned to a partner user or not.</description>
        <label>Convert Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TA_Country__c</fullName>
        <label>TA Country</label>
        <picklist>
            <picklistValues>
                <fullName>England</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hong Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philippines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>UK</fullName>
        <active>true</active>
        <businessProcess>Lead Process</businessProcess>
        <description>Lead belongs to UK</description>
        <label>UK</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <formula>Profile.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Profile Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CampaignMemberTrigger_Test.cls
//Author: Miroslav Handzhiev, Xoomworks
@isTest(seeAllData=false)
public class CampaignMemberTrigger_Test {
     static testMethod void testCampaignMemberTrigger()
     {
         
         
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
         
          list<User> lstAdminUser = [Select u.ProfileId, u.IsActive, u.Id, u.Profile.Name, u.Profile_Name__c From User u 
                                    where u.Profile.Name like '%Admin%' And u.IsActive = true];
          list<RecordType> lstUKCampaign = [Select r.SobjectType, r.Name, r.IsActive, r.Id, r.DeveloperName 
                                From RecordType r where SobjectType = 'Campaign' and DeveloperName ='UK'];
          list<RecordType> lstUK = [Select r.SobjectType, r.Name, r.IsActive, r.Id, r.DeveloperName 
                                From RecordType r where SobjectType = 'Lead' and DeveloperName ='UK'];
         Test.startTest(); 
         Campaign c = new Campaign();
            c.Name = 'M Campaign';
            c.RecordTypeId = lstUKCampaign[0].id;
            insert c;
                
                
                
            Lead objLead1 = new Lead();
            objLead1.Convert_Lead__c = false;
            objLead1.RecordTypeId = lstUK[0].Id;
            objLead1.LastName='Holmes';
            objLead1.FirstName='Sherlock';
            objLead1.Business_Position__c = 'Owner';
            objLead1.Company='Bakers';
            objLead1.Status='Open';
            objLead1.Email = 'test5@gmail.com';
            objLead1.Accepts_Credit_Cards__c = true;
            objLead1.TA_Country__c= 'UK';
            objLead1.OwnerId = lstAdminUser[0].Id;
            insert objLead1;
         
         CampaignMember cm = new CampaignMember();
         cm.LeadId = objLead1.Id;
         cm.CampaignId = c.Id;
         insert cm;
         Test.stopTest();
         List<Lead> resList = [Select CampaignID__c from Lead where id = :objLead1.Id];
         system.assertEquals(c.Id, resList[0].CampaignID__c);
         
         
     }

}