src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Operation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operation</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Loan_Management_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Loan</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Loan Management Events</relationshipLabel>
        <relationshipName>Loan_Management_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Loan Management Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Management Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AMPLoan_Case.cls
public with sharing class AMPLoan_Case {
	
	public void CreateNewCase(map<ID, Loan_Management_Event__c> LMEMap){
		list<Case> BounceBackCases = new list<Case>();
		map<string, ID> NLMUsersMap = this.NLMUsersToAssignCase(); 
		try{
			for(Operation__c Op : this.OpportunityForCase(LMEMap.keySet())){
				BounceBackCases.add(new Case(
			        Subject  =  Op.Account__r.Name+' has bounce back on '+string.valueOf(LMEMap.get(Op.Id).Event_Date__c),
			        Status   = 'New',
			        Priority = 'Medium',			        
			        OwnerId  = NLMUsersMap.get(Op.CurrencyIsoCode),
			        Operation__c = Op.Id,       
			        Description = Op.Account__r.Name+
			        			  ' has a bounce back on '+string.valueOf(LMEMap.get(Op.Id).Event_Date__c)+
			        			  ', please check the bounce back detail by following link and take the bounce back event accordingly. Thanks.\r\n\r\n'+
			        			  System.URL.getSalesforceBaseUrl().toExternalForm()+'/apex/LM_LoanDetails?Id='+Op.Id
		        ));
			}
			Database.insert(BounceBackCases);						
		}catch(DMLException ex){}			
	}
	
	private list<Operation__c> OpportunityForCase(set<ID> listOfOperations){
		return [Select o.Id, o.CurrencyIsoCode, o.Account__r.Name, o.Account__c From Operation__c o where Id IN:listOfOperations];
	}
	
	private map<string,ID> NLMUsersToAssignCase(){
		map<string, string> NLMUsers = new map<string, string>{
			'New Loan Manager User (UK)' => 'GBP',
			'New Loans Manager User (HK)' => 'HKD',
			'New Loans Manager User (SG)' => 'SGD',
			'New Loan Manager User (PH)'  => 'PHP'
		};
		
		map<string, ID> NLMUsersMap = new map<string, ID>(); 
		for(User U : [Select u.Name, u.Id From User u 
					where Name IN : NLMUsers.keyset()]){
			NLMUsersMap.put(NLMUsers.get(U.Name), U.Id);											
		}
		return NLMUsersMap;			
	}
}