src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>DWH_Import__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DWH Import</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Assessment</label>
        <referenceTo>Credit_Assessment__c</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DWH_Data_Type__c</fullName>
        <label>DWH Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Product Association</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission/Incentive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Ledger</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Queued_Record_ID__c</fullName>
        <label>Queued Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Status__c</fullName>
        <label>Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sync Queue</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Sync Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRMS_CaseTriggerTest.cls
/**
	Test class for handler for Case trigger
	Author: Saket Joshi
	Version: 1.0
*/

@isTest
public with sharing class CRMS_CaseTriggerTest {

	//Method to test for DWH_Import__c = false on insert
	@isTest
	static void testFalseImport() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		
		List<Case> lstCase = CRMS_Util.generateCaseList(30, false);
		
		Test.startTest();
		//lstCase[0].DWH_Status__c = CRMS_Constants.DWH_STATUS_QUEUED;
		insert lstCase;
		Test.stopTest();
		List<Case> lstCaseNew = new List<Case> ();
		lstCaseNew = [SELECT DWH_Status__c, DWH_Last_Sync__c FROM Case where Id IN : lstCase];
		for(Case objCase : lstCaseNew)
		    system.assertNotEquals(null, objCase.DWH_Status__c);
	}
	
	//Method to test for DWH_Import__c = true on insert
	@isTest
	static void testTrueImport() {
		CRMS_Util objUtil = new CRMS_Util();
		
		CRMS_Util.generateEndpoints();
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		
		List<Case> lstCase = CRMS_Util.generateCaseList(30, false);
		
		Test.startTest();
		for(Case objCase : lstCase)
			objCase.DWH_Status__c = CRMS_Constants.DWH_STATUS_SYNCED;
		
		insert lstCase;
		Test.stopTest();
		List<Case> lstCaseNew = new List<Case> ();
		lstCaseNew = [SELECT DWH_Status__c, DWH_Last_Sync__c FROM Case];
		for(Case objCase : lstCaseNew)
		    system.assertNotEquals(null, objCase.DWH_Status__c);
	}

	//Method to test for DWH_Import = true on update
	@isTest
	static void testImportChangeFalseToTrue() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		
		List<Case> lstCase = CRMS_Util.generateCaseList(30, false);
		//lstCase[0].DWH_Status__c = CRMS_Constants.DWH_STATUS_QUEUED;
		insert lstCase;
		
		Test.startTest();
		for(Case objCase : lstCase)
			objCase.DWH_Status__c = CRMS_Constants.DWH_STATUS_SYNCED;
		
		update lstCase;
		Test.stopTest();
		
        List<Sync_Queue__c> lstSyncQueue = new List<Sync_Queue__c>();
		lstSyncQueue = [SELECT DWH_Data_Type__c, Sync_Status__c, Action__c FROM Sync_Queue__c WHERE Case__c IN: lstCase];

		system.assertNotEquals(0, lstSyncQueue.size());
        
		List<Case> lstCaseNew = new List<Case> ();
		lstCaseNew = [SELECT DWH_Status__c, DWH_Last_Sync__c FROM Case];
		
		system.assertNotEquals(0, lstCaseNew.size());
		for(Case objCase : lstCaseNew)
			system.assertNotEquals(null, objCase.DWH_Status__c);
	}
	
	//Method to test for DWH_Import = false on update
	@isTest
	static void testImportChangeTrueToFalse() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		
		List<Case> lstCase = CRMS_Util.generateCaseList(30, false);
		for(Case objCase : lstCase)
			objCase.DWH_Status__c = CRMS_Constants.DWH_STATUS_SYNCED;
		
		insert lstCase;
		
		Test.startTest();
		for(Case objCase : lstCase)
			objCase.DWH_Status__c = null;
		
		update lstCase;
		Test.stopTest();
		
		List<Case> lstCaseNew = new List<Case> ();
		lstCaseNew = [SELECT DWH_Status__c, DWH_Last_Sync__c FROM Case];
		
		system.assertNotEquals(0, lstCaseNew.size());
		for(Case objCase : lstCaseNew)
			system.assertNotEquals(null, objCase.DWH_Status__c);
	}
	
	//Method to test deletion of Case record
	@isTest
	static void testDeleteCase() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		
		List<Case> lstCase = CRMS_Util.generateCaseList(30, false);
		insert lstCase;
		
		Set<Id> setCaseID = new Set<Id> ();
		for(Case objCase : lstCase)
			setCaseID.add(objCase.Id);
        Sync_Queue__c syncQueue = new Sync_Queue__c();
        syncQueue.Case__c = lstCase[0].Id;
        syncQueue.Sync_Status__c = CRMS_Util.SYNC_QUEUE_STATUS_PENDING;
        insert syncQueue;
		Test.startTest();
		delete lstCase;
		Test.stopTest();
		
		List<Sync_Queue__c> lstSyncQueue = new List<Sync_Queue__c>();
		lstSyncQueue = [SELECT DWH_Data_Type__c, Sync_Status__c, Action__c FROM Sync_Queue__c];

		system.assertNotEquals(0, lstSyncQueue.size());
        
        List<Sync_Queue__c> syncQueListTest1 =[
            SELECT Credit_Assessment__c
                 , Id
                 , Notes__c
                 , Action__c
                 , Queued_Record_ID__c
                 , Sync_Status__c
                 , DWH_Data_Type__c
               FROM Sync_Queue__c 
              WHERE Queued_Record_ID__c = :lstCase[0].Id
        ];
		system.assertEquals(CRMS_Util.SYNC_STATUS_DELETE, syncQueListTest1[0].Action__c);
	}

}