src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Select to add a new contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DWH_Data_Type__c</fullName>
        <label>DWH Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Product Association</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission/Incentive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Ledger</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Queued_Record_ID__c</fullName>
        <label>Queued Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Status__c</fullName>
        <label>Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sync Queue</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Sync Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRMS_DwhSyncBatchTest.cls
/**
	Test class for the batch class for DWH sync
	Author: Saket Joshi
	Created Date: 31/03/2015		Version: 1.0
*/

@isTest
public with sharing class CRMS_DwhSyncBatchTest {

	//Method to create the test data for contacts
	static void createTestData() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		
		List<Account> lstAccount = new List<Account> ();
		List<Sync_Queue__c> lstQueue = new List<Sync_Queue__c> ();
		List<Contact> lstContact = new List<Contact> ();
		List<Contact> lstContactToDelete = new List<Contact> ();
		List<Task> lstTaskToInsert = new List<Task> ();
		
		CRMS_Util.generateCampaignList(10, true);
		CRMS_Util.generateCaseList(10, true);
		
		CRMS_Util.generateUserList(2, true);
		
		for(Integer i = 0 ; i < 10 ; i++) {
			lstTaskToInsert.add( new Task ( Subject = 'Call Testclass', Status = 'Not Started', Priority = 'Normal' ) );
		}
		
		insert lstTaskToInsert;
		objUtil.initializeCreditAssessment(true);
		objUtil.initializeOperation(true);
		Opportunity newOpp = objUtil.initializeOpportunity(true);
		
		objUtil.initializeLead(true);
		for(Integer i = 0 ; i < 10 ; i++) {
			lstAccount.add(objUtil.initializeAccount(false));
		}
		insert lstAccount;
		
		CRMS_Util.generateODGList(10, true, lstAccount[0].Id, newOpp.Id);
		
		lstContact = CRMS_Util.generateContactList(10, true, lstAccount[0].Id);
		for(Account objAccount : lstAccount) {
			lstQueue.add( new Sync_Queue__c ( Account__c = objAccount.Id,
											DWH_Data_Type__c = CRMS_Constants.DWH_DATA_TYPE_ACCOUNT,
											Queued_Record_ID__c = objAccount.Id,
											Sync_Status__c = CRMS_Constants.SYNC_QUEUE_STATUS_PENDING,
											Action__c = CRMS_Constants.SYNC_ACTION_CREATE) );
		}
		
		for(Contact objContact : lstContact) {
			lstQueue.add( new Sync_Queue__c ( Contact__c = objContact.Id,
										DWH_Data_Type__c = CRMS_Constants.DWH_DATA_TYPE_CONTACT,
										Queued_Record_ID__c = objContact.Id,
										Sync_Status__c = CRMS_Constants.SYNC_QUEUE_STATUS_PENDING,
										Action__c = CRMS_Constants.SYNC_ACTION_CREATE) );
		}
		insert lstQueue;
		
		for(Integer i = 0 ; i < 5 ; i++)
			lstContactToDelete.add(lstContact.get(i));
		
		delete [SELECT Id
				FROM Sync_Queue__c
				WHERE Contact__c IN :lstContactToDelete];
				
		delete lstContactToDelete;
	}

	//Method to test the batch for contact records without sync queue records
	@isTest
	static void testBatchWithoutQueue() {
		createTestData();
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		Test.startTest();
		Database.executeBatch(new CRMS_DwhSyncBatch());
		Test.stopTest();
		
		List<Sync_Queue__c> lstQueue = new List<Sync_Queue__c> ();
		lstQueue = [SELECT Id, Notes__c, Sync_Status__c FROM Sync_Queue__c];
		
		system.assertNotEquals(0, lstQueue.size());
	
		for(Sync_Queue__c objQueue : lstQueue) {
			
			system.assert(
				objQueue.Sync_Status__c.equals(CRMS_Constants.SYNC_QUEUE_STATUS_SUCCESS) || 
				objQueue.Sync_Status__c.equals(CRMS_Constants.SYNC_STATUS_STALE) || 
				objQueue.Sync_Status__c.equals(CRMS_Constants.SYNC_QUEUE_STATUS_PENDING)
			);
		} //End of for loop on every queue record
	}

}