src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DWH_Import__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DWH Import</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Select to add a new contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Guarantors__c.object
<CustomObject>
    <description>AMP Guarantors Custom Object</description>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Owner/Director/Guarantor</label>
    <nameField>
        <displayFormat>ODG-{000000}</displayFormat>
        <label>Owners/Directors/Guarantors</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Owners/Directors/Guarantors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DWH_Import__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DWH Import</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DWH_Import__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DWH Import</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ODG__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner/Director/Guarantor</label>
        <referenceTo>Guarantors__c</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Queued_Record_ID__c</fullName>
        <label>Queued Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Status__c</fullName>
        <label>Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sync Queue</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Sync Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRMS_ODGTriggerHandlerTest.cls
/**
	Test class for the ODG trigger handler class
	Author: Saket Joshi
	Version: 1.0
*/

@isTest
public with sharing class CRMS_ODGTriggerHandlerTest {

	//Method to test for DWH_Import__c = false on insert
	@isTest
	static void testFalseImport() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		RecordType contactType = [SELECT Id FROM RecordType WHERE Name = 'Person Hong Kong' LIMIT 1];
        Account account = new Account(RecordTypeId=contactType.Id);
        account.lastname='Account_PTMA';
        insert account;
        
		Opportunity objOpportunity = objUtil.initializeOpportunity(true);
		
		List<Guarantors__c> lstGuarantors = CRMS_Util.generateODGList(30, false, account.Id, objOpportunity.Id);
		
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		Test.startTest();
		insert lstGuarantors;
		Test.stopTest();
		
		List<Guarantors__c> lstGurantorNew = new List<Guarantors__c> ();
		lstGurantorNew = [SELECT DWH_Status__c, DWH_Last_Sync__c FROM Guarantors__c];
		
		system.assertNotEquals(0, lstGurantorNew.size());
	}
	
	//Method to test for DWH_Import__c = true on insert
	@isTest
	static void testTrueImport() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		RecordType contactType = [SELECT Id FROM RecordType WHERE Name = 'Person Hong Kong' LIMIT 1];
        Account account = new Account(RecordTypeId=contactType.Id);
        account.lastname='Account_PTMA';
        insert account;
        
		Opportunity objOpportunity = objUtil.initializeOpportunity(true);
		
		List<Guarantors__c> lstGuarantors = CRMS_Util.generateODGList(30, false, account.Id, objOpportunity.Id);
		
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		Test.startTest();
		
		for(Guarantors__c objGuarantor : lstGuarantors)
			objGuarantor.DWH_Status__c = CRMS_Constants.DWH_STATUS_SYNCED;
		
		insert lstGuarantors;
		Test.stopTest();
		
		List<Guarantors__c> lstGurantorNew = new List<Guarantors__c> ();
		lstGurantorNew = [SELECT DWH_Status__c, DWH_Last_Sync__c FROM Guarantors__c];
		
		system.assertNotEquals(0, lstGurantorNew.size());
	}

	//Method to test for DWH_Import = true on update
	@isTest
	static void testImportChangeFalseToTrue() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		RecordType contactType = [SELECT Id FROM RecordType WHERE Name = 'Person Hong Kong' LIMIT 1];
        Account account = new Account(RecordTypeId=contactType.Id);
        account.lastname='Account_PTMA';
        insert account;
        
		Opportunity objOpportunity = objUtil.initializeOpportunity(true);
		
		List<Guarantors__c> lstGuarantors = CRMS_Util.generateODGList(30, false, account.Id, objOpportunity.Id);
		for(Guarantors__c objGuarantor : lstGuarantors)
			objGuarantor.DWH_Status__c = CRMS_Constants.DWH_STATUS_QUEUED;
		insert lstGuarantors;
		
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		Test.startTest();
		for(Guarantors__c objGuarantor : lstGuarantors)
			objGuarantor.DWH_Status__c = CRMS_Constants.DWH_STATUS_SYNCED;
		
		update lstGuarantors;
		Test.stopTest();
		
		List<Guarantors__c> lstGurantorNew = new List<Guarantors__c> ();
		lstGurantorNew = [SELECT DWH_Status__c, DWH_Last_Sync__c FROM Guarantors__c];
		
		system.assertNotEquals(0, lstGurantorNew.size());
	}
	
	//Method to test for DWH_Import = false on update
	@isTest
	static void testImportChangeTrueToFalse() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		RecordType contactType = [SELECT Id FROM RecordType WHERE Name = 'Person Hong Kong' LIMIT 1];
        Account account = new Account(RecordTypeId=contactType.Id);
        account.lastname='Account_PTMA';
        insert account;
        
		Opportunity objOpportunity = objUtil.initializeOpportunity(true);
		
		List<Guarantors__c> lstGuarantors = CRMS_Util.generateODGList(30, false, account.Id, objOpportunity.Id);
		for(Guarantors__c objGuarantor : lstGuarantors)
			objGuarantor.DWH_Status__c = CRMS_Constants.DWH_STATUS_SYNCED;
		
		insert lstGuarantors;
		
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		Test.startTest();
		for(Guarantors__c objGuarantor : lstGuarantors)
			objGuarantor.DWH_Status__c = null;
		
		update lstGuarantors;
		Test.stopTest();
		
		List<Guarantors__c> lstGurantorNew = new List<Guarantors__c> ();
		lstGurantorNew = [SELECT DWH_Status__c, DWH_Last_Sync__c FROM Guarantors__c];
		
		system.assertNotEquals(0, lstGurantorNew.size());
	}
	
	//Method to test deletion of contact record
	@isTest
	static void testDeleteContact() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		RecordType contactType = [SELECT Id FROM RecordType WHERE Name = 'Person Hong Kong' LIMIT 1];
        Account account = new Account(RecordTypeId=contactType.Id);
        account.lastname='Account_PTMA';
        insert account;
		
        Opportunity objOpportunity = objUtil.initializeOpportunity(true);
		Set<Id> guarantorsIdSet = new Set<Id>();
		
		List<Guarantors__c> lstGuarantors = CRMS_Util.generateODGList(30, false, account.Id, objOpportunity.Id);
		for (Guarantors__c guarantor : lstGuarantors) {
		   guarantor.DWH_Status__c = CRMS_Constants.DWH_STATUS_QUEUED;
		}
		insert lstGuarantors;
		
		for (Guarantors__c guarantor : lstGuarantors) {
		    guarantorsIdSet.add(guarantor.Id);
		}
		
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		Test.startTest();
		delete lstGuarantors;
		Test.stopTest();
		
		List<Sync_Queue__c> lstSyncQueue = new List<Sync_Queue__c>();
		lstSyncQueue = [
		    SELECT Sync_Status__c
		         , Action__c
		         , Queued_Record_ID__c
		         , Notes__c 
		       FROM Sync_Queue__c 
		      WHERE Queued_Record_ID__c 
		        IN :guarantorsIdSet ];

		system.assertNotEquals(0, lstSyncQueue.size());
	}
	
	static testMethod void test_updateExistingSyncQueueRecord_BeforeDelete() {
        CRMS_Util objUtil = new CRMS_Util();
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        Test.startTest();
        //Query ‘”Sync Queue” for records matching the criteria of Lead = Lead, Sync Status is ‘Pending’.  If a record is found
        
        //If Sync Queue record meeting criteria is not found
        RecordType contactType = [SELECT Id FROM RecordType WHERE Name = 'Person Hong Kong' LIMIT 1];
        Account account = new Account(RecordTypeId=contactType.Id);
        account.lastname='Account_PTMA';
        insert account;
		Opportunity objOpportunity = objUtil.initializeOpportunity(true);
		Sync_Queue__c[] syncQueueList = new Sync_Queue__c[] {};
		Set<String> guarantorsIdSet = new Set<String>();
		
		List<Guarantors__c> lstGuarantors = CRMS_Util.generateODGList(30, false, account.Id, objOpportunity.Id);
		for (Guarantors__c guarantor : lstGuarantors) {
		    guarantor.DWH_Status__c = CRMS_Constants.DWH_STATUS_QUEUED;
		}
		insert lstGuarantors;
		for (Guarantors__c guarantor : lstGuarantors) {
		    String tempId = guarantor.Id;
		    guarantorsIdSet.add(tempId);
		    Sync_Queue__c syncQueue = new Sync_Queue__c();
            syncQueue.ODG__c = guarantor.Id;
            syncQueue.Sync_Status__c = CRMS_Util.SYNC_QUEUE_STATUS_PENDING;
            syncQueueList.add(syncQueue);
		}
        insert syncQueueList;
        delete lstGuarantors;
        Test.stopTest();
        system.assertEquals(syncQueueList[0].Sync_Status__c, CRMS_Util.SYNC_QUEUE_STATUS_PENDING);
    }
}