src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Select to add a new contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Management_Event__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ApprovedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Loan_Management_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Amount__c</fullName>
        <label>Event Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bounce Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waive Accummulated Fees</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Loan</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Loan Management Events</relationshipLabel>
        <relationshipName>Loan_Management_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Loan Management Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Management Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Additional_Information_Narrative__c</fullName>
        <label>Additional Information Narrative</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Disbursal_More_Info__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disbursal More Info</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Final_Decision__c</fullName>
        <label>Final Decision</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Repayment_Date__c</fullName>
        <label>Repayment Begins On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Principal Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Disbursed_Date__c</fullName>
        <label>To Be Disbursed On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loan_Disbursed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Loan Disbursed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReadyForFinanceEmailSent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ReadyForFinanceEmailSent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ready_for_Finance_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready for Finance Approval</label>
        <type>Checkbox</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Additional_Information_Narrative__c</fullName>
        <label>Additional Information Narrative</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Disbursed_Date__c</fullName>
        <label>Disbursed Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DWH_Data_Type__c</fullName>
        <label>DWH Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Product Association</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission/Incentive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Ledger</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Management_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Management Event</label>
        <referenceTo>Loan_Management_Event__c</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operation</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Queued_Record_ID__c</fullName>
        <label>Queued Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Status__c</fullName>
        <label>Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sync Queue</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Sync Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CRMS_OperationTriggerHandler.cls
/**
    Handler class for the Opearation trigger
    Author: CRM Superstars
    Version: 1.0
*/
public class CRMS_OperationTriggerHandler
{
    public static Boolean isTriggerCalled = false;    
    
    // method to set Operation status as Queued when updated on SF end
    public void setOperationDWHStatusQueued(List<Operation__c> lstOperation) {
        for (Operation__c operation : lstOperation) 
        {
            operation.DWH_Status__c = CRMS_Constants.DWH_STATUS_QUEUED;
        }
    }
    // method to set Operation status as Synced when successfully synced with DWH
    public void setOperationDWHStatusSynced(List<Operation__c> lstOperation){
        for (Operation__c operation : lstOperation) 
        {
            //operation.DWH_Status__c = CRMS_Constants.DWH_STATUS_SYNCED;
            operation.DWH_Last_Sync__c = Datetime.now();
        }
    }

    public void updateOpportunity(List<Operation__c> lstOperation, map<Id,Operation__c> mapOldOperations){
        map<ID,Opportunity> mapOpportunityToUpdate = new map<ID,Opportunity>(); 
        map<Id, Loan_Management_Event__c> LoanEventmap = new map<Id,Loan_Management_Event__c>();
              
        for(Operation__c objOper : lstOperation){           
            
            if((objOper.Loan_Disbursed__c && mapOldOperations.get(objOper.Id).Loan_Disbursed__c == false)){              
                	
            	mapOpportunityToUpdate.put(objOper.Id, new Opportunity(
                    Id = objOper.Opportunity__c,
                    Disbursed_Date__c = date.today()                    
                ));
                LoanEventmap.put(objOper.Id, new Loan_Management_Event__c(
                    Operation__c = objOper.Id,
                    Event_Date__c = objOper.Loan_Disbursed_Date__c,
                    Event_Type__c = 'Disbursal',
                    Effective_Date__c =  objOper.First_Repayment_Date__c,
                    Event_Amount__c =  objOper.Loan_Amount__c,
                    IsApproved__c = true,
                    ApprovedBy__c = userinfo.getuserId(),
                    Approval_Date__c =  DateTime.now()          
                ));                              
            }
            
            if(objOper.Final_Decision__c == 'Rejected' && mapOldOperations.get(objOper.Id).Final_Decision__c == null){
                mapOpportunityToUpdate.put(objOper.Id, new Opportunity(
                    Id = objOper.Opportunity__c,
                    StageName = 'Loan Withdrawn'
                ));
            }
        }
        if(LoanEventmap.size() > 0 && !LoanEventmap.isEmpty()){         
            Database.insert(LoanEventmap.values());
        }
        if(!mapOpportunityToUpdate.isEmpty() && mapOpportunityToUpdate.size() > 0){           
            update mapOpportunityToUpdate.values();
        }
    }
    
    public void CheckForAdditionalInformation(map<Id,Operation__c> mapNewOperations,map<Id,Operation__c> mapOldOperations){
        list<Task> AdditionalInfoTasks = new list<Task>();
        for(Operation__c Operation : mapNewOperations.values()){
            if(Operation.Disbursal_More_Info__c == true 
                && Operation.Additional_Information_Narrative__c != null
                && mapOldOperations.get(Operation.Id).Disbursal_More_Info__c != true){
                
                AdditionalInfoTasks.add( this.CreatTask(Operation,
                                'Additional information is required for disbursal of funds',
                                'Normal'));             
            }
            
            if(Operation.Additional_Information_Narrative__c != null
                && mapOldOperations.get(Operation.Id).Additional_Information_Narrative__c != null
                && Operation.Additional_Information_Narrative__c != mapOldOperations.get(Operation.Id).Additional_Information_Narrative__c){
                AdditionalInfoTasks.add( this.CreatTask(Operation,
                                'Additional information is not satisfactory for disbursal of funds',
                                'Normal'));
            }
        }
        if(AdditionalInfoTasks.size()>0 && !AdditionalInfoTasks.isEmpty()){
            Database.insert(AdditionalInfoTasks);
        }         
    
    }
    
    private Task CreatTask(Operation__c OperationObj,string Subject, string Priority){
        Task AdditionalInfoTask= new Task();        
        if(OperationObj != null){
            ID AssignedToUser;
             
            if(OperationObj.RecordtypeId == '012260000008Txc'){ //Operation UK
                AssignedToUser = '00526000000Q6R6'; //Opera UK-Agent 
            }else if(OperationObj.RecordtypeId == '012260000008Txh'){ //Operation HK
                AssignedToUser = '00526000000QTN2'; //Opera HK-Agent 
            }else if(OperationObj.RecordtypeId == '012260000008Txm'){ //Operation SG
                AssignedToUser = '00526000000Qide'; //Opera SG-Agent 
            }else AssignedToUser = OperationObj.OwnerId;
                        
            AdditionalInfoTask.WhatId = OperationObj.Id;
            AdditionalInfoTask.Status = 'Not Started';
            AdditionalInfoTask.OwnerId = AssignedToUser;
            AdditionalInfoTask.Subject = Subject;
            AdditionalInfoTask.Description = 'The following additional information is required: \n' + 
            OperationObj.Additional_Information_Narrative__c;
            AdditionalInfoTask.Priority = Priority;
            AdditionalInfoTask.ActivityDate = date.today();
        }
        return AdditionalInfoTask;        
    }

    // method to create/update Sync Queue records
    public void updateSyncQueueRecord(List<Operation__c> lstOperation){
        Map<Id,List<Sync_Queue__c>> operationIdToSynchQueListMap = new  Map<Id,List<Sync_Queue__c>>();
        Set<Id> operationIdSet = new Set<Id>();
        Sync_Queue__c[] synchQueueUpdateList = new Sync_Queue__c[]{};
        Sync_Queue__c[] synchQueueCreateList = new Sync_Queue__c[]{};
        
        for (Operation__c operation : lstOperation) {
            operationIdSet.add(operation.Id);
        }
        List<Sync_Queue__c> syncQueueList = [
            SELECT Operation__c
                 , Notes__c
                 , Action__c
                 , Queued_Record_ID__c
                 , Sync_Status__c
                 , DWH_Data_Type__c
               FROM Sync_Queue__c 
              WHERE Sync_Status__c = :CRMS_Constants.SYNC_QUEUE_STATUS_PENDING
                AND Operation__c IN :operationIdSet
         ];
         
        for (Sync_Queue__c syncQueue : syncQueueList) {
            if (operationIdToSynchQueListMap.containsKey(syncQueue.Operation__c) == true) {
                operationIdToSynchQueListMap.get(syncQueue.Operation__c).add(syncQueue);
            } else {
                operationIdToSynchQueListMap.put(syncQueue.Operation__c, new Sync_Queue__c[] {syncQueue});
            }
        }
        
        for (Operation__c operation : lstOperation) {
            Sync_Queue__c[] synchQueueList = operationIdToSynchQueListMap.get(operation.Id);
            system.debug('***** synchQueueList '+synchQueueList);
            if (synchQueueList != null && !synchQueueList.isEmpty()) {
                for (Sync_Queue__c synchQue : synchQueueList) {
                    if (synchQue.Action__c != CRMS_Constants.SYNC_ACTION_DELETE) {
                        synchQue.Sync_Status__c = CRMS_Constants.SYNC_STATUS_STALE;
                    }
                    String currentDateTime = Datetime.now().format() + CRMS_Constants.DWH_DELETE_TRIGGER;
                    synchQue.Action__c = CRMS_Constants.SYNC_ACTION_DELETE;
                    synchQue.Notes__c = currentDateTime;
                    synchQue.Queued_Record_ID__c = operation.Id;
                    synchQueueUpdateList.add(synchQue);
                }
            } 
            Sync_Queue__c syncQueue = new Sync_Queue__c();
            syncQueue.Queued_Record_ID__c = operation.Id;
            syncQueue.DWH_Data_Type__c = CRMS_Constants.DWH_DATA_TYPE_OPERATION;
            syncQueue.Action__c = CRMS_Constants.SYNC_ACTION_DELETE;
            syncQueue.Sync_Status__c = CRMS_Constants.SYNC_QUEUE_STATUS_PENDING;
            String currentDateTime = Datetime.now().format() + CRMS_Constants.SYNC_STATUS_OPERATION_DELETED;
            syncQueue.Notes__c = currentDateTime;
            synchQueueCreateList.add(syncQueue);
            
        }
        if (!synchQueueUpdateList.isEmpty()) {
            update synchQueueUpdateList;
             system.debug('***** synchQueueUpdateList '+synchQueueUpdateList);
        }
        if (!synchQueueCreateList.isEmpty()) {
            insert synchQueueCreateList;
            system.debug('***** synchQueueCreateList '+synchQueueCreateList);
        }
    }// end of updateSyncQueueRecord
    
    public void sendEmailToOpportunityTeam(List<Operation__c> lstOperation){
        Map<Id,Id> opportunityOperationMapForEmail = new Map<Id,Id>();
        for(Operation__c tempOp : lstOperation) {
            if(tempOp.Ready_for_Finance_Approval__c == true && tempOp.ReadyForFinanceEmailSent__c == false){
                opportunityOperationMapForEmail.put(tempOp.Opportunity__c,tempOp.Id);
                tempOp.ReadyForFinanceEmailSent__c = true;
            }
        }
        system.debug('Miro opportunityOperationMapForEmail:' + opportunityOperationMapForEmail);
        if(!opportunityOperationMapForEmail.isEmpty()){
            List<OpportunityTeamMember> oppsTeamMembersList = new List<OpportunityTeamMember>();
            oppsTeamMembersList = [Select OpportunityId,User.Email,User.FirstName,User.LastName, Name 
                                   FROM OpportunityTeamMember 
                                   Where OpportunityId IN :opportunityOperationMapForEmail.keySet() And TeamMemberRole = 'Finance'];
            
        system.debug('Miro oppsTeamMembersList:' + oppsTeamMembersList);
                List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
                EmailTemplate templateId = [Select id from EmailTemplate where name = 'Operation Ready For Finance'];
                Messaging.SingleEmailMessage mail;
                List<Contact> tempContactsList = new List<Contact>();
        system.debug('Miro templateId:' + templateId);
            for(OpportunityTeamMember teamMember : oppsTeamMembersList)       {     
                mail = new Messaging.SingleEmailMessage();
                Contact tempContact = new Contact(email = teamMember.User.email, firstName = teamMember.User.FirstName, lastName = teamMember.User.LastName);
                insert tempContact;
                tempContactsList.add(tempContact);
                
                mail.setTemplateID(templateId.Id); 
                mail.setTargetObjectId(tempContact.id);
                mail.setWhatId (opportunityOperationMapForEmail.get(teamMember.OpportunityId));
                mail.setSaveAsActivity(false);
                mail.setUseSignature(false);

                mail.setToAddresses(new String[]{teamMember.User.Email});
    
                allmsg.add(mail);
            }
                system.debug('Miro Emails - >>'+JSON.serialize(allmsg));
                Messaging.SendEmailResult[] res = Messaging.sendEmail(allmsg,false);
            delete tempContactsList;
            for(Messaging.SendEmailResult tempRes : res){
                system.debug('Miro res Emails:' + tempRes.getErrors());}
        }
    }
   
}// end of class