src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Allocated_Internal_Sales_Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Allocated Internal Sales Representative</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Select to add a new contact</description>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Select to add a new partner</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>Annual_Calculation__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Annual Calculation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approved_Loan_Amount__c</fullName>
        <label>Approved Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approved_Loan_Term__c</fullName>
        <label>Approved Loan Term</label>
        <picklist>
            <picklistValues>
                <fullName>03 (090 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 (120 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 (150 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 (180 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 (210 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 (240 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 (270 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 (365 days)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>IF(contains(RecordType.DeveloperName,&apos;Philippines&apos;),&apos;PP&apos;,
IF(contains(RecordType.DeveloperName,&apos;Hong&apos;),&apos;HK&apos;,
IF(contains(RecordType.DeveloperName,&apos;Singapore&apos;),&apos;SG&apos;,&apos;UK&apos;)))</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <formula>TEXT(Opportunity__r.Loan_Purpose__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Loan Purpose</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_Interest_Approved__c</fullName>
        <label>Annual Interest (Approved)</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Interest_Requested__c</fullName>
        <defaultValue>IF(OR($RecordType.DeveloperName == &apos;Credit_Assessment_UK&apos;,$RecordType.DeveloperName == &apos;Credit_Assessment_Completed&apos;) ,  $Setup.IR__c.Annual_UK__c ,  $Setup.IR__c.Annual__c )</defaultValue>
        <label>Annual Interest (Requested)</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Interest__c</fullName>
        <defaultValue>IF(OR($RecordType.DeveloperName == &apos;Credit_Assessment_UK&apos;,$RecordType.DeveloperName == &apos;Credit_Assessment_Completed&apos;) ,  $Setup.IR__c.Annual_UK__c ,  $Setup.IR__c.Annual__c )</defaultValue>
        <label>Annual Interest</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Offer_Amount__c</fullName>
        <label>Offer Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_Loan_Term__c</fullName>
        <formula>TEXT( Opportunity__r.Requested_Loan_Term__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Requested Loan Term</label>
        <type>Text</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <recordTypes>
        <fullName>Credit_Assessment_Completed</fullName>
        <active>true</active>
        <description>Completed Credit Assessment for UK</description>
        <label>Credit Assessment Completed - UK</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Date_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom setting with all date range values</description>
    <fields>
        <fullName>Disbursal_Range__c</fullName>
        <defaultValue>15</defaultValue>
        <description>No of days within which the customer can withdraw loan after disbursal</description>
        <inlineHelpText>Enter no of days within which the customer can withdraw loan after loan disbursal</inlineHelpText>
        <label>Disbursal Range</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Date Settings</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hong Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philippines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>UK</fullName>
        <active>true</active>
        <businessProcess>Lead Process</businessProcess>
        <description>Lead belongs to UK</description>
        <label>UK</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Country__c</fullName>
        <formula>IF(contains(RecordType.DeveloperName,&apos;UK&apos;),&apos;UK&apos;, 
IF(contains(RecordType.DeveloperName,&apos;Hong&apos;),&apos;HK&apos;, 
IF(contains(RecordType.DeveloperName,&apos;Singapore&apos;),&apos;SG&apos;,&apos;PP&apos;)))</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_Interest__c</fullName>
        <defaultValue>IF($RecordType.DeveloperName == &apos;Operation_UK&apos;,  $Setup.IR__c.Annual_UK__c , $Setup.IR__c.Annual__c)</defaultValue>
        <label>Annual Interest</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Annual_Calculation__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Annual Calculation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Application_Form_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox will be automatically checked when all necessary information on the application form has been completed.</description>
        <inlineHelpText>This checkbox will be automatically checked when all necessary information on the application form has been completed</inlineHelpText>
        <label>Application Form Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ave_Monthly_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Ave Monthly Sales</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_Card_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Average Monthly Card Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Signed_Date__c</fullName>
        <label>Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Hong Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philippines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Documents_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checkbox updated automatically by Kofax</inlineHelpText>
        <label>Documents Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Documents_Received_Kofax__c</fullName>
        <label>Documents Received</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Introducer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Introducer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <label>Loan Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refurbishment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expansion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinancing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Monthly_Interest__c</fullName>
        <defaultValue>IF(OR($RecordType.DeveloperName == &apos;Renewal_UK&apos;,
$RecordType.DeveloperName == &apos;Outcome_UK&apos;,
$RecordType.DeveloperName == &apos;Closing_UK&apos;, 
$RecordType.DeveloperName == &apos;Application_UK&apos;,
$RecordType.DeveloperName == &apos;Assessment_UK&apos;,
$RecordType.DeveloperName == &apos;Disbursement_UK&apos;) , $Setup.IR__c.Annual_UK__c , $Setup.IR__c.Annual__c )</defaultValue>
        <label>Annual Interest</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Rental__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Monthly Rental</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Requested_Loan_Term__c</fullName>
        <inlineHelpText>Requested Loan Term in Months (Days)</inlineHelpText>
        <label>Requested Loan Term</label>
        <picklist>
            <picklistValues>
                <fullName>03 (090 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 (120 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 (150 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 (180 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 (210 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 (240 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 (270 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 (365 days)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Required_Documents_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Updated automatically by Kofax</inlineHelpText>
        <label>Required Documents Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Signed_Application_Form_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Signed Application Form Received</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Outcome_UK</fullName>
        <active>true</active>
        <businessProcess>Outcome Process</businessProcess>
        <description>This record type is for all UK opportunities that are at the outcome stage.</description>
        <label>Outcome UK</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Assessment</label>
        <referenceTo>Credit_Assessment__c</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operation</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sync Queue</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Sync Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRMS_OpportunityTriggerHandlerTest.cls
@isTest
private class CRMS_OpportunityTriggerHandlerTest 
{
    static testMethod void test_setOpportunityCloneOpportunity() {
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        
        
        Account objAcc = new Account();
        objAcc.Name = 'testAcc';
        insert objAcc;
        
        Opportunity objOpp = new Opportunity();
        objOpp.Name = 'testOpp';
        objOpp.AccountId = objAcc.Id;
        objOpp.StageName = 'In Progress';//'Qualification';
        objOpp.CloseDate = date.today();
        objOpp.Country__c = 'UK';
        objOpp.Contract_End_Date__c = date.today();
        objOpp.Contract_Signed__c = false;
        insert objOpp;

        objOpp.StageName = 'Accepted';
        objOpp.Contract_End_Date__c = date.today();
        update objOpp;
        list<Opportunity> lstOpp = [select id, Name, Contract_End_Date__c, StageName, AccountId 
                                    From Opportunity 
                                    where AccountId =: objAcc.Id];
        
        system.assertEquals(1,lstOpp.size());
    }
  
    static testMethod void testOpportunityTriggerHandler() 
    {
        list<User> lstUser1 = [SELECT Id, Name FROM User where Name Like '%Partner%'];
        
        list<Profile> lstProfile = [Select p.UserLicenseId, p.Name, p.Id From Profile p 
                                    where p.Name Like '%Partner%' limit 1];
        list<User> lstUser  = [Select u.ProfileId, u.IsActive, u.Id From User u 
                              where u.isActive = true limit 1];
        
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        
        Test.startTest();
        
        Account objAcc = new Account();
        objAcc.Name = 'testAcc';
        insert objAcc;
                              
        Contact objContact = new Contact();
        objContact.lastName = 'first Contact';
        objContact.phone = '8983794213';
        objcontact.Email = 'test@crmsuperstars.com';
        objContact.AccountId = objAcc.Id;
        objContact.Allocated_Internal_Sales_Representative__c = lstuser[0].Id;
        insert objContact ;
                              
        User objUser = new User(
                             Email='standarduser123@test.com', 
                             EmailEncodingKey='UTF-8', 
                             LastName='Testing', 
                             LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', 
                             ProfileId = lstProfile[0].Id,
                             TimeZoneSidKey='America/Los_Angeles', 
                             UserName='standarduser123@test.com',
                             CommunityNickname = 'testUser123',
                             ContactId = objContact.Id,
                             Alias = 't1');
        insert objUser;
        
        Opportunity objOpp = new Opportunity();
        //System.runAs(objUser){
        objOpp.Name = 'testOpp';
        objOpp.AccountId = objAcc.Id;
        objOpp.StageName = 'Qualification';
        objOpp.CloseDate = date.today();
        objOpp.Introducer__c = objUser.Id;
        objOpp.Country__c = 'UK';
        insert objOpp;
        //}
        OpportunityTeamMember objOppTeamMember = new OpportunityTeamMember();
        objOppTeamMember.OpportunityId = objOpp.Id;
        objOppTeamMember.UserId = objUser.Id;
        objOppTeamMember.TeamMemberRole = 'Sales Rep';
        insert objOppTeamMember;
        
        Statics.inFutureContext = true;
        
        Account objAcc1 = new Account();
        objAcc1.Name = 'testAcc1';
        insert objAcc1;
                              
        Contact objContact1 = new Contact();
        objContact1.lastName = 'first Contact1';
        objContact1.phone = '898379423';
        objContact1.Email = 'test@crmsuperstar.com';
        objContact1.AccountId = objAcc1.Id;
        objContact1.Allocated_Internal_Sales_Representative__c = lstuser1[0].Id;
        insert objContact1 ;
        
        User objUser1 = new User(
                             Email='standarduse123@test.com', 
                             EmailEncodingKey='UTF-8', 
                             LastName='Testing', 
                             LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', 
                             ProfileId = lstProfile[0].Id,
                             TimeZoneSidKey='America/Los_Angeles', 
                             UserName='standarduser113@test.com',
                             CommunityNickname = 'testUser111',
                             ContactId = objContact1.Id,
                             Alias = 't1');
        insert objUser1;
        objOpp.Introducer__c = objUser1.Id;
        objOpp.StageName = 'Contract Stage';
        update objOpp;
        Test.stopTest();
    }
    
    static testMethod void test_setOpportunityCreditAssessmentCreation() {
        CRMS_Util util = new CRMS_Util();
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        
        Test.startTest();
        
        Account Acc = new Account();
        Acc.Name  = 'Test Credit Assesment Creation';
        insert Acc;
        
        Contact objContact = new Contact();
        objContact.lastName = 'first Contact1';
        objContact.phone = '898379423';
        objContact.Email = 'test@crmsuperstar.com';
        objContact.AccountId = Acc.Id;
        insert objContact ;
        
        list<Profile> lstProfile1 = [Select p.UserLicenseId, p.Name, p.Id From Profile p where p.Name = 'System Administrator'limit 1];
        User objUser1 = new User(
                             Email='standarduse123@test.com', 
                             EmailEncodingKey='UTF-8', 
                             LastName='Testing', 
                             LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', 
                             ProfileId = lstProfile1[0].Id,
                             TimeZoneSidKey='America/Los_Angeles', 
                             UserName='standarduser123@test.com',
                             CommunityNickname = 'testUser143',
                             Alias = 't1');
        insert objUser1;
        
        Opportunity objP = new Opportunity();
        
        //System.runAS(objUser1){
        objP.AccountId = Acc.Id;
        objP.Name = 'Test Operation Creation';
        objP.CloseDate  = date.today().addDays(30);
        objP.StageName = 'Accepted';
        objP.Loan_Purpose__c = 'Inventory';
        objP.Requested_Loan_Term__c = '03 (090 days)';
        objP.Amount = 1500;
        objP.Monthly_Rental__c = 100;
        objP.Ave_Monthly_Sales__c = 15000;
        objP.Average_Monthly_Card_Sales__c = 15000;
        objP.Contract_Signed__c = false;
        objP.Introducer__c = objUser1.Id;
        insert objP;
        //}
        
        User objUser = new User(
                             Email='standarduser123@test.com', 
                             EmailEncodingKey='UTF-8', 
                             LastName='Test', 
                             LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', 
                             ProfileId = lstProfile1[0].Id,
                             TimeZoneSidKey='America/Los_Angeles', 
                             UserName='standarduser113@test.com',
                             CommunityNickname = 'testUser113',
                             
                             Alias = 't1');
        insert objUser;
        
        CRMS_OpportunityTriggerHandler.blnUpdate = false;  
        objP.Signed_Application_Form_Received__c = true;
        objP.Documents_Received_Kofax__c = 'Test';
        objP.Application_Form_Completed__c = true;
        objP.Required_Documents_Received__c = true;
        objP.Documents_Processed__c = true;
        objP.Contract_End_Date__c = date.today();
        objP.StageName = '(Won) Disbursed';
        objP.Contract_Signed__c = true;
        objP.Introducer__c = objUser.Id;
        update objP;
        
        Test.stopTest();
        list<Credit_Assessment__c> lstCredit = [select Id,CurrencyIsoCode from Credit_Assessment__c where Opportunity__c = :objP.Id];
        system.assertEquals(1,lstCredit.size());
    }
    
    static testMethod void test_setOpportunityOperationCreation() {
        CRMS_Util util = new CRMS_Util();
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        RecordType oppRecordType = [Select r.Id, r.SobjectType ,r.DeveloperName
                                        From RecordType r 
                                        where r.SobjectType = 'Opportunity' 
                                        and r.DeveloperName = 'Outcome_UK'];
                                        
                                        list<Profile> lstProfile1 = [Select p.UserLicenseId, p.Name, p.Id From Profile p where p.Name = 'System Administrator'limit 1];
        User objUser1 = new User(
                             Email='standarduse123@test.com', 
                             EmailEncodingKey='UTF-8', 
                             LastName='Testing', 
                             LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', 
                             ProfileId = lstProfile1[0].Id,
                             TimeZoneSidKey='America/Los_Angeles', 
                             UserName='credituser123@test.com',
                             CommunityNickname = 'testUser143',
                             Alias = 't1');
        insert objUser1;
        Test.startTest();
        
        Opportunity objOpportunity = new Opportunity(RecordTypeId = oppRecordType.Id);
        objOpportunity.Name = 'Test Operations Creation';
        objOpportunity.CloseDate  = date.today().adddays(30);
        objOpportunity.StageName = 'Assessment In Progress';
        objOpportunity.Loan_Purpose__c = 'Inventory';
        objOpportunity.Average_Monthly_Card_Sales__c = 10000;
        objOpportunity.Monthly_Rental__c = 200;
        objOpportunity.Amount = 10000;
        objOpportunity.Monthly_Interest__c = 0.2;
        objOpportunity.Requested_Loan_Term__c = '06 (180 days)';
        objOpportunity.Contract_Signed__c = false;
        insert objOpportunity;
        
        List<RecordType> caRecordType = [Select r.Id, r.SobjectType ,r.DeveloperName
                                        From RecordType r 
                                        where r.SobjectType = 'Credit_Assessment__c' 
                                        and DeveloperName = 'Credit_Assessment_Completed'];
        
        Credit_Assessment__c objCredit = new Credit_Assessment__c(RecordTypeId = caRecordType[0].Id);
        objCredit.OwnerId = objUser1.Id;
        objCredit.Opportunity__c = objOpportunity.Id;
        //objCredit.CurrencyIsoCode = objOpportunity.CurrencyIsoCode;
        objCredit.Annual_Calculation__c = objOpportunity.Annual_Calculation__c;
        objCredit.Approved_Loan_Amount__c = 10000;
        objCredit.Monthly_Interest_Approved__c = 0.2;
        objCredit.Annual_Calculation__c = true;
        objCredit.Offer_Amount__c = 12000;
        objCredit.Approved_Loan_Term__c = '06 (180 days)';
        objCredit.Monthly_Interest__c = 0.2;
        objCredit.Monthly_Interest_Requested__c = objOpportunity.Monthly_Interest__c;
        insert objCredit;
        
        CRMS_OpportunityTriggerHandler.blnUpdate = false;
        objOpportunity.StageName = 'Application Revised';
        objOpportunity.Amount = 10500;
        update objOpportunity;
        
        CRMS_OpportunityTriggerHandler.blnUpdate = false;
        objOpportunity.Contract_Signed__c = true;
        objOpportunity.StageName = '(Won) Signed';
        objOpportunity.Contract_Signed_Date__c = date.today().addDays(30);
        objOpportunity.Contract_End_Date__c = date.newInstance(2016, 06, 01);
        objOpportunity.Signed_Application_Form_Received__c = true;
        update objOpportunity;
        Test.stopTest();
        list<Operation__c> lstOperation = [Select o.Opportunity__c, o.Id From Operation__c o where o.Opportunity__c =: objOpportunity.Id];
        system.assertEquals(1,lstOperation.size());
    }
    
    static testMethod void test_setOpportunity() {
        CRMS_Util util = new CRMS_Util();
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        RecordType oppRecordType = [Select r.Id, r.SobjectType ,r.DeveloperName
                                        From RecordType r 
                                        where r.SobjectType = 'Opportunity' 
                                        and r.DeveloperName = 'Outcome_UK'];
                                        
        list<Profile> lstProfile1 = [Select p.UserLicenseId, p.Name, p.Id From Profile p where p.Name = 'System Administrator'limit 1];
        User objUser2 = new User(
                             Email='standarduse123@test.com', 
                             EmailEncodingKey='UTF-8', 
                             LastName='Testing', 
                             LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', 
                             ProfileId = lstProfile1[0].Id,
                             TimeZoneSidKey='America/Los_Angeles', 
                             UserName='credituser123@test.com',
                             CommunityNickname = 'testUser143',
                             Alias = 't1');
        insert objUser2;
        Test.startTest();
        
        Opportunity objOpportunity = new Opportunity(RecordTypeId = oppRecordType.Id);
        objOpportunity.Name = 'Test Opportunity';
        objOpportunity.CloseDate  = date.today().adddays(30);
        objOpportunity.StageName = 'Loan Withdrawn';
        objOpportunity.Loan_Purpose__c = 'Inventory';
        objOpportunity.Average_Monthly_Card_Sales__c = 10000;
        objOpportunity.Monthly_Rental__c = 200;
        objOpportunity.Amount = 20000;
        objOpportunity.Monthly_Interest__c = 0.2;
        objOpportunity.Requested_Loan_Term__c = '06 (180 days)';
        objOpportunity.Contract_Signed__c = false;
        insert objOpportunity;
        
        Date_Setting__c dtCustom = new Date_Setting__c();
        dtCustom.Name = 'Test';
        dtCustom.Disbursal_Range__c = 3;
        dtCustom.Batch_Ownership_Change__c = 4;
        insert dtCustom;
        
        Operation__c operationobj = new Operation__c();
        operationobj.Loan_Disbursed__c = true;
        operationobj.Loan_Disbursed_Date__c = date.today().adddays(10);
        operationobj.Opportunity__c = objOpportunity.Id;
        insert operationobj;
        
    }
    
    
    static testMethod void test_setOpportunityDWHStatusSynced() {
        CRMS_Util util = new CRMS_Util();
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        
        Test.startTest();
        
        Opportunity opportunity = util.initializeOpportunity(false);
        opportunity.DWH_Status__c = CRMS_Util.DWH_STATUS_SYNCED;
        insert opportunity;
        Test.stopTest();
        
        List<Opportunity> testOpportunityList = [select DWH_Status__c,DWH_Last_Sync__c from Opportunity where id = :opportunity.Id];
        //system.assertNotEquals(null, testOpportunityList[0].DWH_Last_Sync__c);
    }
    
    static testMethod void test_setOpportunityDWHStatusQueued() {
        CRMS_Util util = new CRMS_Util();
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        
        Test.startTest();
        Opportunity opportunity = util.initializeOpportunity(false);
        insert opportunity;
        
        Test.stopTest();
        List<Opportunity> testOpportunityList = [select DWH_Status__c from Opportunity where id = :opportunity.Id];
    }
    
    
    /*
    // Do not uncomment
    static testMethod void test_createSyncQueueAfterOpportunityInsert() {
        CRMS_Util util = new CRMS_Util();
        
                                
        Opportunity opportunity = util.initializeOpportunity(false);
        opportunity.DWH_Import__c = false;
        insert opportunity;
        
        List<Sync_Queue__c> syncQueList = [SELECT Sync_Status__c FROM Sync_Queue__c WHERE Opportunity__c = :opportunity.Id];
        //system.assertEquals(1,syncQueList.size());
        //system.assertEquals(CRMS_Util.SYNC_QUEUE_STATUS_PENDING,syncQueList[0].Sync_Status__c);
    }
    
    static testMethod void test_createSyncQueueAfterOpportunityUpdate() {
        CRMS_Util util = new CRMS_Util();
        
                                
        Opportunity opportunity = util.initializeOpportunity(false);
        opportunity.DWH_Import__c = true;
        insert opportunity;
        
        List<Opportunity> opportunityList = [SELECT DWH_Import__c,DWH_Status__c FROM Opportunity WHERE Id = :opportunity.Id];
        opportunityList[0].DWH_Import__c = false;
        opportunityList[0].DWH_Status__c = CRMS_Util.DWH_STATUS_QUEUED;
        update opportunityList;
        
        List<Sync_Queue__c> syncQueList = [SELECT Sync_Status__c FROM Sync_Queue__c WHERE Opportunity__c = :opportunity.Id];
        //system.assertEquals(1,syncQueList.size());
        //system.assertEquals(CRMS_Util.SYNC_QUEUE_STATUS_PENDING,syncQueList[0].Sync_Status__c);
    }*/
    
    
    static testMethod void test_createSyncQueueRecord_BeforeDelete() {
        CRMS_Util util = new CRMS_Util();
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        
        Test.startTest();
        
        //If Sync Queue record meeting criteria is not found
        Opportunity oppObj = util.initializeOpportunity(false);
        oppObj.DWH_Import__c = false;
        insert oppObj;
        
        String opportunityId = oppObj.Id;
        List<Sync_Queue__c> syncQueList1 =[SELECT Id FROM Sync_Queue__c WHERE Opportunity__c = :opportunityId];
        delete syncQueList1;
        delete oppObj;
        
        List<Sync_Queue__c> syncQueListTest1 =[
            SELECT Opportunity__c
                 , Id
                 , Notes__c
                 , Action__c
                 , Queued_Record_ID__c
                 , Sync_Status__c
                 , DWH_Data_Type__c
               FROM Sync_Queue__c 
              WHERE Queued_Record_ID__c = :opportunityId
        ];
        
        Test.stopTest();
        //system.assertEquals(CRMS_Util.DWH_DATA_TYPE_OPPORTUNITY,syncQueListTest1[0].DWH_Data_Type__c);
        //system.assertEquals(opportunityId, syncQueListTest1[0].Queued_Record_ID__c);
        //system.assertEquals(CRMS_Util.SYNC_STATUS_DELETE, syncQueListTest1[0].Action__c);
        //system.assertEquals(CRMS_Util.SYNC_QUEUE_STATUS_PENDING, syncQueListTest1[0].Sync_Status__c);
        String syncQueueNotes1 = syncQueListTest1[0].Notes__c;
        //system.assert(syncQueueNotes1.contains(CRMS_Util.SYNC_STATUS_OPPORTUNITY_DELETED));
    }
    
    static testMethod void test_updateSyncQueueRecord_BeforeDelete() {
        CRMS_Util util = new CRMS_Util();
        //Query ??Sync Queue? for records matching the criteria of Lead = Lead, Sync Status is ?Pending?.  If a record if found
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        
        Test.startTest();
        //If Sync Queue record meeting criteria is not found
        Opportunity opprtunity = util.initializeOpportunity(false);
        opprtunity.DWH_Status__c = CRMS_Util.DWH_STATUS_QUEUED;
        insert opprtunity;
        
        Sync_Queue__c syncQueue = new Sync_Queue__c();
        syncQueue.Opportunity__c = opprtunity.Id;
        syncQueue.Sync_Status__c = CRMS_Util.SYNC_QUEUE_STATUS_PENDING;
        insert syncQueue;
        String opprtunityId = opprtunity.Id;
       
        delete opprtunity;
        
        List<Sync_Queue__c> syncQueListTest1 =[
            SELECT Credit_Assessment__c
                 , Id
                 , Notes__c
                 , Action__c
                 , Queued_Record_ID__c
                 , Sync_Status__c
                 , DWH_Data_Type__c
               FROM Sync_Queue__c 
              WHERE Queued_Record_ID__c = :opprtunityId
        ];
        
        Test.stopTest();
       //system.assertEquals(CRMS_Util.SYNC_STATUS_STALE, syncQueListTest1[0].Sync_Status__c);
        String syncQueueNotes1 = syncQueListTest1[0].Notes__c;
        //system.assert(syncQueueNotes1.contains(CRMS_Util.DWH_DELETE_TRIGGER));
    }
}