src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DWH_Import__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DWH Import</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Select to add a new contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Assessment</label>
        <referenceTo>Credit_Assessment__c</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DWH_Data_Type__c</fullName>
        <label>DWH Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Product Association</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission/Incentive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Ledger</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Queued_Record_ID__c</fullName>
        <label>Queued Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Status__c</fullName>
        <label>Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sync Queue</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Sync Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRMS_ContactTriggerHandlerTest.cls
/**
	Test class for the Contact trigger handler class
	Author: Saket Joshi
	Version: 1.0
*/

@isTest
public with sharing class CRMS_ContactTriggerHandlerTest {

	//Method to test for DWH_Import__c = false on insert
	@isTest
	static void testFalseImport() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		
		Account objAccount = objUtil.initializeAccount(true); 
		List<Contact> lstContact = CRMS_Util.generateContactList(30, false, objAccount.Id);
		
		Test.startTest();
		insert lstContact;
		Test.stopTest();
		
		List<Contact> lstContactNew = new List<Contact> ();
		lstContactNew = [SELECT DWH_Status__c, DWH_Last_Sync__c FROM Contact];

		for(Contact contact : lstContactNew)
			system.assertNotEquals(null, contact.DWH_Status__c);
	}
	
	//Method to test for DWH_Import__c = true on insert
	@isTest
	static void testTrueImport() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		
		Account objAccount = objUtil.initializeAccount(true);
		List<Contact> lstContact = CRMS_Util.generateContactList(30, false, objAccount.Id);
		
		Test.startTest();
		
		for(Contact objContact : lstContact)
			objContact.DWH_Status__c = CRMS_Constants.DWH_STATUS_SYNCED;
		insert lstContact;
		Test.stopTest();
		
		List<Contact> lstContactNew = new List<Contact> ();
		lstContactNew = [SELECT DWH_Status__c, DWH_Last_Sync__c FROM Contact];
		
		system.assertNotEquals(0, lstContactNew.size());
		for(Contact objContact : lstContactNew)
			system.assertNotEquals(null, objContact.DWH_Last_Sync__c);
	}

	//Method to test for DWH_Import = true on update
	@isTest
	static void testImportChangeFalseToTrue() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		
		Account objAccount = objUtil.initializeAccount(true);
		List<Contact> lstContact = CRMS_Util.generateContactList(30, false, objAccount.Id);
		insert lstContact;
		
		Test.startTest();
		for(Contact objContact : lstContact)
			objContact.DWH_Status__c = CRMS_Constants.DWH_STATUS_SYNCED;
		
		update lstContact;
		Test.stopTest();
		
		List<Contact> lstContactNew = new List<Contact> ();
		lstContactNew = [SELECT DWH_Status__c, DWH_Last_Sync__c FROM Contact];
		
		system.assertNotEquals(0, lstContactNew.size());
		for(Contact objContact : lstContactNew)
			system.assertNotEquals(null, objContact.DWH_Last_Sync__c);
	}
	
	//Method to test for DWH_Import = false on update
	@isTest
	static void testImportChangeTrueToFalse() {
		CRMS_Util objUtil = new CRMS_Util();
		CRMS_Util.generateEndpoints();
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
		
		Account objAccount = objUtil.initializeAccount(true);
		List<Contact> lstContact = CRMS_Util.generateContactList(30, false, objAccount.Id);
		for(Contact objContact : lstContact)
			objContact.DWH_Status__c = CRMS_Constants.DWH_STATUS_SYNCED;
		
		insert lstContact;
		
		Test.startTest();
		for(Contact objContact : lstContact)
			objContact.DWH_Status__c = null;
		
		update lstContact;
		Test.stopTest();
		
		List<Contact> lstContactNew = new List<Contact> ();
		lstContactNew = [SELECT DWH_Status__c, DWH_Last_Sync__c FROM Contact];
		
		system.assertNotEquals(0, lstContactNew.size());
		for(Contact objContact : lstContactNew)
			system.assertNotEquals(null, objContact.DWH_Status__c);
	}
	
	//Method to test deletion of contact record
	/*@isTest
	static void testDeleteContact() {
		CRMS_Util objUtil = new CRMS_Util();
		
		Account objAccount = objUtil.initializeAccount(true);
		List<Contact> lstContact = CRMS_Util.generateContactList(30, false, objAccount.Id);
		insert lstContact;
		
		Set<Id> setContactId = new Set<Id> ();
		for(Contact objContact : lstContact)
			setContactId.add(objContact.Id);
		
		Test.startTest();
		delete lstContact;
		Test.stopTest();
		
		List<Sync_Queue__c> lstSyncQueue = new List<Sync_Queue__c>();
		lstSyncQueue = [SELECT DWH_Data_Type__c, Sync_Status__c, Action__c FROM Sync_Queue__c WHERE Contact__c = null];

		//system.assertNotEquals(0, lstSyncQueue.size());
		for(Sync_Queue__c objQueue : lstSyncQueue)
			//system.assertEquals(CRMS_Constants.SYNC_STATUS_STALE, objQueue.Sync_Status__c);
	}*/
	
	static testMethod void test_createSyncQueueRecord_BeforeDelete() {
        CRMS_Util util = new CRMS_Util();
        CRMS_Util.generateEndpoints();
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        
        Account objAccount = util.initializeAccount(true);
        Contact[] contactList = CRMS_Util.generateContactList(1, false, objAccount.Id);
        Contact contact = contactList.get(0);
        contact.DWH_Status__c = CRMS_Util.DWH_STATUS_QUEUED;
        contact.Salutation = 'Mr.';
        insert contact;
        
        String contactId = contact.Id;
        delete contact;
        
        List<Sync_Queue__c> syncQueListTest1 =[
            SELECT Account__c
                 , Id
                 , Notes__c
                 , Action__c
                 , Queued_Record_ID__c
                 , Sync_Status__c
                 , DWH_Data_Type__c
               FROM Sync_Queue__c 
              WHERE Queued_Record_ID__c = :contactId
        ];
        
        system.assertEquals(CRMS_Util.DWH_DATA_TYPE_CONTACT,syncQueListTest1[0].DWH_Data_Type__c);
        
    }
	
	@isTest
	static void test_updateExistingSyncQueueRecord_BeforeDelete() {
        CRMS_Util util = new CRMS_Util();
        CRMS_Util.generateEndpoints();
		Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        
        Account objAccount = util.initializeAccount(true);
        Contact[] contactList = CRMS_Util.generateContactList(1, false, objAccount.Id);
        Contact contact = contactList.get(0);
        contact.DWH_Status__c = CRMS_Util.DWH_STATUS_QUEUED;
        contact.Salutation = 'Ms.';
        insert contact;
        
        Sync_Queue__c syncQueue = new Sync_Queue__c();
        syncQueue.Contact__c = contact.Id;
        syncQueue.Sync_Status__c = CRMS_Util.SYNC_QUEUE_STATUS_PENDING;
        insert syncQueue;
        String contactId = contact.Id;
       
        delete contact;
        
        List<Sync_Queue__c> syncQueListTest1 =[
            SELECT Credit_Assessment__c
                 , Id
                 , Notes__c
                 , Action__c
                 , Queued_Record_ID__c
                 , Sync_Status__c
                 , DWH_Data_Type__c
               FROM Sync_Queue__c 
              WHERE Queued_Record_ID__c = :contactId
        ];
        
        system.assertEquals(CRMS_Util.SYNC_STATUS_DELETE, syncQueListTest1[0].Action__c);
        system.assertEquals(CRMS_Util.SYNC_STATUS_STALE, syncQueListTest1[0].Sync_Status__c);
        
    }
}