src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>AMP_Credit_Score__c</fullName>
        <label>AMP Credit Score</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FOC__c</fullName>
        <formula>TEXT(Opportunity__r.FOC__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Frequency of Collection</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Paid_In_M1__c</fullName>
        <label>Paid In M1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Paid_In_M2__c</fullName>
        <label>Paid In M2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Paid_In_M3__c</fullName>
        <label>Paid In M3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Paid_Out_M1__c</fullName>
        <label>Paid Out M1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Paid_Out_M2__c</fullName>
        <label>Paid Out M2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Paid_Out_M3__c</fullName>
        <label>Paid Out M3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Repayable_Approved__c</fullName>
        <formula>Approved_Loan_Amount__c + Interest_Amount_Approved__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount Repayable (Approved)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Weekly_Amount_Repayable_Approved__c</fullName>
        <label>Total Weekly Amount Repayable (Approved)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRMS_CreditAssessmentController.cls
/**
    Controller for the Lead Flow, currently not being used
    Author: Vivian
    Version: 1.0
*/
public class CRMS_CreditAssessmentController{
    public Credit_Assessment__c objCA {get;set;}
    //public Decimal repaymentAmount{get;set;}
    public CRMS_CreditAssessmentController (ApexPages.StandardController controller){
        creditAssessmentDetails(controller.getId());
    }

    public void creditAssessmentDetails(Id objCA_Id){
        //repaymentAmount = 0.0;
        list<Credit_Assessment__c> lstCA = [select Id, Total_Weekly_Amount_Repayable_Approved__c,
                                           Total_Amount_Repayable_Approved__c,AMP_Credit_Score__c,
                                            FOC__c from Credit_Assessment__c
                                            where Id =: objCA_Id];

        if(lstCA != null && !lstCA.isEmpty()){
            objCA = new Credit_Assessment__c(Id = lstCA[0].Id, AMP_Credit_Score__c = lstCA[0].AMP_Credit_Score__c);
            if(lstCA[0].FOC__c != null && lstCA[0].FOC__c != ''
            && lstCA[0].FOC__c.equalsIgnoreCase('Weekly'))
                objCA.Test__c = lstCA[0].Total_Weekly_Amount_Repayable_Approved__c;
            else
                objCA.Test__c = lstCA[0].Total_Amount_Repayable_Approved__c;
        }
    } // end of creditAssessmentDetails
    
    public list<CreditAssessmentIncomeDetails> getIncomeDetails(){
        
        list<CreditAssessmentIncomeDetails> listIncome = new list<CreditAssessmentIncomeDetails>();
        if (objCA != null){
            listIncome.add(new CreditAssessmentIncomeDetails('M1', (objCA.Paid_In_M1__c != null) ? objCA.Paid_In_M1__c : 0, (objCA.Paid_Out_M1__c != null) ? objCA.Paid_Out_M1__c : 0));
            listIncome.add(new CreditAssessmentIncomeDetails('M2', (objCA.Paid_In_M2__c != null) ? objCA.Paid_In_M2__c : 0, (objCA.Paid_Out_M2__c != null) ? objCA.Paid_Out_M2__c : 0));
            listIncome.add(new CreditAssessmentIncomeDetails('M3', (objCA.Paid_In_M3__c != null) ? objCA.Paid_In_M3__c : 0, (objCA.Paid_Out_M3__c != null) ? objCA.Paid_Out_M3__c : 0));            
        }     
        
        return listIncome;
    }
} // end of class