src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>Approved_Loan_Amount__c</fullName>
        <label>Approved Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approved_Loan_Term__c</fullName>
        <label>Approved Loan Term</label>
        <picklist>
            <picklistValues>
                <fullName>03 (090 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 (120 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 (150 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 (180 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 (210 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 (240 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 (270 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 (365 days)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FOC__c</fullName>
        <formula>TEXT(Opportunity__r.FOC__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Frequency of Collection</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <formula>TEXT(Opportunity__r.Loan_Purpose__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Loan Purpose</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_Interest_Approved__c</fullName>
        <label>Annual Interest (Approved)</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Paid_In_M1__c</fullName>
        <label>Paid In M1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Paid_In_M2__c</fullName>
        <label>Paid In M2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Paid_In_M3__c</fullName>
        <label>Paid In M3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FOC__c</fullName>
        <label>Frequency of Collection</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <label>Loan Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refurbishment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expansion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinancing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CRMS_CreditAssessmentControllerTest.cls
/*
	Test Class for CRMS_CreditAssessmentControllerTest
 */
@isTest
private class CRMS_CreditAssessmentControllerTest{
    static testMethod void myUnitTest(){
       Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());

       Account accountobj = new Account();
       accountobj.Name = 'Test';
       insert accountobj;

       Opportunity opprotunityobj = new Opportunity();
       opprotunityobj.AccountId = accountobj.Id;
       opprotunityobj.Name = 'Test1';
       opprotunityobj.CloseDate = Date.Today();
       opprotunityobj.Loan_Purpose__c = 'Other';
       opprotunityobj.StageName = 'In Progress';
       opprotunityobj.FOC__c = 'Daily';
       insert opprotunityobj;

       Credit_Assessment__c creditobj = new Credit_Assessment__c();
       creditobj.Opportunity__c = opprotunityobj.Id;
       creditobj.Approved_Loan_Amount__c = 1000;
       creditobj.Approved_Loan_Term__c = '06 (180 days)';
       creditobj.Monthly_Interest_Approved__c = 2.5 ;
       creditobj.Test__c = 1000;
       creditobj.Paid_In_M1__c = 5555;
       creditobj.Paid_In_M2__c = 3333;
       creditobj.Paid_In_M3__c = 1111;
       insert creditobj;

       ApexPages.StandardController controller = new ApexPages.StandardController(creditobj);
       CRMS_CreditAssessmentController objCreditAssessment = new CRMS_CreditAssessmentController(controller);
        
        List<CreditAssessmentIncomeDetails> resList = objCreditAssessment.getIncomeDetails();
        
        system.assertEquals(true, resList != null);
        
       //CreditAssessmentobj.creditAssessmentDetails(creditobj.Id);
    } // end of myUnitTest
} // end of class