src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted(Written-off)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disbursed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Disbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Topped-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DWH_Import__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DWH Import</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Credit_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Assessment</label>
        <referenceTo>Credit_Assessment__c</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DWH_Data_Type__c</fullName>
        <label>DWH Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Product Association</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission/Incentive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Ledger</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operation</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Queued_Record_ID__c</fullName>
        <label>Queued Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Status__c</fullName>
        <label>Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sync Queue</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Sync Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRMS_OperationTriggerHandlerTest.cls
@isTest
public class CRMS_OperationTriggerHandlerTest {

	/*@isTest(seeAllData=true)
    static void testCRMS_CreditAssessmentTriggerHandler()
    {
    	Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
    	
    	Test.startTest();
        list<RecordType> lstRecType = [Select r.SobjectType, r.Id, r.DeveloperName, r.Name 
                           From RecordType r 
                            where r.SobjectType = 'Opportunity' and r.DeveloperName like 'Application%'];
        
        Opportunity objOpp = new Opportunity();
        	objOpp.Name = 'test';
            objOpp.CloseDate = date.today();
        	objOpp.StageName = 'Closed Won';
        	objOpp.RecordTypeId = lstRecType[0].Id;
        	
        	insert objOpp;
        	objOpp.Contract_Signed__c = true;
        	update objOpp;
        	
        	
        
        Operation__c lstOperation = [select Id,Opportunity__c,Payment_Received__c,Status__c from Operation__c where Opportunity__c =:objOpp.Id];
        System.debug('lstOperation>>>'+lstOperation);
        lstOperation.Status__c = 'Payment Received';  
        lstOperation.Payment_Received__c = true;
        update lstOperation;
        
        lstOperation.Status__c = 'Payment Outstanding';  
        lstOperation.Payment_Received__c = false;
        update lstOperation;
        
        Test.stopTest();
        
        //list<Task> lstTask = [select Id,Subject,WhatId from Task where WhatId =:objOpp.Id];
        //System.debug('lstTask[0].Subject'+lstTask[0].Subject);
		//System.assertEquals(lstTask[0].Subject, 'Follow Up With Client');
    }*/
    
    static testMethod void test_setOperationDWHStatusSynced() {
        CRMS_Util util = new CRMS_Util();
        CRMS_Util.generateEndpoints();
    	Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
    	
    	Test.startTest();
        Operation__c operationObj = util.initializeOperation(false);
        operationObj.DWH_Status__c = CRMS_Util.DWH_STATUS_SYNCED;
        insert operationObj;
        Test.stopTest();
        List<Operation__c> testOperationList = [select DWH_Status__c,DWH_Last_Sync__c from Operation__c where id = :operationObj.Id];
    	System.assertNotEquals(null, testOperationList[0].DWH_Status__c);
    }
    
    static testMethod void test_setOperationDWHStatusQueued() {
        CRMS_Util util = new CRMS_Util();
       	CRMS_Util.generateEndpoints();
    	Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
    	
    	Test.startTest();
        Operation__c operationObj = util.initializeOperation(false);
        insert operationObj;
        Test.stopTest();
        List<Operation__c> testOperationList = [select DWH_Status__c from Operation__c where id = :operationObj.Id];
   		System.assertNotEquals(null, testOperationList[0].DWH_Status__c);
    }
    
    static testMethod void test_updateOperationDWHStatusSynced() {
        CRMS_Util util = new CRMS_Util();
        CRMS_Util.generateEndpoints();
    	Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
    	
    	Test.startTest();
        Operation__c operationObj = util.initializeOperation(false);
        insert operationObj;
        
        operationObj.DWH_Status__c = CRMS_Util.DWH_STATUS_SYNCED;
        update operationObj;
        Test.stopTest();
        List<Operation__c> testOperationList = [select DWH_Status__c,DWH_Last_Sync__c from Operation__c where id = :operationObj.Id];
    	System.assertNotEquals(null, testOperationList[0].DWH_Status__c);
    }
    
    static testMethod void test_updateOperationDWHStatusQueued() {
        CRMS_Util util = new CRMS_Util();
       	CRMS_Util.generateEndpoints();
    	Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
    	
    	Test.startTest();
        Operation__c operationObj = util.initializeOperation(false);
        operationObj.DWH_Status__c = CRMS_Util.DWH_STATUS_SYNCED;
        insert operationObj;
        
        operationObj.DWH_Status__c = null;
        update operationObj;
        Test.stopTest();
        List<Operation__c> testOperationList = [select DWH_Status__c from Operation__c where id = :operationObj.Id];
    	System.assertNotEquals(null, testOperationList[0].DWH_Status__c);
    }
   /*
    static testMethod void test_updateOperationStatus() {
        CRMS_Util util = new CRMS_Util();
        
        Operation__c operationObj = util.initializeOperation(false);
        operationObj.DWH_Import__c = true;
        insert operationObj;
        
        List<Operation__c> testOperationList = [select DWH_Status__c,DWH_Import__c from Operation__c where id = :operationObj.Id];
        system.assertEquals(false, testOperationList[0].DWH_Import__c);
        system.assertEquals(CRMS_Util.DWH_STATUS_SYNCED, testOperationList[0].DWH_Status__c);
    }
    
    static testMethod void test_createSyncQueueAfterOperationInsert() {
        CRMS_Util util = new CRMS_Util();
        
                                
        Operation__c operationObj = util.initializeOperation(false);
        operationObj.DWH_Import__c = false;
        insert operationObj;
        
        List<Sync_Queue__c> syncQueList = [SELECT Sync_Status__c FROM Sync_Queue__c WHERE Operation__c = :operationObj.Id];
        system.assertEquals(1,syncQueList.size());
        system.assertEquals(CRMS_Util.SYNC_QUEUE_STATUS_PENDING,syncQueList[0].Sync_Status__c);
    }
    
    static testMethod void test_createSyncQueueAfterOperationUpdate() {
        CRMS_Util util = new CRMS_Util();
        
                                
        Operation__c operationObj = util.initializeOperation(false);
        operationObj.DWH_Import__c = true;
        insert operationObj;
        
        List<Operation__c> operationList = [SELECT DWH_Import__c,DWH_Status__c FROM Operation__c WHERE Id = :operationObj.Id];
        operationList[0].DWH_Import__c = false;
        operationList[0].DWH_Status__c = CRMS_Util.DWH_STATUS_QUEUED;
        update operationList;
        
        List<Sync_Queue__c> syncQueList = [SELECT Sync_Status__c FROM Sync_Queue__c WHERE Operation__c = :operationObj.Id];
        system.assertEquals(1,syncQueList.size());
        system.assertEquals(CRMS_Util.SYNC_QUEUE_STATUS_PENDING,syncQueList[0].Sync_Status__c);
    }*/
    
    static testMethod void test_createSyncQueueRecord_BeforeDelete() {
        CRMS_Util util = new CRMS_Util();
        CRMS_Util.generateEndpoints();
    	Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
    	
    	Test.startTest();
        //If Sync Queue record meeting criteria is not found
        Operation__c operationObj1 = util.initializeOperation(false);
        operationObj1.DWH_Status__c = CRMS_Util.DWH_STATUS_QUEUED;
        insert operationObj1;
        
        String operationId = operationObj1.Id;
        delete operationObj1;
        Test.stopTest();
        List<Sync_Queue__c> syncQueListTest1 =[
            SELECT Operation__c
                 , Id
                 , Notes__c
                 , Action__c
                 , Queued_Record_ID__c
                 , Sync_Status__c
                 , DWH_Data_Type__c
               FROM Sync_Queue__c 
              WHERE Queued_Record_ID__c = :operationId
        ];
        
    }
    
    static testMethod void test_updateSyncQueueRecord_BeforeDelete() {
        CRMS_Util util = new CRMS_Util();
        CRMS_Util.generateEndpoints();
    	Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
    	
    	Test.startTest();
        //If Sync Queue record meeting criteria is not found
        Operation__c operation = util.initializeOperation(false);
        operation.DWH_Status__c = CRMS_Util.DWH_STATUS_QUEUED;
        insert operation;
        
        Sync_Queue__c syncQueue = new Sync_Queue__c();
        syncQueue.Operation__c = operation.Id;
        syncQueue.Sync_Status__c = CRMS_Util.SYNC_QUEUE_STATUS_PENDING;
        insert syncQueue;
        system.debug('***syncQueue '+syncQueue); 
        String operationId = operation.Id;
       
        delete operation;
        Test.stopTest();
        List<Sync_Queue__c> syncQueListTest1 =[
            SELECT Credit_Assessment__c
                 , Id
                 , Notes__c
                 , Action__c
                 , Queued_Record_ID__c
                 , Sync_Status__c
                 , DWH_Data_Type__c
               FROM Sync_Queue__c 
              WHERE Queued_Record_ID__c = :operationId
        ];
        
        
    }
}