src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>AMP_Credit_Score__c</fullName>
        <label>AMP Credit Score</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Additional_Information_Details__c</fullName>
        <label>Additional Information Details</label>
        <picklist>
            <controllingField>Additional_Information_Required__c</controllingField>
            <picklistValues>
                <fullName>Financial Info-Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Info- Management Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evidence Of Time Trading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarantor Details-Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarantor Details-Personal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evidence Of Additional Capitalisation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clarification Over Residential Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Asset &amp; Liability Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Additional_Information_Narrative__c</fullName>
        <label>Additional Information Narrative</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Additional_Information_Required__c</fullName>
        <label>Additional Information Required</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Additional_Information_Satisfactory__c</fullName>
        <label>Additional Information Satisfactory</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Applicant_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Assessments (Applicant Name)</relationshipLabel>
        <relationshipName>Credit_Assessments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approved_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_Interest_Rate__c</fullName>
        <label>Approved Interest Rate</label>
        <picklist>
            <picklistValues>
                <fullName>18%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30%</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>31%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>33%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>34%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>35%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>38%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>39%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40%</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approved_Loan_Amount__c</fullName>
        <label>Approved Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approved_Loan_Term__c</fullName>
        <label>Approved Loan Term</label>
        <picklist>
            <picklistValues>
                <fullName>03 (090 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 (120 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 (150 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 (180 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 (210 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 (240 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 (270 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 (365 days)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_IQ_Score__c</fullName>
        <label>Business IQ Score</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Trading_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Trading Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Final_Decision_Date__c</fullName>
        <label>Final Decision Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Decision__c</fullName>
        <label>Final Decision</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Narrative_Box__c</fullName>
        <label>Narrative Box</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program_Product_ASO__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program_Product_ASO__c.Rules_Engine__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Max_Interest_rate__c</fullName>
        <label>Max Interest rate</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Interest_rate__c</fullName>
        <label>Min Interest Rate</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>DWH_Last_Sync__c</fullName>
        <label>DWH Last Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>PPAS</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AMPSales_CreditAssessment_Controller.cls
public with sharing class AMPSales_CreditAssessment_Controller {
	
	public Credit_Assessment__c CreditAssessment	{get; set;}{
		CreditAssessment = new Credit_Assessment__c();
	}
	public string ApprovedInterestRate	{get; set;}
	public string ReturnURL	{get; set;}
	
	public AMPSales_CreditAssessment_Controller(ApexPages.StandardController StdCntlr_CreditAssessment){
		Credit_Assessment__c ContexttRecord = (Credit_Assessment__c)StdCntlr_CreditAssessment.getRecord();
		CreditAssessment = this.getCreditAssessmentRecord(ContexttRecord.Id);
		ApprovedInterestRate = CreditAssessment.Approved_Interest_Rate__c;
		ReturnURL = ApexPages.currentPage().getParameters().get('retURL');
	}
	
	private Credit_Assessment__c getCreditAssessmentRecord(ID RecordId){
		try{
			return [Select c.Status__c, 
					c.RecordType.Name, 
					c.RecordTypeId, 
					c.Program__c, 
					c.Program_Product_ASO__c, 
					c.Opportunity__c, 
					c.Narrative_Box__c, 
					c.Name,
					c.Id,
					c.Owner.Name, 
					c.Final_Decision__c, 
					c.Final_Decision_Date__c, 
					c.DWH_Status__c, 
					c.DWH_Last_Sync__c, 
					c.Business_Trading_Name__c, 
					c.Business_IQ_Score__c, 
					c.Approved_Loan_Term__c, 
					c.Approved_Loan_Amount__c, 
					c.Approved_Interest_Rate__c, 
					c.Approved_By__c, 
					c.Approval_Date__c, 
					c.Applicant_Name__c, 
					c.Additional_Information_Satisfactory__c, 
					c.Additional_Information_Required__c, 
					c.Additional_Information_Narrative__c,
					c.Additional_Information_Details__c, 
					c.AMP_Credit_Score__c 
				From Credit_Assessment__c c where Id =:RecordId limit 1];			
		}catch(QueryException ex){
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getmessage()));
		}
		return null;
	}
	
	public void updateApprovedInterestRates(){
		this.getApprovedInerestRates();
	}
	
	public list<selectoption> getApprovedInerestRates(){
		list<selectoption> InterestRates = new list<selectoption>();
		Product2 SelectedProduct = 	this.getMinAndMaxInterestRateForProduct(CreditAssessment.Program_Product_ASO__c);
					
		Schema.DescribeFieldResult ApprovedInterestRates = Credit_Assessment__c.Approved_Interest_Rate__c.getDescribe();        
		for(Schema.PicklistEntry picklist: ApprovedInterestRates.getPicklistValues()){
			if(SelectedProduct != null){
				if(integer.valueof(picklist.getValue().replace('%', '')) >= SelectedProduct.Min_Interest_rate__c
					&& integer.valueof(picklist.getValue().replace('%', '')) <= SelectedProduct.Max_Interest_rate__c){
					InterestRates.add(new selectoption(picklist.getValue(), picklist.getLabel()));	
				}
			}else InterestRates.add(new selectoption(picklist.getValue(), picklist.getLabel()));
		}
		return InterestRates;
	}
	
	private Product2 getMinAndMaxInterestRateForProduct(ID ProductId){
		try{
			Program_Product_ASO__c ProgramProduct = [Select p.Product__r.Max_Interest_rate__c, 
														p.Product__r.Min_Interest_rate__c,
														p.Product__r.Full_Term__c 
													From Program_Product_ASO__c p where p.Id =:ProductId];
		
			if(ProgramProduct != null){
				CreditAssessment.Approved_Loan_Term__c = ProgramProduct.product__r.Full_Term__c;
				return ProgramProduct.product__r;
			}			
		}catch(QueryException ex){}		
		return null;
	}
	
	public PageReference Save(){
		try{
			CreditAssessment.Approved_Interest_Rate__c = ApprovedInterestRate;
			Database.update(CreditAssessment);
		}catch(DMLException ex){
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getmessage()));
			return null;
		}
		return new Pagereference(ReturnURL);
	}
}