src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>Client_ID__c</fullName>
        <formula>Opportunity__r.Account.Client_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>IF(contains(RecordType.DeveloperName,&apos;Philippines&apos;),&apos;PP&apos;,
IF(contains(RecordType.DeveloperName,&apos;Hong&apos;),&apos;HK&apos;,
IF(contains(RecordType.DeveloperName,&apos;Singapore&apos;),&apos;SG&apos;,&apos;UK&apos;)))</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program_Product_ASO__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program_Product_ASO__c.Rules_Engine__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Credit Assessments</relationshipLabel>
        <relationshipName>Credit_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_Ledger__c.object
<CustomObject>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Product ASO</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Loan Ledgers</relationshipLabel>
        <relationshipName>Loan_Ledgers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan Ledger</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_Management__c.object
<CustomObject>
    <fields>
        <fullName>Grace_period__c</fullName>
        <label>Grace period</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Max_number_of_payment_holidays__c</fullName>
        <label>Max number of payment holidays</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notification_days__c</fullName>
        <label>Notification days</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Program_Product_ASO__r.Product__r.Product_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <label>Program Product ASO</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipName>Loan_Management</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Program_Product_ASO__r.Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <label>Rules Engine</label>
    <nameField>
        <displayFormat>LM-{000}</displayFormat>
        <label>Loan Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules Engines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Country__c</fullName>
        <formula>IF(contains(RecordType.DeveloperName,&apos;UK&apos;),&apos;UK&apos;, 
IF(contains(RecordType.DeveloperName,&apos;Hong&apos;),&apos;HK&apos;, 
IF(contains(RecordType.DeveloperName,&apos;Singapore&apos;),&apos;SG&apos;,&apos;PP&apos;)))</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Hong Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philippines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Program__c</field>
                <operation>equals</operation>
                <valueField>Program_Product_ASO__c.Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program_Product_ASO__c.Rules_Engine__c</field>
                <operation>notEqual</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>contains</operation>
                <valueField>Program__c.Country_Mapping__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UK</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <picklist>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>180</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>210</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>240</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>270</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>365</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UK</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <recordTypes>
        <fullName>UK</fullName>
        <active>true</active>
        <label>UK</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>PPAS</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Loan_Management_Controller_Test.cls
@isTest(seeAllData = true)
public class Loan_Management_Controller_Test {
    public static testmethod void  testIt () {
        
        //CRMS_Util.generateEndpoints();
        
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        Program__c prog = new Program__c(Country__c = 'UK1');
        insert prog;
        Product2 prod = new Product2(Country__c = 'UK1',Term__c = '55');
        insert prod;    
        Program_Product_ASO__c ppas1 = new Program_Product_ASO__c(Program__c = prog.id, Product__c = prod.Id);
        insert ppas1;   
        
        Account acc = new Account(Type = 'Client', Name = 'MiroTestLMAccount');
        insert acc;
        Account accResult = [Select Id, Name, Client_ID__c From Account Where ID = :acc.id][0];
        Loan_Management__c lm = new Loan_Management__c(Program_Product_ASO__c = ppas1.id,Max_number_of_payment_holidays__c = '5',
                                                       Notification_days__c ='5', Grace_period__c = '5' );
        insert lm;         
        Opportunity opp = new Opportunity(Name = 'MiroTestDisbursalSummary', StageName = 'In Progress', CloseDate = Date.today().addDays(10),
                                         AccountId   = acc.id,  Country__c = 'UK');
        insert opp;        
        Credit_Assessment__c ca = new Credit_Assessment__c(Opportunity__c = opp.id, Business_Trading_Name__c   = acc.Id);
        insert ca;
        Operation__c op1 = new Operation__c(Account__c = acc.id, Opportunity__c = opp.id, Program_Product_ASO__c = ppas1.Id,Loan_Disbursed_Date__c = Date.today().addDays(-1),
                                            Final_Repayment_Date__c = Date.today().addDays(20), Number_of_Repayments__c = 3);
        insert op1;       
        Loan_Ledger__c lr = new Loan_Ledger__c(Account__c = acc.id, Program_Product_ASO__c = ppas1.id, Sign_Off_Date__c = Date.today(),
                                               LoanID__c = op1.id, Agreed_by_client__c = true,InputFromScreen__c = 'bounceBackSection',
                                              Borrowed_Amount__c = 10000, Outstanding_Amount__c = 5000);
        insert lr;
        
        Loan_Management_Controller wrongC = new Loan_Management_Controller();
        
         ApexPages.currentPage().getParameters().put('AccountID', acc.id);     
         Loan_Management_Controller c = new Loan_Management_Controller();
        
         c.clientID = accResult.Client_ID__c;
         c.getClients();
         system.assertEquals(false, c.clientList.isEmpty());
         c.clientList = null;
         c.clientID = null;
         c.clientName = accResult.Name;
         c.getClients();      
         system.assertEquals(false, c.clientList.isEmpty());
        
         c.getProgramsWithLedger();
         c.selectedProgram = prog.id;
         c.getLedgerFromProgram();
        
        system.assertEquals(false, c.loanList.isEmpty());
        
        c.moveToSuspension();
        
        List<Loan_Ledger__c> result1 = [Select Id, Move_to_Suspension__c From Loan_Ledger__c Where Account__c = :acc.Id];
        
        system.assertEquals(true, result1[0].Move_to_Suspension__c);
        c.AccountID = acc.Id;
        c.lr.InputFromScreen__c = 'restructureSection';
        c.screenSelected = 'restructureSection';
        c.agreedByClient = true;
        c.signOff();
        
        c.screenSelected = 'topUpSection';
        c.lr.InputFromScreen__c = 'topUpSection';
        c.signOff();
        
        List<Opportunity> result2 = [Select Id,Type  From Opportunity Where AccountID = :acc.Id And ID != :opp.id];
        
        system.assertEquals('Restructure', result2[0].Type);
        system.assertEquals('Top-up', result2[1].Type);
        
        c.calculation();
        
        c.EventStartDate = String.valueOf(Date.today());
         c.EventEndDate = String.valueOf(Date.today().addDays(1));
        c.EventAmount = '10000';
        c.EventAmountAllocation1 = '';
        c.EventAmountAllocation2 = '';
         System.HttpResponse response = new System.HttpResponse ();    
            response.setStatus('OK');
            response.setStatusCode(200);
        String body = '{"requestId":"","objectName":"LoanScheduleDetail","timestamp":"2015-12-17T09:27:38.9588006Z","results":[{"result":"Success","reason":"Success",'+
            '"newEndDate":"2016-04-02T00:00:00","newPrincipalAmount":1111,"newInterestAmount":2222,"loanVATAmount":33.00,"loanChargesAmount":44,'+
            '"programProductSFId":"' +ppas1.id + '"}]}';
            response.setBody(body);
        
        c.calculationResponse(response);
    }
}