src/objects/Credit_Assessment__c.object
<CustomObject>
    <description>AMP Credit Assessment Custom Object</description>
    <fields>
        <fullName>AMP_Credit_Score__c</fullName>
        <label>AMP Credit Score</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Application_ID__c</fullName>
        <formula>Opportunity__r.Application_ID2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interest_Daily_Repayment_Offer__c</fullName>
        <label>Interest Daily Repayment (Offer)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Weekly_Repayment_Offer__c</fullName>
        <label>Interest Weekly Repayment (Offer)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Interest__c</fullName>
        <defaultValue>IF(OR($RecordType.DeveloperName == &apos;Credit_Assessment_UK&apos;,$RecordType.DeveloperName == &apos;Credit_Assessment_Completed&apos;) ,  $Setup.IR__c.Annual_UK__c ,  $Setup.IR__c.Annual__c )</defaultValue>
        <label>Annual Interest</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Number_of_Repayments_Offer__c</fullName>
        <label>Number of Repayments (Offer)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offer_Amount__c</fullName>
        <label>Offer Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offer_Term__c</fullName>
        <label>Offer Term</label>
        <picklist>
            <picklistValues>
                <fullName>03 (090 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 (120 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 (150 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 (180 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 (210 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 (240 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 (270 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 (365 days)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Offer_Total_Repayment__c</fullName>
        <label>Offer Total Repayment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Principal_Daily_Repayment_Offer__c</fullName>
        <label>Principal Daily Repayment (Offer)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Principal_Weekly_Repayment_Offer__c</fullName>
        <label>Principal Weekly Repayment (Offer)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Repayable_Offer__c</fullName>
        <label>Total Amount Repayable (Offer)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Daily_Repayment_Offer__c</fullName>
        <label>Total Daily Repayment (Offer)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Weekly_Repayment_Offer__c</fullName>
        <label>Total Weekly Repayment (Offer)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Credit Assessment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Credit Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRMS_RESTCreditAssessment.cls
/**
@ Created Date : 31-3-2015. 
@ Description  : It is used to update the credit assessment record using REST. 
@ Author       : CRMSuperstars
*/
@RestResource(urlMapping='/FieldCreditAssessment/*')
global class CRMS_RESTCreditAssessment {
    // Used to stor response json
    public static String responseJSON = '';
    public static List<restResponseLog> listResponse = new List<restResponseLog>();
    // DTO -- Inner class for json 
    global class restRequestLog{
        public String ApplicationNumber;
        //public Integer AplicationId;
        public String SalesforceCreaditAssessmentId;
        public Decimal CreditScore; 
        public Decimal OfferAmount;
        public Decimal OfferedPrincipalDailyRepaiment;
        public Decimal OfferedPrincipalWeeklyRepayment;
        public Decimal OffederInterestDailyRepayment;
        public Decimal OfferedInterestWeeklyRepayment;
       
        public Decimal OfferedTotalDailyRepayment;
        public Decimal OfferedTotalWeeklyRepayment;
        public Decimal OfferedTotalRepayment;
        public Integer LoanTermInMonths;
        public Decimal MonthlyInterest;
        public Integer DailyRepaimentNum;
    }
    
    global class restResponseLog{
        public Integer status_code;
        public String description;
        public String salesforce_Credit_AssessmentID;
     }
     @HttpPost
     global static String updateCreditAssessment(){
        
        // Used to store all credit assessments to insert
        List<Credit_Assessment__c> listCreditAToUpdate  = new List<Credit_Assessment__c>();
        RestRequest req = RestContext.request;
        //String requestJSON = RestRequest.requestBody.toString();
        // List Of operation Id
        List<Id> listID = new List<Id>();
        try{
            // json de-serialize 
            List<restRequestLog> listCreditAssessment = (List<restRequestLog>)JSON.deserialize(req.requestbody.tostring(), List<restRequestLog>.class);
            system.debug('******* Request Data to Insert ******'+listCreditAssessment);
            // Get operation Ids
            for( restRequestLog creditAss : listCreditAssessment){
                listID.add(creditAss.SalesforceCreaditAssessmentId);
            }
            // Query all operation record contains list Id
            Map<ID, Credit_Assessment__c> mapCreditAssess = new Map<ID, Credit_Assessment__c>([SELECT Id, Application_ID__c, AMP_Credit_Score__c, Offer_Amount__c,
                                                                                                        Principal_Daily_Repayment_Offer__c, Interest_Daily_Repayment_Offer__c,
                                                                                                        Total_Amount_Repayable_Offer__c, Total_Daily_Repayment_Offer__c,
                                                                                                        Offer_Total_Repayment__c, Offer_Term__c, Monthly_Interest__c,
                                                                                                        Number_of_Repayments_Offer__c
                                                                                                FROM Credit_Assessment__c 
                                                                                                Where Id = : listID]);
            
            if( listCreditAssessment != null ){
                // Need to check null 
                for (restRequestLog creditAssessment : listCreditAssessment ){
                    system.debug('======Application Id Is:::::'+creditAssessment.ApplicationNumber);
                    Credit_Assessment__c newCreditAssessment = new Credit_Assessment__c();
                    newCreditAssessment = mapCreditAssess.get(creditAssessment.SalesforceCreaditAssessmentId);
                    if( newCreditAssessment != null ){
                        if( newCreditAssessment.Application_ID__c == creditAssessment.ApplicationNumber ){
                            //newCreditAssessment.Id = (Id)creditAssessment.SalesforceCreaditAssessmentId;
                            newCreditAssessment.AMP_Credit_Score__c = creditAssessment.CreditScore;
                            newCreditAssessment.Offer_Amount__c = creditAssessment.OfferAmount;
                            newCreditAssessment.Principal_Daily_Repayment_Offer__c = creditAssessment.OfferedPrincipalDailyRepaiment;
                            newCreditAssessment.Principal_Weekly_Repayment_Offer__c = creditAssessment.OfferedPrincipalWeeklyRepayment;
                            newCreditAssessment.Interest_Daily_Repayment_Offer__c = creditAssessment.OffederInterestDailyRepayment;
                            newCreditAssessment.Interest_Weekly_Repayment_Offer__c = creditAssessment.OfferedInterestWeeklyRepayment;
                            newCreditAssessment.Total_Daily_Repayment_Offer__c = creditAssessment.OfferedTotalDailyRepayment; 
                            newCreditAssessment.Total_Weekly_Repayment_Offer__c = creditAssessment.OfferedTotalWeeklyRepayment;
                            newCreditAssessment.Offer_Total_Repayment__c = creditAssessment.OfferedTotalRepayment;
                            newCreditAssessment.Offer_Term__c = string.valueOf(creditAssessment.LoanTermInMonths);
                            newCreditAssessment.Monthly_Interest__c = creditAssessment.MonthlyInterest;
                            newCreditAssessment.Number_of_Repayments_Offer__c = creditAssessment.DailyRepaimentNum;
                            
                            listCreditAToUpdate.add(newCreditAssessment);
                        }else 
                            generateResponseJSON('Application Id does not Match ', 304, newCreditAssessment.Id);
                        
                    }else 
                        generateResponseJSON('Salesforce Credit Assessment ID does not match. Please provied correct salesforce Id. ', 400, creditAssessment.SalesforceCreaditAssessmentId);
                    
                }
                // Use to store the insert result
                Database.SaveResult[] listInsertResult;
                 system.debug('***** TO DO *****');
                if( listCreditAToUpdate.size() > 0 ){
                    listInsertResult = Database.update(listCreditAToUpdate, false);
                
                    // Iterate through each returned result
                    for (Database.SaveResult saveResult : listInsertResult) {
                        if (saveResult.isSuccess()) {
                            // Operation was successful, so get the ID of the record that was processed
                            System.debug('Successfully inserted Credit Assessment. Credit Assessment ID: ' + saveResult.getId());
                            generateResponseJSON('Successfully updated Credit Assessment. ', 200, saveResult.getId());
                        }
                        else {
                            // Operation failed, so get all errors                
                            for(Database.Error err : saveResult.getErrors()) {
                                generateResponseJSON('The error has occurred.'+err.getStatusCode() + ': ' + err.getMessage()+'Credit Assessment fields that affected this error: ' + err.getFields(), 400, saveResult.getId());
                                System.debug('The following error has occurred.');
                                System.debug(err.getStatusCode() + ': ' + err.getMessage());
                                System.debug('Credit Assessment fields that affected this error: ' + err.getFields());
                            }
                        }
                    }
                }
            }
        }catch(Exception e){
            system.debug('********** Exception Is ******* ::'+e.getMessage());
            generateResponseJSON('The error has occurred.'+e.getMessage(), 400, null);
            
            if( listResponse.size() > 0)
                responseJSON = JSON.serialize(listResponse);
            return responseJSON; 
        }
        
        if(listResponse.size() > 0 )
            responseJSON = JSON.serialize(listResponse);
      return responseJSON;  
     }
      // Use to create status code with error.
    public static void generateResponseJSON( string responseMessage, integer statusCode, String operationID){
        restResponseLog response = new restResponseLog();
        response.status_code = statusCode;
        response.description = responseMessage;
        response.salesforce_Credit_AssessmentID = operationID;
        listResponse.add(response);
        
        //return JSON.serialize(response);
    }
}