src/objects/IR__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Annual_UK__c</fullName>
        <label>Annual UK</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Interest Rates</label>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Country__c</fullName>
        <formula>IF(contains(RecordType.DeveloperName,&apos;UK&apos;),&apos;UK&apos;, 
IF(contains(RecordType.DeveloperName,&apos;Hong&apos;),&apos;HK&apos;, 
IF(contains(RecordType.DeveloperName,&apos;Singapore&apos;),&apos;SG&apos;,&apos;PP&apos;)))</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Hong Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philippines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Program__c</field>
                <operation>equals</operation>
                <valueField>Program_Product_ASO__c.Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program_Product_ASO__c.Rules_Engine__c</field>
                <operation>notEqual</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Check_Name__c</fullName>
        <label>Check Name</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UK</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Full_Term__c</fullName>
        <label>Full_Term</label>
        <picklist>
            <picklistValues>
                <fullName>03 (090 days)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>04 (120 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 (150 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 (180 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 (210 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 (240 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 (270 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 (365 days)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <defaultValue>$Setup.IR__c.Annual_UK__c</defaultValue>
        <label>Interest Rate</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Interest_type__c</fullName>
        <label>Interest type</label>
        <picklist>
            <picklistValues>
                <fullName>Flat</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Diminishing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Max_Interest_rate__c</fullName>
        <label>Max Interest rate</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Interest_rate__c</fullName>
        <label>Min Interest Rate</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <description>AMP(or partner name) “Country code” – “Scheduled type” Repayment type Interest type, interest type. The name cannot be manually entered but it is automatically generated</description>
        <formula>TEXT(Country__c) &amp; &quot; - &quot; &amp; TEXT(Product_Type__c)&amp; &quot; - &quot; &amp; TEXT(Schedule_Type__c  )&amp; &quot;, &quot; &amp; TEXT(Interest_type__c)&amp; &quot; Interest &quot; &amp; TEXT(Interest_Rate__c*100)&amp; &quot;%, &quot; &amp; TEXT(Full_Term__c)</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Loan</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <label>Schedule Type</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <picklist>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>180</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>210</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>240</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>270</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>365</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Check_Name__c</fullName>
        <label>Check Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Loan_Product_Controller.cls
public class Loan_Product_Controller {
    public ID recID {get;set;}
    public Product2 p {get;set;}    
    public boolean isNewOrEditRecord {get; set;}  
    public boolean isNewRecord {get;set;} 
    public boolean isDeleteActive {get;set;}
    public decimal selectedMinrate {get; set;}
    public decimal selectedMaxrate {get; set;}     
        
    public Loan_Product_Controller (ApexPages.StandardController stdController) {
        
        recID = ApexPages.currentPage().getParameters().get('id');
        if(recID == null)
            this.p = (Product2)stdController.getRecord();
        else
        {
            this.p = [Select Id, Name, ProductCode, Description, IsActive,Interest_type__c,
                      Product_Type__c, Country__c, Schedule_Type__c, Interest_Rate__c,Term__c, Full_Term__c,
                      Product_Name__c, Min_Interest_rate__c, Max_Interest_rate__c, Check_Name__c,CreatedById,LastModifiedById,CreatedDate,LastModifiedDate 
                      FROM Product2 Where id = :recID][0];
            
            isNewOrEditRecord=true;
            isNewRecord = false;
                                                
            if([select Id from Opportunity where Program_Product_ASO__r.Product__c  =:p.Id].size() > 0 || 
               [select Id from Operation__c where Program_Product_ASO__r.Product__c =:p.Id].size() > 0){
               /*
                *	Khurram Shahzad (02/03/2016) LMS-184
                *	Warning Message When user tries to edit the product which is associated with Loan.
                */
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'There are loans in the system created with this product. Changes on this page, will affect their interest calculation.'));
                isDeleteActive = false;
            }else
                isDeleteActive = true;
        }
        if(p.Country__c == null && p.Schedule_Type__c == null) {
            //p.Country__c ='UK';
            isNewRecord = true;
            IR__c ukInterest = IR__c.getInstance();
            p.Interest_Rate__c = ukInterest.Annual_UK__c*100;   
        }
        if(isDeleteActive == null) isDeleteActive = true;
        if(isNewOrEditRecord == null) isNewOrEditRecord = false;
        if(isNewRecord == null) isNewRecord = false;
    }
    
    public List<SelectOption> getIntList()
    {
        List<SelectOption> options = new List<SelectOption>();
        for (Integer i = 0; i <= 10; i ++)
            options.add(new SelectOption(string.valueof(i), string.valueof(i)));
        
        if (p.Interest_Rate__c != null && p.Min_Interest_rate__c != null && p.Max_Interest_rate__c != null)
        {
            selectedMinrate = p.Interest_Rate__c - p.Min_Interest_rate__c;
            selectedMaxrate = p.Max_Interest_rate__c - p.Interest_Rate__c;
        }
        
        return options;
    }
    
    public PageReference newRec()
    {
        isNewOrEditRecord = true;
        return null;
    }
     public PageReference save (){
                       
        try{
            p.Min_Interest_rate__c = p.Interest_Rate__c - selectedMinrate;
            p.Max_Interest_rate__c = p.Interest_Rate__c + selectedMaxrate;
            system.debug('p'+p);           
            upsert p;   
            
            Pagereference pr = new Pagereference('/apex/Loan_Product');
            //pr.getParameters().put('ID',recID);
            pr.setRedirect(true);
            return pr;
        }catch(DmlException e){
            String mess = e.getMessage();
            String existingID = mess.substringAfter('id: ').removeEnd(': []');
            system.debug('existingID:' + existingID);
            boolean checkName = mess.containsIgnoreCase('Check_Name__c');
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'A product with the same name already exists. You can open it <b><a href="Loan_Product?ID='+existingID+'" style="margin:0 0px;">here</a></b> ');
            //ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, checkName ? 'A product with the same name already exists. You can open it <b><a href="Loan_Product?ID='+existingID+'" style="margin:0 0px;">here</a></b> ' : 'Sorry :/');
			ApexPages.addMessage(myMsg);
        } 
        return null;
    }    
    public PageReference deleteRecord () {
        delete p;
        
        Pagereference pr = new Pagereference('/apex/Loan_Product');
        pr.setRedirect(true);
        return pr;
    }
    public PageReference cancel () {        
        Pagereference pr = new Pagereference('/apex/Loan_Product');
        pr.setRedirect(true);
        return pr;
    }
}