src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Business_Position__c</fullName>
        <label>Business Position</label>
        <picklist>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shareholder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarantor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Do_Not_Mail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Mail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Do_Not_Txt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Txt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <label>Owner Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Website_Tracker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner Tracker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>contains</operation>
                <value>Partner</value>
            </filterItems>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>Account.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Partner_Leads</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonAccountId__c</fullName>
        <label>PersonAccountId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TA_Country__c</fullName>
        <label>TA Country</label>
        <picklist>
            <picklistValues>
                <fullName>England</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hong Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philippines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AMPSales_PersonalAccount.cls
public with sharing class AMPSales_PersonalAccount {
	
	public void CreatePersonAccountFromLead(list<Lead> SObjectListOfLead){		 
		map<ID, Account> PersonAccountMap = new map<ID, Account>();	
		
		for(Lead L: SObjectListOfLead){
			
			PersonAccountMap.put(L.Id, new Account(
				FirstName 					= L.FirstName,
                LastName 					= L.LastName,               
                Phone 						= L.Phone,
                Partner_Website_Tracker__c 	= L.Partner_Website_Tracker__c,
                PersonEmail 				= L.Email,
                PersonLeadSource 			= L.LeadSource,
               	Business_Position__pc	 	= L.Business_Position__c,
                Salutation 					= L.Salutation,
                Salutation__pc 				= L.Salutation,
                Owner_Name__pc 				= L.Owner_Name__c,
                Home_Country__pc 			= L.TA_Country__c,
                PersonHasOptedOutOfEmail 	= L.HasOptedOutOfEmail,
                PersonDoNotCall 			= L.DoNotCall,
                Do_Not_Txt__pc 				= L.Do_Not_Txt__c,
                Do_Not_Mail__pc 			= L.Do_Not_Mail__c
			));			
		}
		if(PersonAccountMap.size() > 0 && PersonAccountMap != null){
			Database.insert(PersonAccountMap.values());			
			
			for(Lead L: SObjectListOfLead){				
				L.PersonAccountId__c = PersonAccountMap.get(L.Id).Id;					
			}
		}
	}
}