src/objects/Loan_Management__c.object
<CustomObject>
    <fields>
        <fullName>Notification_days__c</fullName>
        <label>Notification days</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <label>Program Product ASO</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipName>Loan_Management</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rules Engine</label>
    <nameField>
        <displayFormat>LM-{000}</displayFormat>
        <label>Loan Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules Engines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Management_Event__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ApprovedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Loan_Management_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bounce Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waive Accummulated Fees</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Loan</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Loan Management Events</relationshipLabel>
        <relationshipName>Loan_Management_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Event_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Event Id</label>
        <referenceTo>Loan_Management_Event__c</referenceTo>
        <relationshipLabel>Loan Management Events</relationshipLabel>
        <relationshipName>Loan_Management_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan Management Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Management Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Actual_Interest_Amount__c</fullName>
        <label>Actual Interest Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_Number_of_Repayments__c</fullName>
        <label>Actual Number of Repayments</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_VAT_Amount__c</fullName>
        <label>Actual VAT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_Repayment_Date__c</fullName>
        <label>Final Repayment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loan_Outstanding_Interest__c</fullName>
        <label>Loan Outstanding Interest</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Outstanding_VAT_Amount__c</fullName>
        <label>Loan Outstanding VAT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remaining_Number_of_Repayments__c</fullName>
        <label>Remaining Number of Repayments</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted(Written-off)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disbursed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Disbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Topped-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LM_Resume_Test.cls
public class LM_Resume_Test implements Queueable, Database.AllowsCallouts {
    public String operationId {get; set;}
    private LM_CalculationResult cr {get; set;} 
    
    public LM_Resume_Test(Id opId)
    {
        System.debug('In Constr');
        operationId = opId;
    }
    
    public void execute(QueueableContext context) {
        System.debug('DANI');
        System.debug(operationId);
        Loan_Management_Event__c rejectedLME = [SELECT Id, IsActive__c, Operation__r.Program_Product_ASO__c, Notes__c FROM Loan_Management_Event__c
                                                WHERE Operation__c = :operationId AND IsActive__c = :true AND Event_Type__c IN ('Restructure', 'Top-up', 'Payment Holiday')][0];
        
        String notDays = [SELECT Notification_days__c FROM Loan_Management__c WHERE Program_Product_ASO__c = :rejectedLME.Operation__r.Program_Product_ASO__c][0].Notification_days__c;
                
// Callout Calculate
        String calcGetParams = '?LoanId=' + operationId +
                            '&EventType=' + 'Resume'.replaceAll(' ', '%20') +
                            '&EventStartDate=' + CRMS_Util.DateToString(Date.today(), LMS_Constants.DATE_FORMAT_DWH) +
                            '&EventEndDate=&EventAmount=&LoanTerm=&EventProcessMethod=&PaymentReceived=&PrincipalAllocation=&InterestAllocation=';  
        
        string calculateResponse = LMS_Callout.CallOutGET(LMS_Constants.endpointValue, calcGetParams);
       
        Map<String, Object> responseMap =  (Map<String, Object>)JSON.deserializeUntyped(calculateResponse); 
        List<Object> responseResultsList = (List<Object>)responseMap.get('results');
              
        Map<String, Object> resultsMap = (Map<String, Object>)responseResultsList[0];          
        
        String responseResultJSON = JSON.serialize(responseMap.get('results'));
        cr = ((List<LM_CalculationResult>)JSON.deserialize(responseResultJSON, List<LM_CalculationResult>.class))[0];
        System.debug('Calc_El');
        System.debug(cr);
// End Collout Calculate       
        
// Callout EffectiveDate
        String dateGetParams = '?LoanId=' + operationId + 
                    '&StartDate=' + CRMS_Util.DateToString(Date.today(), LMS_Constants.DATE_FORMAT_DWH) +
                    '&Days=' + String.valueOf(Integer.valueOf(notDays) + 1) +
                    '&EventType=' + 'Resume'.replaceAll(' ', '%20');
        
        Date EffectiveDate = Date.valueOf(((string)LMS_Callout.GetResultsMapFromResponse(LMS_Callout.CallOutGET(LMS_Constants.FirstRepDayEndPoint, dateGetParams)).get('repaymentDay')).replace('T', ' '));
        System.debug('Date_El');
        System.debug(EffectiveDate);
// End Callout EffectiveDate

// Deactivate Restructure/Top-up Event and Insert Resume
        //rejectedLME.IsActive__c = false;
        rejectedLME.Notes__c = 'whduljekklde';
        update rejectedLME;
        
        system.debug('rejectedLME >>>> '+rejectedLME);
        //System.enqueueJob(new AMP_Test(rejectedLME));
        
        /*
// Insert Resume Event
        Loan_Management_Event__c resumeLME = new Loan_Management_Event__c();
        resumeLME.Operation__c = operationId;
        resumeLME.Related_Event_Id__c = rejectedLME.Id;
        resumeLME.Event_Type__c = 'Resume';
        resumeLME.IsActive__c = true;
        resumeLME.Event_Date__c = Date.today();
        resumeLME.Effective_Date__c = EffectiveDate;
        resumeLME.IsApproved__c = true;
        resumeLME.ApprovedBy__c = UserInfo.getUserId();
        resumeLME.Approval_Date__c = Datetime.now();
        insert resumeLME;
        
        System.debug('resume_El');
        System.debug(resumeLME.Effective_Date__c);

// Update Loan Amounts
        Operation__c o = [SELECT Final_Repayment_Date__c, Actual_Interest_Amount__c, Actual_VAT_Amount__c, Loan_Outstanding_Interest__c, Loan_Outstanding_VAT_Amount__c,
                                Actual_Number_of_Repayments__c, Remaining_Number_of_Repayments__c, Status__c
                         FROM Operation__c WHERE Id = :operationId][0];
        o.Final_Repayment_Date__c = Date.valueOf(cr.LoanEndDate);
        o.Actual_Interest_Amount__c = cr.ActualTotalInterestAmount;
        o.Actual_VAT_Amount__c = cr.ActualTotalVATAmount;
        o.Loan_Outstanding_Interest__c = cr.InterestAmount;
        o.Loan_Outstanding_VAT_Amount__c = cr.InterestVATAmount;
        o.Actual_Number_of_Repayments__c = cr.ActualTotalRepaymentsNum;
        o.Remaining_Number_of_Repayments__c = cr.RepaymentsNum;
        o.Status__c = cr.LoanStatus;
        update o;
        System.debug('op_El');
        System.debug(o.Final_Repayment_Date__c);

*/
    }
}