src/objects/Loan_Ledger__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Ledgers</relationshipLabel>
        <relationshipName>Loan_Ledgers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreed_by_client__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Agreed by client</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BB_Amount__c</fullName>
        <label>BB_Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BB_Date__c</fullName>
        <label>BB_Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>BB_Num__c</fullName>
        <defaultValue>0</defaultValue>
        <label>BB_Num</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Borrowed_Amount__c</fullName>
        <label>Borrowed Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EventAmountAllocation1__c</fullName>
        <label>EventAmountAllocation1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EventAmountAllocation2__c</fullName>
        <label>EventAmountAllocation2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EventAmount__c</fullName>
        <label>EventAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EventEndDate__c</fullName>
        <label>EventEndDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EventLoanTerm__c</fullName>
        <label>EventLoanTerm</label>
        <picklist>
            <picklistValues>
                <fullName>03 (090 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 (120 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 (150 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 (180 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 (210 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 (240 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 (270 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 (365 days)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EventProcessMethod__c</fullName>
        <label>EventProcessMethod</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventStartDate__c</fullName>
        <label>EventStartDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LoanCharges__c</fullName>
        <label>LoanCharges</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LoanEndDate__c</fullName>
        <label>LoanEndDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LoanID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operation</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Loan Ledgers</relationshipLabel>
        <relationshipName>Loan_Ledgers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LoanStartDate__c</fullName>
        <label>LoanStartDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LoanVAT__c</fullName>
        <label>LoanVAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Move_to_Suspension__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Move to Suspension</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NewLoanEndDate__c</fullName>
        <label>NewLoanEndDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NewRepaymentAmountPerInstallment__c</fullName>
        <label>NewRepaymentAmountPerInstallment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NewTotalInterestAmount__c</fullName>
        <label>NewTotalInterestAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NewTotalPrincipalAmount__c</fullName>
        <label>NewTotalPrincipalAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NumAvailablePaymentHolidays__c</fullName>
        <label>NumAvailablePaymentHolidays</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Outstanding_Amount__c</fullName>
        <label>Outstanding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rules_Engine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rules Engine</label>
        <referenceTo>Loan_Management__c</referenceTo>
        <relationshipLabel>Loan Ledgers</relationshipLabel>
        <relationshipName>Loan_Ledgers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sign_Off_Date__c</fullName>
        <label>Sign Off Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disbursed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Loan Ledger</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_Management__c.object
<CustomObject>
    <fields>
        <fullName>Max_payment_holiday_duration__c</fullName>
        <label>Max payment holiday duration</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notification_days__c</fullName>
        <label>Notification days</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Repayment_method__c</fullName>
        <label>Repayment method</label>
        <picklist>
            <picklistValues>
                <fullName>Add to the end of the term</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Spread across existing term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add to the next day of the term</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rules Engine</label>
    <nameField>
        <displayFormat>LM-{000}</displayFormat>
        <label>Loan Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules Engines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted(Written-off)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disbursed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Disbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Topped-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <picklist>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>180</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>210</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>240</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>270</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>365</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Rules_Engine__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rules Engine</label>
        <type>Checkbox</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Loan_Overview_Controller.cls
public class Loan_Overview_Controller {
    
    public Boolean isSearchedProgramLedgers {get;set;}  
    public Boolean isLoanSelected {get;set;}    
    public List<Loan_Ledger__c> loanList {get;set;}
    public Loan_Ledger__c r {get;set;}
    public ID recID{get;set;}        
    public String selectedProgram {get;set;}
    
    public Loan_Overview_Controller(){      
        recID = ApexPages.currentPage().getParameters().get('id');
            if(recID !=null) {
                r = [SELECT Id,Name,Status__c, LoanID__c, LoanStartDate__c, LoanEndDate__c, Borrowed_Amount__c, 
                      Outstanding_Amount__c, NewLoanEndDate__c, NumAvailablePaymentHolidays__c, Rules_Engine__c,
                      Rules_Engine__r.Max_payment_holiday_duration__c, Rules_Engine__r.Notification_days__c,Move_to_Suspension__c,
                      NewTotalPrincipalAmount__c, NewTotalInterestAmount__c, LoanCharges__c, LoanVAT__c,
                      NewRepaymentAmountPerInstallment__c, Account__c, Sign_Off_Date__c,Agreed_by_client__c,
                      EventStartDate__c, EventEndDate__c, EventAmount__c, EventProcessMethod__c, EventLoanTerm__c,
             		  EventAmountAllocation1__c, EventAmountAllocation2__c,BB_Num__c,BB_Date__c,BB_Amount__c, Rules_Engine__r.Repayment_method__c,
                      Total_Amount__c,Program_Product_ASO__r.Program__c, Progress__c,
                     LoanID__r.Contract_Signed_Received_Date__c,LoanID__r.Loan_Amount__c,LoanID__r.Total_Amount_Repayable__c,
                     Program_Product_ASO__r.Product__r.Name, Program_Product_ASO__r.Program__r.CurrencyISOCode, Program_Product_ASO__r.Product__r.Schedule_Type__c,
                     Program_Product_ASO__r.Product__r.Interest_Type__c,Program_Product_ASO__r.Product__r.Term__c,
                     Program_Product_ASO__r.Product__r.Interest_Rate__c
                      FROM Loan_Ledger__c where id = :recID][0];
            isLoanSelected = true;
            }
    }
                
    public List<SelectOption> getProgramsWithLedger(){
        List<SelectOption> optns = new List<SelectOption>();
        Map <Id,String> progNameMap = new Map <Id,String>();
        
        List<Loan_Ledger__c> ledg = new List<Loan_Ledger__c>();
        ledg = [Select LoanID__r.Program_Product_ASO__r.Program__c, LoanID__r.Program_Product_ASO__r.Program__r.Name From Loan_Ledger__c Where  LoanID__r.Program_Product_ASO__c != null];
        Map<ID,String> programNameMap = new Map <ID,String>();
        
        for(Loan_Ledger__c tempLedger : ledg){
            programNameMap.put(tempLedger.LoanID__r.Program_Product_ASO__r.Program__c, tempLedger.LoanID__r.Program_Product_ASO__r.Program__r.Name);
            //optns.add(new SelectOption(tempLedger.LoanID__r.Program_Product_ASO__r.Program__c,tempLedger.LoanID__r.Program_Product_ASO__r.Program__r.Name));
        } 
        
        for(ID tempProgID : programNameMap.keySet()){
            optns.add(new SelectOption(tempProgID,programNameMap.get(tempProgID)));
        }
        
        return optns;
    }    
    public void getLedgerFromProgram (){
        
        isSearchedProgramLedgers = true;
        loanList = new List<Loan_Ledger__c>();
        
        		system.debug('selectedProgram:'+selectedProgram);
        
        loanList = [Select Id,Account__c,Account__r.Name,LoanEndDate__c,Outstanding_Amount__c,LoanID__c, LoanID__r.Name, LoanID__r.Status__c, LoanID__r.Loan_Disbursed_Date__c,
                    LoanID__r.Total_Amount_Repayable__c, Total_Amount_Per_Installment__c,BB_Num__c, Progress__c,Borrowed_Amount__c
                    From Loan_Ledger__c Where LoanID__r.Program_Product_ASO__c != '' And LoanID__r.Program_Product_ASO__r.Program__c = :selectedProgram 
                    And Status__c != 'Completed'];
    }  
    public PageReference cancel(){
        PageReference pr = new PageReference('/apex/Loan_Overview');
        pr.setRedirect(true);
        return pr;
    }
}