src/objects/Loan_Management__c.object
<CustomObject>
    <fields>
        <fullName>Notification_days__c</fullName>
        <label>Notification days</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <label>Program Product ASO</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipName>Loan_Management</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rules Engine</label>
    <nameField>
        <displayFormat>LM-{000}</displayFormat>
        <label>Loan Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules Engines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Management_Event__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ApprovedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Loan_Management_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Process_Method__c</fullName>
        <label>Event Process Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bounce Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waive Accummulated Fees</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Loan</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Loan Management Events</relationshipLabel>
        <relationshipName>Loan_Management_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Event_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Event Id</label>
        <referenceTo>Loan_Management_Event__c</referenceTo>
        <relationshipLabel>Loan Management Events</relationshipLabel>
        <relationshipName>Loan_Management_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan Management Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Management Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Actual_Interest_Amount__c</fullName>
        <label>Actual Interest Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_Number_of_Repayments__c</fullName>
        <label>Actual Number of Repayments</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_Repayment_Per_Installment__c</fullName>
        <label>Actual Repayment Per Installment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_VAT_Amount__c</fullName>
        <label>Actual VAT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_Repayment_Date__c</fullName>
        <label>Final Repayment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loan_Outstanding_Interest__c</fullName>
        <label>Loan Outstanding Interest</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Outstanding_VAT_Amount__c</fullName>
        <label>Loan Outstanding VAT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_Payment_Holidays__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Payment Holidays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remaining_Number_of_Repayments__c</fullName>
        <label>Remaining Number of Repayments</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted(Written-off)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disbursed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Disbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Topped-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LM_Resume.cls
/*public class LM_Resume {        
	@InvocableMethod(label='Create Resume Event' description='If TopUp/Restructure is rejected, insert LME Resume')
    public static void createResume(List<ID> opID){
        //calloutCalculateInsertResume(opID[0]);
        System.debug(opId[0]);
        System.enqueueJob(new LM_Resume_Test(opId[0]));
    }
}
*/
public class LM_Resume {

    public Operation__c o {get; set;}
    public Loan_Management__c rulesEngine {get; set;}
    public LM_CalculationResult cr {get; set;}
    private Date resumeDate {get; set;}
    private Date pauseDate {get; set;}
    private Loan_Management_Event__c resumeLME {get; set;}
    private Integer phNum {get; set;}
    
    public LM_Resume (Operation__c op, Loan_Management__c rules)
    {
        o = op;
        rulesEngine = rules;
    }
    
    public void ResumeLoan()
    {
        resumeDate = Date.today(); //Date.newInstance(2016, 12, 19);
        phNum = 0;
        
        String getParams = '?LoanId=' + o.Id + 
                    '&StartDate=' + CRMS_Util.DateToString(resumeDate, LMS_Constants.DATE_FORMAT_DWH) +
                    '&Days=' + String.valueOf(Integer.valueOf(rulesEngine.Notification_days__c) + 1) +
                    '&EventType=' + 'Resume'.replaceAll(' ', '%20');
        
        Date EffectiveDate = Date.valueOf(((string)LMS_Callout.GetResultsMapFromResponse(LMS_Callout.CallOutGET(LMS_Constants.FirstRepDayEndPoint, getParams)).get('repaymentDay')).replace('T', ' '));
    	
        CalloutCalculate();
        
        Loan_Management_Event__c rejectedLME = [SELECT Id, IsActive__c, Operation__r.Program_Product_ASO__c, Notes__c, Event_Date__c FROM Loan_Management_Event__c
                                              	WHERE Operation__c = :o.Id AND IsActive__c = :true AND Event_Type__c IN ('Restructure', 'Top-up')][0];
        pauseDate = rejectedLME.Event_Date__c;
        rejectedLME.IsActive__c = false;
        update rejectedLME;
            
        // Insert Resume Event
        resumeLME = new Loan_Management_Event__c();
        resumeLME.Operation__c = o.Id;
        resumeLME.Related_Event_Id__c = rejectedLME.Id;
        resumeLME.Event_Type__c = 'Resume';
        resumeLME.IsActive__c = true;
        resumeLME.Event_Date__c = resumeDate;
        resumeLME.Effective_Date__c = EffectiveDate; //rejectedLME.Event_Date__c > EffectiveDate ? rejectedLME.Event_Date__c : EffectiveDate;
        resumeLME.IsApproved__c = true;
        resumeLME.ApprovedBy__c = UserInfo.getUserId();
        resumeLME.Approval_Date__c = Datetime.now();
        insert resumeLME;
        
        DeactivateOngoingEvent();

		// Update Loan Amounts
        o.Final_Repayment_Date__c = Date.valueOf(cr.LoanEndDate);
        o.Actual_Interest_Amount__c = cr.ActualTotalInterestAmount;
        o.Actual_VAT_Amount__c = cr.ActualTotalVATAmount;
        o.Loan_Outstanding_Interest__c = cr.InterestAmount;
        o.Loan_Outstanding_VAT_Amount__c = cr.InterestVATAmount;
        o.Actual_Number_of_Repayments__c = cr.ActualTotalRepaymentsNum;
        o.Actual_Repayment_Per_Installment__c = cr.RepaymentPerInstallment;
        o.Remaining_Number_of_Repayments__c = cr.RepaymentsNum;
        o.Number_Payment_Holidays__c = o.Number_Payment_Holidays__c - phNum;
        o.Status__c = cr.LoanStatus;
        update o;    
    }
    
    private void DeactivateOngoingEvent()
    {
        List<Loan_Management_Event__c> ongoingLME = [SELECT Id, IsActive__c, Event_Type__c, Event_Date__c
                                               		 FROM Loan_Management_Event__c WHERE Operation__c = :o.Id AND Event_Type__c IN ('Payment Holiday', 'Change Collection Amount') 
                                                     	AND IsActive__c = :true AND Effective_Date__c > :pauseDate AND Effective_Date__c <= :resumeLME.Effective_Date__c];
        if(ongoingLME.size() > 0)
        {
            for(Loan_Management_Event__c lme :ongoingLME)
            {
                lme.IsActive__c = false;
                update lme;
                
                if (lme.Event_Type__c == 'Payment Holiday')
                    phNum++;
                
                Loan_Management_Event__c cancelLME = new Loan_Management_Event__c();
                cancelLME.Operation__c = o.Id;
                cancelLME.Related_Event_Id__c = lme.Id;
                cancelLME.Event_Type__c = 'Cancel ' + lme.Event_Type__c;
                cancelLME.Event_Process_Method__c = 'Auto';
                cancelLME.IsActive__c = true;
                cancelLME.Event_Date__c = resumeDate;
                cancelLME.Effective_Date__c = resumeDate;
                cancelLME.IsApproved__c = true;
                cancelLME.ApprovedBy__c = UserInfo.getUserId();
                cancelLME.Approval_Date__c = Datetime.now();
                insert cancelLME;                
            }
        }
    }
    
    private void CalloutCalculate()
    {
       	String getParamsCalc = '?LoanId=' + o.Id +
                            '&EventType=' + 'Resume'.replaceAll(' ', '%20') +
                            '&EventStartDate=' + CRMS_Util.DateToString(resumeDate, LMS_Constants.DATE_FORMAT_DWH) +
                            '&EventEndDate=&EventAmount=&LoanTerm=&EventProcessMethod=&PaymentReceived=&PrincipalAllocation=&InterestAllocation=';
        
        string calculateResponse = LMS_Callout.CallOutGET(LMS_Constants.endpointValue, getParamsCalc);
        processResponse(calculateResponse);
    }
    
    public void processResponse(string response)
    {
        if(response == null)
       	{
           ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Http request failed');
           ApexPages.addMessage(myMsg);
           return;
       	}
                
        Map<String, Object> responseMap =  (Map<String, Object>)JSON.deserializeUntyped(response); 
        List<Object> responseResultsList = (List<Object>)responseMap.get('results');
        
        if (responseResultsList == null)
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'The calculation request failed');
           	ApexPages.addMessage(myMsg);
           	return;
        }
        
        Map<String, Object> resultsMap = (Map<String, Object>)responseResultsList[0];          
        
        String responseResultJSON = JSON.serialize(responseMap.get('results'));
        cr = ((List<LM_CalculationResult>)JSON.deserialize(responseResultJSON, List<LM_CalculationResult>.class))[0];
           
        if(cr.Result == 'Error')
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, cr.Reason);
            ApexPages.addMessage(myMsg);       
            
        }
    }
}