src/objects/Loan_Management__c.object
<CustomObject>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <label>Program Product ASO</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipName>Loan_Management</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Repayment_method__c</fullName>
        <label>Repayment method</label>
        <picklist>
            <picklistValues>
                <fullName>Add to the end of the term</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Spread across existing term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add to the next day of the term</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rules Engine</label>
    <nameField>
        <displayFormat>LM-{000}</displayFormat>
        <label>Loan Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules Engines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Management_Event__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ApprovedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Loan_Management_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Amount__c</fullName>
        <label>Event Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_End_Date__c</fullName>
        <label>Event End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Loan_Term__c</fullName>
        <label>Event Loan Term</label>
        <picklist>
            <picklistValues>
                <fullName>01 (30 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03 (090 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 (120 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 (150 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 (180 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 (210 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 (240 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 (270 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 (365 days)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Process_Method__c</fullName>
        <label>Event Process Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bounce Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waive Accummulated Fees</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest_Allocation__c</fullName>
        <label>Interest Allocation</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Loan</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Loan Management Events</relationshipLabel>
        <relationshipName>Loan_Management_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Principal_Allocation__c</fullName>
        <label>Principal Allocation</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Waive_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waive Fee</label>
        <type>Checkbox</type>
    </fields>
    <label>Loan Management Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Management Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Actual_Interest_Amount__c</fullName>
        <label>Actual Interest Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_Number_of_Repayments__c</fullName>
        <label>Actual Number of Repayments</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_Repayment_Per_Installment__c</fullName>
        <label>Actual Repayment Per Installment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_VAT_Amount__c</fullName>
        <label>Actual VAT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_Repayment_Date__c</fullName>
        <label>Final Repayment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loan_Outstanding_Interest__c</fullName>
        <label>Loan Outstanding Interest</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Outstanding_Principal__c</fullName>
        <label>Loan Outstanding Principal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outstanding_Fees_VAT__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Outstanding Fees VAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outstanding_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Outstanding Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remaining_Number_of_Repayments__c</fullName>
        <label>Remaining Number of Repayments</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AMPLoan_ProcessBounceBack.cls
public class AMPLoan_ProcessBounceBack implements Database.Batchable<SObject>, Database.AllowsCallouts{
	
	private LM_CalculationResult cr;
		
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([Select Id,
        										Waive_Fee__c, 
        										Principal_Allocation__c, 
        										Payment_Received__c, 
        										Operation__c, 
        										Name, 
        										IsApproved__c, 
        										IsActive__c,        										 
        										Event_Type__c, 
        										Event_Process_Method__c, 
        										Event_Loan_Term__c, 
        										Event_End_Date__c, 
        										Event_Date__c, 
        										Event_Amount__c, 
        										Effective_Date__c, 
        										ApprovedBy__c, 
        										Approval_Date__c, 
	        									Operation__r.Program_Product_ASO__c
                                         	From Loan_Management_Event__c
                                        	Where Event_Type__c = 'Bounce Back' 
                                         	And IsApproved__c = false
                                         	And DAY_ONLY(CreatedDate) <: Date.today()                                      	
                                        ]);
    }

    public void execute(Database.BatchableContext BC, list<Loan_Management_Event__c> LoanEvents){
              
        if(LoanEvents.size() > 0 && !LoanEvents.isEmpty()){
            list<ID> ProgramProducts = new list<ID>();
            list<ID> RelatedOperationIds = new list<ID>();
            list<Operation__c> LoantoUpdate = new list<Operation__c>();
            list<Loan_Management_Event__c> LoanEventsList = new list<Loan_Management_Event__c>();
            
                                    
            for(Loan_Management_Event__c LME : LoanEvents){
            	ProgramProducts.add(LME.Operation__r.Program_Product_ASO__c);
            	RelatedOperationIds.add(LME.Operation__c);
            }
            
            map<ID, Loan_Management__c> RuleEngineMap = RepaymentMethod(ProgramProducts);
            map<ID, Operation__c> RelatedOperations = LoanDetail(RelatedOperationIds);
            
            
            for(Loan_Management_Event__c LoanEvent : LoanEvents){               
                
                if(RuleEngineMap.size() > 0 && !RuleEngineMap.isEmpty())
                	LoanEvent.Event_Process_Method__c = RuleEngineMap.get(LoanEvent.Operation__r.Program_Product_ASO__c).Repayment_method__c;
                                                
                if(Calculate(LoanEvent)){
                	Operation__c Loan = RelatedOperations.get(LoanEvent.Operation__c);
                	
                	LoanEvent.IsApproved__c = true;
			        LoanEvent.ApprovedBy__c = UserInfo.getUserId();
			        LoanEvent.Approval_Date__c = Datetime.now();
			       	
			       	LoanEventsList.add(LoanEvent);
			       			                
			        Loan.Outstanding_Fees__c = cr.AccFeesAmount + cr.EventFeeAmount;
			        Loan.Outstanding_Fees_VAT__c = cr.AccFeesVatAmount + cr.EventFeeVATAmount;
			        Loan.Final_Repayment_Date__c = Date.valueOf(cr.LoanEndDate);
			        Loan.Actual_Interest_Amount__c = cr.ActualTotalInterestAmount;
			        Loan.Actual_VAT_Amount__c = cr.ActualTotalVATAmount;
			        Loan.Loan_Outstanding_Interest__c = cr.InterestAmount;
			        Loan.Loan_Outstanding_Principal__c = cr.PrincipalAmount;
			        Loan.Actual_Number_of_Repayments__c = cr.ActualTotalRepaymentsNum;
			        Loan.Remaining_Number_of_Repayments__c = cr.RepaymentsNum;
			        Loan.Actual_Repayment_Per_Installment__c = cr.RepaymentPerInstallment;            
			        LoantoUpdate.add(Loan);                	
                }                                                           
            }
            
            if(LoanEventsList.size() > 0 && !LoanEventsList.isEmpty())
            	Database.update(LoanEvents);
            if(LoantoUpdate.size() > 0 && !LoantoUpdate.isEmpty())
            	Database.update(LoantoUpdate);            
        }        
    }
    
    private map<ID, Loan_Management__c> RepaymentMethod(list<ID> ProgramProductsList){
    	map<ID, Loan_Management__c> RuleEngineMap = new map<ID, Loan_Management__c>();
    	for(Loan_Management__c RE : [Select Id, 
    									Program_Product_ASO__c, 
    									Repayment_method__c 
    								From Loan_Management__c 
    								Where Program_Product_ASO__c IN:ProgramProductsList]){
    		RuleEngineMap.put(RE.Program_Product_ASO__c, RE);    									
    	}
    	return RuleEngineMap;
    }
    
    private map<ID, Operation__c> LoanDetail(list<ID> LMEOperations){
    	map<ID, Operation__c> Operations = new map<ID, Operation__c>([Select Id,
				    Outstanding_Fees__c, 
				    Outstanding_Fees_VAT__c, 
				    Final_Repayment_Date__c,
				    Actual_Interest_Amount__c,
				    Actual_VAT_Amount__c,
				    Loan_Outstanding_Interest__c,
				    Loan_Outstanding_Principal__c,
				    Actual_Number_of_Repayments__c,
				    Remaining_Number_of_Repayments__c,
				    Actual_Repayment_Per_Installment__c
			    From Operation__c Where Id IN : LMEOperations]);
		return Operations;
    }
    
    private boolean Calculate(Loan_Management_Event__c lme){
    	                
        String getParams = '?LoanId=' + lme.Operation__c +
            '&EventType=' + lme.Event_Type__c.replaceAll(' ', '%20') +
            '&EventStartDate=' + CRMS_Util.DateToString(lme.Event_Date__c, LMS_Constants.DATE_FORMAT_DWH) +
            '&EventEndDate=' + CRMS_Util.DateToString(lme.Event_End_Date__c, LMS_Constants.DATE_FORMAT_DWH) +
            '&EventAmount=' + lme.Event_Amount__c +
            '&LoanTerm=' + (lme.Event_Loan_Term__c == null ? '' : lme.Event_Loan_Term__c.substring(4, 7).replaceAll(' ', '')) +
            '&EventProcessMethod=' + (lme.Event_Process_Method__c == null ? '' : lme.Event_Process_Method__c.replaceAll(' ', '%20')) +
            '&PaymentReceived=' + lme.Payment_Received__c +
            '&PrincipalAllocation=' + lme.Principal_Allocation__c +
            '&InterestAllocation=' + lme.Interest_Allocation__c +
            '&WaiveFee=' + lme.Waive_Fee__c;  
         
        string calculateResponse = LMS_Callout.CallOutGET(LMS_Constants.endpointValue, getParams);
        return processResponse(calculateResponse, lme);        
    }
    
    private boolean processResponse(string response, Loan_Management_Event__c LoanEvent){
    	
        if(response == null){           
           return false;
        }
        
        list<LMS_CalculationFieldDescriptor> lstCalculationResultValues = new list<LMS_CalculationFieldDescriptor>();
        
        Map<String, Object> responseMap =  (Map<String, Object>)JSON.deserializeUntyped(response); 
        List<Object> responseResultsList = (List<Object>)responseMap.get('results');
        
        if (responseResultsList == null){            
            return false;
        }
        
        Map<String, Object> resultsMap = (Map<String, Object>)responseResultsList[0];          
        
        String responseResultJSON = JSON.serialize(responseMap.get('results'));
        cr = ((List<LM_CalculationResult>)JSON.deserialize(responseResultJSON, List<LM_CalculationResult>.class))[0];
        cr.lme = LoanEvent;
        if(cr.Result == 'Error'){
        	return false;
        }
        return true;
    }
    
    public void finish(Database.BatchableContext BC){}
}