src/objects/Loan_Management_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_End_Date__c</fullName>
        <label>Event End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bounce Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waive Accummulated Fees</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Loan</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Loan Management Events</relationshipLabel>
        <relationshipName>Loan_Management_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Event_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Event Id</label>
        <referenceTo>Loan_Management_Event__c</referenceTo>
        <relationshipLabel>Loan Management Events</relationshipLabel>
        <relationshipName>Loan_Management_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan Management Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Management Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Principal Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Disbursed_Date__c</fullName>
        <label>To Be Disbursed On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loan_Outstanding_Principal__c</fullName>
        <label>Loan Outstanding Principal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted(Written-off)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disbursed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Disbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Topped-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>PPAS</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Loan_Management_Rev_Controller.cls
public class Loan_Management_Rev_Controller {
    
    public string selectedProgram { get; set; }
    public string selectedStatus { get; set; }
    
    public integer totalRecs { get; set; }
    public integer OffsetSize { get; set; }
    public integer LimitSize { get; set; }
    
    public string sortColumn { get; set;}
    public string prevSortColumn { get; set; }
    public string sortOrder { get; set; }
    
    public Id selectedId { get; set; }
    public string SearchText    {get; set;}
        
    public Loan_Management_Rev_Controller(ApexPages.StandardController stdController)
    {
        selectedProgram = 'All';
        selectedStatus = 'All';
        
        totalRecs = 0;
        OffsetSize = 0;
        LimitSize = 20;
        
        sortColumn = 'Id';
        prevSortColumn = 'Id';
        sortOrder = 'ASC';
                
    }
    
    public List<SelectOption> getPrograms()
    {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('All', 'All'));
        
        List<Program__c> programs = [Select Id, Name from Program__c Order By Name];
        
        for (Program__c pr : programs)
        {
            options.add(new SelectOption(pr.Id, pr.Name));
        }
        
        return options;
    }
    
    public List<SelectOption> getStatuses()
    {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('All', 'All'));
        
        Schema.DescribeFieldResult fieldResult = Operation__c.Status__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for(Schema.PicklistEntry e : ple)
        {
            options.add(new SelectOption(e.getValue(), e.getLabel()));
        }
        
        return options;
    }
    
    public void FindOperationsByClient(){
        totalRecs = 0;
        OffsetSize = 0;
        LimitSize = 20;
    }
    
    public List<Operation__c> getOperations()
    {
        string SearchString = '';
        List<Operation__c> operations = new List<Operation__c>();
        string strQuery = 'select id, name, Account__r.Name, Loan_Amount__c, Loan_Outstanding_Principal__c, Loan_Disbursed_Date__c, Status__c, ';
        strQuery += '(select Id, Event_Type__c from Loan_Management_Events__r where (Event_Type__c = \'Change Collection Amount\' and IsActive__c = true and Event_Date__c <= TODAY and (Event_End_Date__c >= TODAY or Event_End_Date__c = null))';
        strQuery += ' OR (Event_Type__c = \'Payment Holiday\' and Event_Date__c <= TODAY and Event_End_Date__c >= TODAY and IsActive__c = true )) ';
        strQuery += ' from Operation__c where Id != null';
        string strCountQuery = 'select count() from Operation__c where Id != null';
                
        if (selectedProgram != 'All')
        {
            strQuery = strQuery + ' and Program_Product_ASO__c in (select id from Program_Product_ASO__c where Program__c =:selectedProgram)';
            strCountQuery = strCountQuery + ' and Program_Product_ASO__c in (select id from Program_Product_ASO__c where Program__c =:selectedProgram)';
        } 

        if (selectedStatus != 'All')
        {
            strQuery = strQuery + ' and Status__c =:selectedStatus';
            strCountQuery = strCountQuery + ' and Status__c =:selectedStatus';
        }
        
        if(SearchText != null && SearchText.trim() != ''){
            SearchText = string.escapeSingleQuotes(EncodingUtil.urlDecode(SearchText, 'UTF-8'));
            SearchString =  '%'+SearchText+'%'; 
            system.debug('SearchString :: '+SearchString);
            strQuery = strQuery + ' AND Account__r.Name LIKE : SearchString';
            strCountQuery = strCountQuery + ' AND Account__r.Name LIKE : SearchString';
        }
        
        totalRecs = Database.countQuery(strCountQuery);
                
        strQuery = strQuery + ' ORDER BY ' + sortColumn + ' ' + sortOrder + ' NULLS ' + (sortOrder == 'ASC' ? 'FIRST' : 'LAST');
        strQuery = strQuery + ' LIMIT :LimitSize OFFSET :OffsetSize';
        system.debug('strQuery :: '+strQuery);        
        operations = Database.query(strQuery);        
        
        prevSortColumn = sortColumn;
        
        return operations;
    }
    
    public void FirstPage()
    {
        OffsetSize = 0;
    }
    
    public void previous()
    {
        OffsetSize = OffsetSize - LimitSize;
    }
    
    public void next()
    {
        OffsetSize = OffsetSize + LimitSize;
    }
    
    public void LastPage()
    {
        OffsetSize = totalrecs - math.mod(totalRecs, LimitSize);
    } 
    
    public void sortOrder()
    {
        if (sortColumn == prevSortColumn && sortOrder == 'ASC')
            sortOrder = 'DESC';        
        else
            sortOrder = 'ASC';
        
    }
    
}