src/objects/Loan_Management__c.object
<CustomObject>
    <fields>
        <fullName>Action1__c</fullName>
        <label>Action1</label>
        <picklist>
            <picklistValues>
                <fullName>Refer case</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Move to Restructure</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Action2__c</fullName>
        <label>Action2</label>
        <picklist>
            <picklistValues>
                <fullName>Refer case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move to Restructure</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Action3__c</fullName>
        <label>Action3</label>
        <picklist>
            <picklistValues>
                <fullName>Refer case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move to Restructure</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Allow_Cancellation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow_Cancellation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assigned_to1__c</fullName>
        <label>Assigned to1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_to2__c</fullName>
        <label>Assigned to2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_to3__c</fullName>
        <label>Assigned to3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancellation_Period__c</fullName>
        <label>Cancellation Period</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charges_waiver__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Charges waiver</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Documentary_Stamp_Tax__c</fullName>
        <label>Documentary Stamp Tax</label>
        <precision>12</precision>
        <scale>9</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Cancellation_Amount__c</fullName>
        <label>Loan Cancellation Amount</label>
        <precision>12</precision>
        <scale>9</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Cancellation_Minimum__c</fullName>
        <label>Loan Cancellation Minimum</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Early_Payoff_Amount__c</fullName>
        <label>Loan Early Payoff Amount</label>
        <precision>12</precision>
        <scale>9</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Early_Payoff_Minimum__c</fullName>
        <label>Loan Early Payoff Minimum</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Restructure_Amount__c</fullName>
        <label>Loan Restructure Amount</label>
        <precision>12</precision>
        <scale>9</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Restructure_Minimum__c</fullName>
        <label>Loan Restructure Minimum</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Manual_Repayment_Handling_Fixed__c</fullName>
        <label>Manual Repayment Handling Fixed</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_principal_repaid__c</fullName>
        <label>Min principal repaid</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Num_of_Bounce_Backs2__c</fullName>
        <label>Num of Bounce Backs2</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Num_of_Bounce_Backs3__c</fullName>
        <label>Num of Bounce Backs3</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Num_of_Bounce_Backs__c</fullName>
        <label>Num of Bounce Backs1</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Origination_Fee_Amount__c</fullName>
        <label>Origination Fee Amount</label>
        <precision>12</precision>
        <scale>9</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Origination_Fee_Minimum__c</fullName>
        <label>Origination Fee Minimum</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Program_Product_ASO__r.Product__r.Product_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <label>Program Product ASO</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipName>Loan_Management</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Program_Product_ASO__r.Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repayment_method__c</fullName>
        <label>Repayment method</label>
        <picklist>
            <picklistValues>
                <fullName>Add to the end of the term</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Spread across existing term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add to the next day of the term</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reversal_Fee_Fixed__c</fullName>
        <label>Reversal Fee Fixed</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Second_Level_Limit__c</fullName>
        <label>Second Level Limit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Second_Person_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Second Person Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Top_ups__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Top-ups</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value_Added_Tax__c</fullName>
        <label>Value Added Tax</label>
        <precision>12</precision>
        <scale>9</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wire_Transfer_Handling_Fee_Fixed__c</fullName>
        <label>Wire Transfer Handling Fee Fixed</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Rules Engine</label>
    <nameField>
        <displayFormat>LM-{000}</displayFormat>
        <label>Loan Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules Engines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Program__c</field>
                <operation>equals</operation>
                <valueField>Program_Product_ASO__c.Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program_Product_ASO__c.Rules_Engine__c</field>
                <operation>notEqual</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>contains</operation>
                <valueField>Program__c.Country_Mapping__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Loan</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>PPAS</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Loan_RulesEngine_Controller.cls
public class Loan_RulesEngine_Controller {
    
    public ID recID {get;set;}
    public List<Loan_Management__c> rList {get;set;}
    public Loan_Management__c r {get;set;}
    public Program_Product_ASO__c rec {get;set;}
    public Map<id,string> PPASCurrency {get;set;}
    public boolean disableAssociationDropdown {get;set;}
    public string BounceBack1    {get;set;}
    public string BounceBack2    {get;set;}
    public string BounceBack3    {get;set;}
    
    public boolean isNewOrEditRecord {get; set;}
    public boolean flagNoOpportunityExist   {get; set;}{
        flagNoOpportunityExist = false;
    }
    
    public String selectedRolesVal1{get;set;}   
    public String selectedRolesVal2{get;set;}    
    public String selectedRolesVal3{get;set;}

    public String selectedProgramVal{get;set;}      
    public String selectedPPVal{get;set;}
    public String currencyISO {get;set;}    
    Map<ID,String> programCurrencyCodeMap; 
    
 public Loan_RulesEngine_Controller (ApexPages.StandardController stdController) {
        
        if(PPASCurrency==null)  PPASCurrency = new Map<ID,String>();
        if (programCurrencyCodeMap==null) programCurrencyCodeMap = new Map<ID,String>();
     
        rList = new List<Loan_Management__c>();
     
        r = new Loan_Management__c();
    
        recID = ApexPages.currentPage().getParameters().get('id');
        if(recID == null)
            this.rec = (Program_Product_ASO__c)stdController.getRecord();
        
        else
        {
            this.rec = [SELECT Id, Program__c,Program__r.CurrencyISOCode, Product__c, Product__r.Product_Type__c
                        FROM Program_Product_ASO__c Where id = :recID][0];
            
            rList = [SELECT Id, Name, Program_Product_ASO__r.Program__r.CurrencyISOCode, LastModifiedDate, LastModifiedById, Repayment_method__c, 
                          Action1__c, Action2__c, Action3__c, Num_of_Bounce_Backs__c, Num_of_Bounce_Backs2__c, Num_of_Bounce_Backs3__c, Assigned_to1__c, Assigned_to2__c, Assigned_to3__c, 
                          Charges_waiver__c, Top_ups__c, Min_principal_repaid__c, Second_Person_Approval__c, Second_Level_Limit__c, Allow_Cancellation__c, Cancellation_Period__c,
                          Documentary_Stamp_Tax__c, Loan_Cancellation_Amount__c, Loan_Cancellation_Minimum__c, Loan_Early_Payoff_Amount__c, Loan_Early_Payoff_Minimum__c, 
                          Loan_Restructure_Amount__c, Loan_Restructure_Minimum__c, Manual_Repayment_Handling_Fixed__c, Origination_Fee_Amount__c, Origination_Fee_Minimum__c, 
                          Reversal_Fee_Fixed__c, Value_Added_Tax__c, Wire_Transfer_Handling_Fee_Fixed__c, Funding_Pool__c, Second_Level_Signatory__c,  Program_Product_ASO__c,
                          Program_Product_ASO__r.Program__c, Program_Product_ASO__r.Program__r.Name, Completion_Days__c,
                          Grace_period__c, Notification_days__c, Max_number_of_payment_holidays__c, Max_payment_holiday_duration__c, Minimum_of_principal_repaid__c,
                          Origination_Fee_Fixed__c, Wire_Transfer_Handling_Fee_Amount__c, Wire_Transfer_Handling_Fee_Minimum__c, Loan_Cancellation_Fixed__c, 
                          Loan_Early_Payoff_Fixed__c, Loan_Restructure_Fixed__c, Reversal_Fee_Amount__c, Reversal_Fee_Minimum__c, Manual_Repayment_Handling_Amount__c, 
                          Manual_Repayment_Handling_Minimum__c, Fee_payment_method__c,CreatedById,CreatedDate
                     FROM Loan_Management__c where Program_Product_ASO__c = :recID];
            if(!rList.isEmpty()){
                r = rList[0];
                BounceBack1 = r.Num_of_Bounce_Backs__c; 
                BounceBack2 = r.Num_of_Bounce_Backs2__c; 
                BounceBack3 = r.Num_of_Bounce_Backs3__c; 
            }
            currencyISO = rec.Program__r.CurrencyISOCode;
            selectedProgramVal = rec.Program__c;
            selectedPPVal = rec.id;
            
            if([select Id from Opportunity where Program_Product_ASO__c =:recID].size() > 0 || 
               [select Id from Operation__c where Program_Product_ASO__c =:recID].size() > 0){
            	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'There are loans in the system assigned to this rule. Changes on this page, will affect their loan behavior and fee calculation.'));
                flagNoOpportunityExist = false;     
            }else flagNoOpportunityExist = true;
            
            isNewOrEditRecord=true;
        }
     
     disableAssociationDropdown = (selectedPPVal != null);
     selectedRolesVal1 = r.Assigned_to1__c; selectedRolesVal2 = r.Assigned_to2__c ; selectedRolesVal3 = r.Assigned_to3__c;
 }
    
    public void RefreshBounceBackList(){
        integer index = this.ProfileIndex();
        if(BounceBack1 != NULL && BounceBack1 != 'None'){
            r.Action1__c = 'Refer case';            
            selectedRolesVal1 = this.getProfiles()[index].getValue();
        }else {
            r.Action1__c = null;
            selectedRolesVal1 = this.getProfiles()[0].getValue();
        }
        if(BounceBack2 != NULL && BounceBack2 != 'None'){
            r.Action2__c = 'Refer case';
            selectedRolesVal2 = this.getProfiles()[index].getValue();
        }else {
            r.Action2__c = null;
            selectedRolesVal2 = this.getProfiles()[0].getValue();
        }
        if(BounceBack3 != NULL && BounceBack3 != 'None'){
            r.Action3__c = 'Refer case';
            selectedRolesVal3 = this.getProfiles()[index].getValue();
        }else {
            r.Action3__c = null;
            selectedRolesVal3 = this.getProfiles()[0].getValue();
        }
        
        //system.debug('BounceBack1 :: '+BounceBack1);
        //system.debug('BounceBack2 :: '+BounceBack2);
        //system.debug('BounceBack3 :: '+BounceBack3);
    }
    
    private integer ProfileIndex(){
       
        if(currencyISO == 'HKD'){
            return 15;
        }else if(currencyISO == 'PHP'){
            return 16;
        }else if(currencyISO == 'SGD'){
            return 17;
        }else if(currencyISO == 'GBP'){
            return 18;
        }
        return 0;
    }
    
    public list<SelectOption> getBounceBacks1(){
        list<SelectOption> BounceBackList = new list<SelectOption>();
        BounceBackList.add(new SelectOption('None', '--None--'));
        for(integer i=1; i<=10; i++){        
            if(BounceBack2 == string.valueOf(i) || BounceBack3 == string.valueOf(i)) continue;      
            BounceBackList.add(new SelectOption(string.valueOf(i),string.valueOf(i)));
        }        
        return BounceBackList;       
    }
    
    public list<SelectOption> getBounceBacks2(){
        list<SelectOption> BounceBackList = new list<SelectOption>();
        BounceBackList.add(new SelectOption('None', '--None--'));
        for(integer i=1; i<=10; i++){        
            if(BounceBack1 == string.valueOf(i) || BounceBack3 == string.valueOf(i)) continue;      
            BounceBackList.add(new SelectOption(string.valueOf(i),string.valueOf(i)));
        }               
        return BounceBackList;
    }
    
    public list<SelectOption> getBounceBacks3(){
        list<SelectOption> BounceBackList = new list<SelectOption>();
        BounceBackList.add(new SelectOption('None', '--None--'));
        for(integer i=1; i<=10; i++){
            if(BounceBack1 == string.valueOf(i) || BounceBack2 == string.valueOf(i)) continue;      
            BounceBackList.add(new SelectOption(string.valueOf(i),string.valueOf(i)));
        }        
        return BounceBackList;
    }
    
    public List<SelectOption> getPrograms(){
        List<SelectOption> optns = new List<SelectOption>();
        Set<ID> addedPrograms = new Set<ID>();
        List<Program_Product_ASO__c> ppList = new List<Program_Product_ASO__c>();
        
        if (disableAssociationDropdown) //rules engine already created
            optns.add(new SelectOption(r.Program_Product_ASO__r.Program__c, r.Program_Product_ASO__r.Program__r.Name));
        else
        {
            ppList = [Select Program__c,Program__r.Name,Program__r.CurrencyISOCode From Program_Product_ASO__c Where Rules_Engine__c = false Order By Program__r.Name];
            optns.add(new selectOption('', '--None--' ));
            for(Program_Product_ASO__c p : ppList){
                if(!addedPrograms.contains(p.Program__c)){                 
                    programCurrencyCodeMap.put(p.Program__c, p.Program__r.CurrencyISOCode);  
                    optns.add(new selectOption(p.Program__c, p.Program__r.Name));
                    addedPrograms.add(p.Program__c);
                }
            } 
        }
        return optns;
    }    
    public List<SelectOption> getProducts(){
        //currencyISO = programCurrencyCodeMap.get(selectedProgramVal);
        if(!disableAssociationDropdown)
            if(selectedProgramVal != null && selectedProgramVal != 'null' && selectedProgramVal != '')
                currencyISO = programCurrencyCodeMap.get(selectedProgramVal);
            else 
                currencyISO = '';
                
        List<SelectOption> optns = new List<SelectOption>();
        List<Program_Product_ASO__c> ppList = new List<Program_Product_ASO__c>();
        ppList = [Select Id,Product__r.Name 
                  From Program_Product_ASO__c 
                  Where Program__c = :selectedProgramVal And Rules_Engine__c = false
                  Order By Product__r.Name];
        if(disableAssociationDropdown== true) {
            ppList = [Select Id,Product__r.Name 
                  From Program_Product_ASO__c 
                  Where ID =: selectedPPVal];
        }
        optns.add(new selectOption('', '--None--' ));
                
        for(Program_Product_ASO__c p : ppList){
           optns.add(new selectOption(p.ID, p.Product__r.Name));
        } 
        
        return optns;
    }
    

    public List<SelectOption> getProfiles(){
        List<SelectOption> optns = new List<SelectOption>();
        List<Profile> profList = new List<Profile>();
        profList = [Select id, Name from Profile Order By Name];  
            optns.add(new selectOption('', '--None--'));
         for(Profile p : profList){
            optns.add(new selectOption(p.ID, p.Name));
        }       
        
        return optns;
    }
        
    public PageReference newRec()
    {
        isNewOrEditRecord = true;
        return null;
    }
     public PageReference refresh()
    {
       // system.debug(logLevel, 'selectedProductVal:' + selectedProductVal);
        //system.debug(logLevel, 'productIDandTypeMap.get(selectedProductVal):' + productIDandTypeMap.get(selectedProductVal));
        return null;
    }  
    
    public PageReference newRecord()
    {   
        r.Assigned_to1__c = selectedRolesVal1; r.Assigned_to2__c = selectedRolesVal2; r.Assigned_to3__c = selectedRolesVal3;
        r.Num_of_Bounce_Backs__c = BounceBack1; 
        r.Num_of_Bounce_Backs2__c = BounceBack2; 
        r.Num_of_Bounce_Backs3__c = BounceBack3;        
                       
        if(rec.id == null) {
            
            rec.id = selectedPPVal;          
            disableAssociationDropdown= true;
            r.CurrencyIsoCode = rec.Program__r.CurrencyISOCode;
        } 
                    
        if(r.Program_Product_ASO__c == null) r.Program_Product_ASO__c = rec.id;
        upsert r; 
        
        rec.Rules_Engine__c = true;
        update rec;
        
        Pagereference pr = new Pagereference('/apex/Loan_RulesEngine');
        pr.setRedirect(true);
        return pr;
    }    
    public PageReference deleteRecord () {
        
        delete r; 
        
        rec.Rules_Engine__c = false;
        update rec;
        
        Pagereference pr = new Pagereference('/apex/Loan_RulesEngine');
        pr.setRedirect(true);
        return pr;
    }    
    public PageReference cancel () {
        Pagereference pr = new Pagereference('/apex/Loan_RulesEngine');
        pr.setRedirect(true);
        return pr;
    }
}