src/objects/Loan_Management_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Amount__c</fullName>
        <label>Event Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bounce Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waive Accummulated Fees</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Waive_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waive Fee</label>
        <type>Checkbox</type>
    </fields>
    <label>Loan Management Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Management Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Full_Term__c</fullName>
        <label>Full_Term</label>
        <picklist>
            <picklistValues>
                <fullName>03 (090 days)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>04 (120 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 (150 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 (180 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 (210 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 (240 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 (270 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 (365 days)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <defaultValue>$Setup.IR__c.Annual_UK__c</defaultValue>
        <label>Interest Rate</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <label>Schedule Type</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LM_CalculationResult.cls
public class LM_CalculationResult 
{
    public Loan_Management_Event__c lme  { get; set; }
    public Program_Product_ASO__c PPASO { get; set; }
    
    public decimal AccFeesAmount { get; set;}
    public decimal InterestVATAmount { get; set; }
    public decimal AccFeesVatAmount { get; set; }
    public decimal EventFeeAmount { get; set; }
    public decimal EventFeeVATAmount { get; set; }
    public DateTime LoanEndDate { get; set; }
    public decimal InterestAmount { get; set; }
    public decimal PrincipalAmount { get; set; }
    public Id ProgramProductSFId 
    { 
        get; 
        set
        {
            ProgramProductSFId = value;
            if (ProgramProductSFId != null)
            	PPASO = [SELECT Product__r.Full_Term__c, Product__r.Schedule_Type__c, Product__r.Interest_Rate__c
                        FROM Program_Product_ASO__c 
                        WHERE Id =: this.ProgramProductSFId][0];
        }
    }
    public String Reason { get; set; }
    public String Result { get; set; }
    public decimal ActualTotalInterestAmount { get; set; }
    public decimal ActualTotalVATAmount { get; set; }
    public integer ActualTotalRepaymentsNum { get; set; }
    public integer RepaymentsNum { get; set; }
    public decimal RepaymentPerInstallment { get; set; }
    public String LoanStatus { get; set; }
    
    public string EventFeeAmountWithVAT
    {
        get
        {
            return CRMS_Util.DecimalToString(EventFeeAmount + EventFeeVATAmount) + ' (incl. VAT ' + CRMS_Util.DecimalToString(EventFeeVATAmount) + ')';
        }        
    }
    
    public string AccFeesAmountWithVAT
    {
        get
        {
            return CRMS_Util.DecimalToString(AccFeesAmount + AccFeesVatAmount) + ' (incl. VAT ' + CRMS_Util.DecimalToString(AccFeesVatAmount) + ')';
        }
    }
    
    public decimal TotalAmountNoInterest
    {
        get
        {
            return (PrincipalAmount != null ? PrincipalAmount : 0) + 
                	(lme.Event_Type__c == 'Top-up' ? lme.Event_Amount__c : 0) +
                			(AccFeesAmount != null ? AccFeesAmount : 0) +
                			(AccFeesVATAmount != null ? AccFeesVATAmount : 0) +
                			(lme.Waive_Fee__c ? 0 : (EventFeeAmount != null ? EventFeeAmount : 0)) +
                			(lme.Waive_Fee__c ? 0 : (EventFeeVATAmount != null ? EventFeeVATAmount : 0));
        }
    }
    
    public decimal TotalAmount
    {
        get
        {
            return TotalAmountNoInterest +
                		(InterestAmount != null ? InterestAmount : 0) +
                		(InterestVATAmount != null ? InterestVATAmount : 0);
        }
    }
    
    public decimal EventAmount
    {
        get
        {
            return lme.Event_Amount__c;
        }
    }

	public string LoanTerm
    {
        get
        {
            return PPASO.Product__r.Full_Term__c;
        }
    }
    
    public string LoanFrequency
    {
        get
        {
            return PPASO.Product__r.Schedule_Type__c;
        }
    }
    
    public decimal LoanInterest
    {
        get
        {
            return PPASO.Product__r.Interest_Rate__c;
        }
    }
}