src/objects/Loan_Ledger__c.object
<CustomObject>
    <fields>
        <fullName>Agreed_by_client__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Agreed by client</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DWH_Import__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DWH Import</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DWH_Status__c</fullName>
        <label>DWH Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>InputFromScreen__c</fullName>
        <label>InputFromScreen</label>
        <picklist>
            <picklistValues>
                <fullName>Early repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bounce back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt collection</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sign_Off_Date__c</fullName>
        <label>Sign Off Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disbursed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Loan Ledger</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sync_Queue__c.object
<CustomObject>
    <fields>
        <fullName>DWH_Data_Type__c</fullName>
        <label>DWH Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ODG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Product Association</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission/Incentive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Ledger</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Ledger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Ledger</label>
        <referenceTo>Loan_Ledger__c</referenceTo>
        <relationshipLabel>Sync Queues</relationshipLabel>
        <relationshipName>Sync_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Queued_Record_ID__c</fullName>
        <label>Queued Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Status__c</fullName>
        <label>Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sync Queue</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Sync Queue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Loan_LedgerTriggerHandler_Test.cls
@isTest
public class Loan_LedgerTriggerHandler_Test {
   public static testmethod void insertTest(){
        
        CRMS_Util.generateEndpoints();
        
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());
        
        Loan_Ledger__c lr = new Loan_Ledger__c(Sign_Off_Date__c = Date.today(),Agreed_by_client__c = true,InputFromScreen__c = 'bounceBackSection');
        insert lr;
        lr.Status__c = 'In Progress';
        update lr;
        List<Loan_Ledger__c> result = [SELECT DWH_Status__c   FROM Loan_Ledger__c WHERE id = :lr.id];
         system.assertNotEquals(null, result[0].DWH_Status__c);
        
           
        Sync_Queue__c sq = new Sync_Queue__c ( Loan_Ledger__c = lr.Id,
                                                        DWH_Data_Type__c = CRMS_Constants.DWH_DATA_TYPE_LOAN_LEDGER,
                                                        Queued_Record_ID__c = lr.Id,
                                                        Sync_Status__c = CRMS_Constants.SYNC_QUEUE_STATUS_PENDING);
        insert sq; 
        lr.DWH_Status__c = CRMS_Constants.DWH_STATUS_SYNCED;
        update lr;
		  
        Loan_Ledger__c lr2 = new Loan_Ledger__c(Sign_Off_Date__c = Date.today(),Agreed_by_client__c = true, DWH_Import__c =  true);
        insert lr2;
        lr2.DWH_Status__c = CRMS_Constants.DWH_STATUS_SYNCED;
        update lr2;
        
        delete lr;
    }

}