src/objects/Loan_Management__c.object
<CustomObject>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <label>Program Product ASO</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipName>Loan_Management</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Repayment_method__c</fullName>
        <label>Repayment method</label>
        <picklist>
            <picklistValues>
                <fullName>Add to the end of the term</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Spread across existing term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add to the next day of the term</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rules Engine</label>
    <nameField>
        <displayFormat>LM-{000}</displayFormat>
        <label>Loan Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules Engines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Management_Event__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ApprovedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Loan_Management_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Process_Method__c</fullName>
        <label>Event Process Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bounce Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Collection Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Repayment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waive Accummulated Fees</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Loan</label>
        <referenceTo>Operation__c</referenceTo>
        <relationshipLabel>Loan Management Events</relationshipLabel>
        <relationshipName>Loan_Management_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Loan Management Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Management Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Loan_BounceBackBatch.cls
/*
*This Batch is supposed to run at midnight local time and approves any unprocessed Bounce Backs, so that they will be processed by DWH with default parameters
*
*/

global class Loan_BounceBackBatch implements Database.Batchable<SObject>{
    
    public static final Date UK_DATE = Date.valueOf(System.now().format('yyyy-MM-dd', 'GMT+00:00'));
    public static final Date PH_SG_HK_DATE = Date.valueOf(System.now().format('yyyy-MM-dd', 'GMT+08:00'));
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([Select Id, Event_Process_Method__c, IsApproved__c, Approval_Date__c, ApprovedBy__c, Operation__r.Program_Product_ASO__c
                                         From Loan_Management_Event__c 
                                         Where Event_Type__c = 'Bounce Back' 
                                         	And IsApproved__c = false
                                         	And DAY_ONLY(CreatedDate) <: Date.today()
                                        ]);
    }

    global void execute(Database.BatchableContext BC, List<Loan_Management_Event__c> lstLMEvents) {
              
        if(!lstLMEvents.isEmpty())
        {
            for (Loan_Management_Event__c lme : lstLMEvents)
            {
                
                List<Loan_Management__c> rulesList = [Select Id, Repayment_method__c From Loan_Management__c Where Program_Product_ASO__c =: lme.Operation__r.Program_Product_ASO__c];
                lme.Event_Process_Method__c = rulesList.size() == 1 ? rulesList[0].Repayment_method__c : null;
                lme.IsApproved__c = true;
                lme.Approval_Date__c = Datetime.now();
                lme.ApprovedBy__c = UserInfo.getUserId();
            }
            
            update lstLMEvents;
        }
        
    }
    
    public void finish(Database.BatchableContext info) 
    {
       
    }
}