src/objects/Loan_Management__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Program_Product_ASO__r.Product__r.Product_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <label>Program Product ASO</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipName>Loan_Management</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Program_Product_ASO__r.Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Name</label>
        <type>Text</type>
    </fields>
    <label>Rules Engine</label>
    <nameField>
        <displayFormat>LM-{000}</displayFormat>
        <label>Loan Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules Engines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <recordTypes>
        <fullName>UK</fullName>
        <active>true</active>
        <label>UK</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>PPAS</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Loan_RulesEngine_Controller_Test.cls
@isTest
public class Loan_RulesEngine_Controller_Test {
    static testMethod void myUnitTest(){
     Product2 prod = new Product2(Name='UK-Loan-Miro');
     insert prod;
     Program__c prog = new Program__c(Name='UK-Miro');
     insert prog;
     Program_Product_ASO__c aso = new Program_Product_ASO__c(Program__c = prog.id, Product__c = prod.id);
     insert aso;
     Loan_Management__c re = new Loan_Management__c(Program_Product_ASO__c=aso.id); 
     insert re;
        
		ApexPages.StandardController controller = new ApexPages.StandardController(aso);
        Loan_RulesEngine_Controller ctrl1 = new Loan_RulesEngine_Controller(controller);
        
        ApexPages.currentPage().getParameters().put('id', aso.id);

        Loan_RulesEngine_Controller ctrl = new Loan_RulesEngine_Controller(controller);   
        ctrl.getPrograms();
        ctrl.getProducts();
        ctrl.getProfiles();
        ctrl.newRec();
        ctrl.refresh();
        ctrl.newRecord();
        
        List<Loan_Management__c> result = [Select ID From Loan_Management__c Where Program_Product_ASO__c = :aso.id];
        System.assertEquals(true, result!=null);
        ctrl.cancel();
        ctrl.deleteRecord();
        
    }
}