src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Advanced_Notification_Sent_to_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Advanced Notification Sent to Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted(Written-off)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disbursed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Disbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Topped-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Signed_Date__c</fullName>
        <label>Contract Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credit_File_Disclosure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit File Disclosure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Data_Protection_Act_Declaration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Data Protection Act Declaration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Signed_Application_Form_Received_Date__c</fullName>
        <label>Signed Application Form Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Signed_Application_Form_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Signed Application Form Received</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CRMS_DocuSignTriggerHandler.cls
/**
    Handler class for the Docusign trigger
    Author: CRM Superstars
    Version: 1.0
*/
public class CRMS_DocuSignTriggerHandler 
{
    /**This method is used to update opportunity fields when docusign's status record is inseted and it's status 
    * is updated to "Completed".
    **/
    public void updateOpportunty(list<dsfs__DocuSign_Status__c> listDocusign)
    {
        List<Id> oppIds = new List<Id>();
        List<Id> lstOperationIds = new List<Id>();
        for(dsfs__DocuSign_Status__c dc: listDocusign)
        {
            if(dc.dsfs__Envelope_Status__c == 'Completed')
            { //Assuming the field on Docusign object is Status__c
                if(dc.dsfs__Opportunity__c != null)
                {
                    oppIds.add(dc.dsfs__Opportunity__c); //Assuming the relationship field on Docusign object is Opportunity__c
                }
            }
            if(dc.dsfs__Envelope_Status__c == 'Sent')
            {
                lstOperationIds .add(dc.Operation__c);
            }
        }
        List<Opportunity> oppList = [select StageName, Signed_Application_Form_Received__c, Contract_Signed__c,
                                    Contract_Signed_Date__c, Data_Protection_Act_Declaration__c,
                                    Credit_File_Disclosure__c, Recordtype.Name, Id, Name
                                    from Opportunity where id IN : oppIds];
        List<Opportunity> oppListnew = new List<Opportunity>();
        
        List<Operation__c> operationList = [select Id, Advanced_Notification_Sent_to_Customer__c 
                                            from Operation__c where id In : lstOperationIds ];
        List<Operation__c> lstOperationToUpdate = new List<Operation__c>();
        
        //integer flag = 0;
        if(oppList != null && !oppList.isEmpty())
        {
            /*
            for(Opportunity op : oppList)
            {
                // when 1st signed docusign document is received 
                flag = 0;
                if(op.Signed_Application_Form_Received__c == false)
                {
                    op.Signed_Application_Form_Received__c = true;
                    op.Signed_Application_Form_Received_Date__c = date.today();
                    op.Credit_File_Disclosure__c = true;
                    op.Data_Protection_Act_Declaration__c = true;
                    flag = 1;
                }
                // when 2nd signed docusign document is received 
                if(op.Contract_Signed__c == false & flag==0)
                {
                    op.Contract_Signed__c = true;
                    op.Contract_Signed_Date__c = date.today();
                }
                oppListnew.add(op);
            }
            */
            for(Opportunity op : oppList)
            {
                if(op.Recordtype.Name.contains('Application'))
                {
                    system.debug('***********Inside sign done********');
                    op.Signed_Application_Form_Received__c = true;
                    op.Signed_Application_Form_Received_Date__c = date.today();
                    op.Data_Protection_Act_Declaration__c = true;
                    op.Credit_File_Disclosure__c = true;
                }
                else if(op.Recordtype.Name.contains('Outcome'))
                {
                    op.Contract_Signed__c = true;
                    op.Contract_Signed_Date__c = date.today();
                }
                oppListnew.add(op);
            }
        }
        if(!operationList.isEmpty() && operationList != null)
        {
            for(Operation__c objOperation : operationList)
            {
                if(objOperation.Advanced_Notification_Sent_to_Customer__c == false)
                {
                    objOperation.Advanced_Notification_Sent_to_Customer__c  = true;
                    lstOperationToUpdate.add(objOperation);
                }
            }
        }
        if(!oppListnew.isEmpty() && oppListnew != null)
        {
            update oppListnew;
        }
        if(!lstOperationToUpdate.isEmpty() && lstOperationToUpdate != null)
        {
            update lstOperationToUpdate;
        }
    } // end of updateOpportunty method
} // end of class