src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Disbursal_Approve__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disbursal Approve</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defaulted(Written-off)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disbursed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Disbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restructured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Topped-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LM_Renewal_Controller.cls
public with sharing class LM_Renewal_Controller extends LM_ComponentController{    
    public override void extendedSetterActions() 
    {	
        if(!bIsComponentInitialized){	//The setter is called multiple times and we don't want to overwrite if initialization is already done
            super.extendedSetterActions();
        	bIsCalculationActive = false;
            /*
            Operation__c o = ((LM_EventProcessor_Controller)pageController).o;
            
            Boolean IsError = false;
            Boolean IsDisbursed = o.Disbursal_Approve__c == null ? false : o.Disbursal_Approve__c;
            String opStatus = o.Status__c;
            
            
            if(!IsDisbursed)
            {
                IsError = true;
                infoMessage = 'The current loan of the client is in disbursal stage yet.';
            }        
            else if (opStatus != 'Completed')
            {
                IsError = true;
                infoMessage = 'The current loan of the client is not yet completed.';
            }
            
            if(IsError)
            {
				disableCalculation();
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.INFO, infoMessage);
                ApexPages.addMessage(msg);
            }
			*/
        }
    }
}