src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Interest_Daily_Repayment__c</fullName>
        <label>Interest Repayment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Principal Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Disbursed_Date__c</fullName>
        <label>To Be Disbursed On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Monthly_Interest__c</fullName>
        <defaultValue>IF($RecordType.DeveloperName == &apos;Operation_UK&apos;,  $Setup.IR__c.Annual_UK__c , $Setup.IR__c.Annual__c)</defaultValue>
        <label>Annual Interest</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>No_of_Days__c</fullName>
        <formula>VALUE(MID(TEXT(Loan_Term__c),5,3))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>No of Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Repayments__c</fullName>
        <label>Number of Repayments</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Outstanding_Principal__c</fullName>
        <label>Outstanding Principal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Principal_Daily_Repayments__c</fullName>
        <label>Principal Repayment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Repayments_Made__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Repayments Made</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Repayable__c</fullName>
        <label>Total Amount Repayable</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Daily_Repayment__c</fullName>
        <label>Total Repayment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>days__c</fullName>
        <defaultValue>0</defaultValue>
        <label># of days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRMS_DiminishingInterestCalculation.cls
/*
CRMS_DiminishingInterestCalculation is the batch class for calculation Remaining Principal for
Philippines Operations records

Author          Version           Date          Description
Vivian            1.0           07/07/2015      Initial Draft
*/
global class CRMS_DiminishingInterestCalculation implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([Select o.Total_Daily_Repayment__c, o.No_of_Days__c,
                                        o.Principal_Daily_Repayments__c, o.Number_of_Repayments__c,
                                        o.Name, o.Monthly_Interest__c, o.Loan_Disbursed_Date__c,
                                        o.Loan_Amount__c, o.Interest_Daily_Repayment__c, o.Id,
                                        o.RecordType.Name, o.Total_Amount_Repayable__c,
                                        o.Outstanding_Principal__c, o.Repayments_Made__c,
                                        o.days__c
                                        From Operation__c o
                                        where o.RecordType.Name like '%Philippines'
                                        and o.Loan_Disbursed_Date__c != null
                                        and o.Outstanding_Principal__c >= 0]);
    }

    global void execute(Database.BatchableContext BC, List<Operation__c> lstOperations) {
        list<Operation__c> lstToUpdate = new list<Operation__c>();
        map<String,Integer> mapDayOfWeek_Days = new map<String,Integer>();
        mapDayOfWeek_Days.put('Monday',5);
        mapDayOfWeek_Days.put('Tuesday',7);
        mapDayOfWeek_Days.put('Wednesday',6);
        mapDayOfWeek_Days.put('Thursday',5);
        mapDayOfWeek_Days.put('Friday',5);

        for(Operation__c objOperation : lstOperations) {
            objOperation.days__c = objOperation.days__c != null? (objOperation.days__c + 1): 0;
            Datetime dt = DateTime.newInstance(objOperation.Loan_Disbursed_Date__c,
            Time.newInstance(0, 0, 0, 0));
            //String disbursedDayOfWeek = dt.format('EEEE');
            if(objOperation.Loan_Disbursed_Date__c.daysBetween(date.today()) >=
            mapDayOfWeek_Days.get(dt.format('EEEE'))
            && objOperation.Loan_Disbursed_Date__c.daysBetween(date.today()) <=
            objOperation.No_of_Days__c) {
                Datetime currentDate = DateTime.newInstance(date.today(),
                Time.newInstance(0, 0, 0, 0));
                if(currentDate.format('EEEE') != 'Saturday'
                && currentDate.format('EEEE') != 'Sunday') {
	                objOperation.Outstanding_Principal__c = objOperation.Outstanding_Principal__c -
	                objOperation.Principal_Daily_Repayments__c;
	                objOperation.Repayments_Made__c = objOperation.Repayments_Made__c + 1;
                } // reduce outstanding principal only on Weekdays
            }
            lstToUpdate.add(objOperation);
        }

        if(!lstToUpdate.isEmpty()){
            update lstToUpdate;
        }
    } // end of execute

    public void finish(Database.BatchableContext info) {
    }
} // end of class