src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Principal Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Disbursed_Date__c</fullName>
        <label>To Be Disbursed On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loan_Term__c</fullName>
        <label>Loan Term</label>
        <picklist>
            <picklistValues>
                <fullName>03 (090 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 (120 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 (150 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 (210 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 (240 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 (360 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 (180 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 (270 days)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Outstanding_Principal__c</fullName>
        <label>Outstanding Principal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Principal_Daily_Repayments__c</fullName>
        <label>Principal Repayment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Repayments_Made__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Repayments Made</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <recordTypes>
        <fullName>Operation_Philippines</fullName>
        <active>true</active>
        <description>Record Type for Philippines</description>
        <label>Operation Philippines</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRMS_DiminishingInterestCalculationTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class CRMS_DiminishingInterestCalculationTest {

    static testMethod void myUnitTest() {
        CRMS_Util.generateEndpoints();
        Test.setMock(HttpCalloutMock.class, new CRMS_HttpCalloutMock());

        RecordType oppRecordType = [Select r.Id, r.SobjectType ,r.DeveloperName
                                    From RecordType r 
                                    where r.SobjectType = 'Operation__c' 
                                    and DeveloperName = 'Operation_Philippines'];
        list<Operation__c> lstOper = new list<Operation__c>(); 
        
        Operation__c objOperation = new Operation__c();
        objOperation.Loan_Disbursed_Date__c = date.today().addDays(-5);
        objOperation.Loan_Amount__c = 10000;
        objOperation.Outstanding_Principal__c = 10000;
        objOperation.RecordTypeId = oppRecordType.Id;
        objOperation.Loan_Term__c = '03 (090 days)';
        objOperation.Principal_Daily_Repayments__c = 200;
        objOperation.Repayments_Made__c = 0;
        lstOper.add(objOperation);

        Operation__c objOperation1 = new Operation__c();
        objOperation1.Loan_Disbursed_Date__c = date.today().addDays(-6);
        objOperation1.Loan_Amount__c = 15000;
        objOperation1.Outstanding_Principal__c = 15000;
        objOperation1.RecordTypeId = oppRecordType.Id;
        objOperation1.Loan_Term__c = '06 (180 days)';
        objOperation1.Principal_Daily_Repayments__c = 200;
        objOperation1.Repayments_Made__c = 0;
        lstOper.add(objOperation1);
        Test.startTest();
        insert lstOper;
        Database.executeBatch(new CRMS_DiminishingInterestCalculation());
        Test.stopTest();
    }
}