src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Principal Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Outstanding_Principal__c</fullName>
        <label>Loan Outstanding Principal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Full_Term__c</fullName>
        <label>Full_Term</label>
        <picklist>
            <picklistValues>
                <fullName>03 (090 days)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>04 (120 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 (150 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 (180 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 (210 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 (240 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 (270 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 (365 days)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <defaultValue>$Setup.IR__c.Annual_UK__c</defaultValue>
        <label>Interest Rate</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Interest_type__c</fullName>
        <label>Interest type</label>
        <picklist>
            <picklistValues>
                <fullName>Flat</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Diminishing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <label>Schedule Type</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>PPAS</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LM_Topup_Controller.cls
public with sharing class LM_Topup_Controller extends LM_ComponentController
{
    private Operation__c o;
         
    public override void extendedSetterActions()
    {    	
        if(!bIsComponentInitialized) //The setter is called multiple times and we don't want to overwrite if initialization is already done
        {
            super.extendedSetterActions();
            
            o = ((LM_EventProcessor_Controller)pageController).o;
            
            lme.Event_Date__c = Date.today();
            decimal totalPrincipalAmount = o.Loan_Amount__c;
            decimal repaidPrincipalAmount =  totalPrincipalAmount - (o.Loan_Outstanding_Principal__c == null ? totalPrincipalAmount : o.Loan_Outstanding_Principal__c);
            
            if (rulesEngine != null)
            {
                if (!rulesEngine.Top_ups__c)
                {
                    disableCalculation();
                    infoMessage = 'Top-ups are not allowed for the product used by this loan';                
                }
                else if(rulesEngine.Top_ups__c && (rulesEngine.Minimum_of_principal_repaid__c == null || rulesEngine.Minimum_of_principal_repaid__c == 0))
                {
                    disableCalculation();
                    infoMessage = 'Minimum % of Principal Repaid has not been configured. Please check the Rules Engine.';
                    
                }
                else if (repaidPrincipalAmount < (rulesEngine.Minimum_of_principal_repaid__c/100)*totalPrincipalAmount)
                {
                    disableCalculation();
                    infoMessage = 'Minimum % of Principal Repaid has not been reached. Top-ups are not allowed for this loan yet.';
                    
                }
            } 
        }
    }
    
    public list<selectOption> getLoanTerms(){
		list<selectOption> Terms = new list<selectOption>();
		Terms.add(new selectOption('','--None--'));
		try{
			for(Product2 Prod : this.getProductFullLoanTerm()){
				Terms.add(new selectOption(Prod.Full_Term__c, Prod.Full_Term__c));
			}			
		}catch(Exception ex){}		
		return Terms;		
	}
	
	private list<Product2> getProductFullLoanTerm(){
		try{			
			return [Select p.Full_Term__c From Product2 p
                    Where Id IN (Select Product__c
                                 From Program_Product_ASO__c 
                                 Where Program__c =: o.Program_Product_ASO__r.Program__c And Program__r.isActive__c = true 
                                 	And Product__r.Schedule_Type__c =: o.Program_Product_ASO__r.Product__r.Schedule_Type__c 
                                	And Product__r.Interest_Type__c =: o.Program_Product_ASO__r.Product__r.Interest_Type__c
                                	And Product__r.Interest_Rate__c =: o.Program_Product_ASO__r.Product__r.Interest_Rate__c)
                    Order By Full_Term__c];
            
		}catch(QueryException ex){
			return null;
		}
	}
}