src/objects/Operation__c.object
<CustomObject>
    <description>AMP Operations Custom Object</description>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Operations</relationshipLabel>
        <relationshipName>Operations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Operation</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Operations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Full_Term__c</fullName>
        <label>Full_Term</label>
        <picklist>
            <picklistValues>
                <fullName>03 (090 days)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>04 (120 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 (150 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 (180 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 (210 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 (240 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 (270 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 (365 days)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <defaultValue>$Setup.IR__c.Annual_UK__c</defaultValue>
        <label>Interest Rate</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Interest_type__c</fullName>
        <label>Interest type</label>
        <picklist>
            <picklistValues>
                <fullName>Flat</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Diminishing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <label>Schedule Type</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>PPAS</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rules_Engine__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rules Engine</label>
        <type>Checkbox</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LM_Restructure_Controller.cls
/**
 * AMP Loan Management System
 * 
 * This file is part of the AMP Loan Management Project
 * Loan Management System for Sales & Admin Peoples.
 *
 * Copyright (c) 2016 - xoomworks.com
 * 
 * @author Khurram Shahzad (Sr. Software Engineer .at. XoomWorks) <a href="http://www.xoomworks.com/">XoomWorks</a>
 * @created 2016
 * 
 * Loan Management Restructure Event Controller extension Class to Restructure the Loan Ammount.
 * This controller class enforce the sharing rules for the current user. 
 */ 

public with sharing class LM_Restructure_Controller extends LM_ComponentController {
		
	private Operation__c Operation;
    public Boolean hasRulesEngine {get; set;}
			
	public override void extendedSetterActions()
    {
        if(!bIsComponentInitialized) //The setter is called multiple times and we don't want to overwrite if initialization is already done
        {
            super.extendedSetterActions();
            
            Operation = ((LM_EventProcessor_Controller)pageController).o;
            lme.Event_Date__c = Date.today();
        }
    }
	
	public list<selectOption> getLoanTerms(){
		list<selectOption> Terms = new list<selectOption>();
		Terms.add(new selectOption('','--None--'));
		try{
			for(Product2 Prod : this.getProductFullLoanTerm()){
				Terms.add(new selectOption(Prod.Full_Term__c, Prod.Full_Term__c));
			}			
		}catch(Exception ex){}		
		return Terms;		
	}
	
	private list<Product2> getProductFullLoanTerm(){
		try{			
			return [Select Full_Term__c From Product2
                    Where Id IN (Select Product__c
                                 From Program_Product_ASO__c 
                                 Where Program__c =: Operation.Program_Product_ASO__r.Program__c And Program__r.isActive__c = true 
                                 	And Product__r.Schedule_Type__c =: Operation.Program_Product_ASO__r.Product__r.Schedule_Type__c 
                                	And Product__r.Interest_Type__c =: Operation.Program_Product_ASO__r.Product__r.Interest_Type__c
                                	And Product__r.Interest_Rate__c =: Operation.Program_Product_ASO__r.Product__r.Interest_Rate__c)
                    Order By Full_Term__c];
		}catch(QueryException ex){
			return null;
		}
	}
    
    public void checkForRulesEngine(){
        hasRulesEngine = [Select Rules_Engine__c
                          From Program_Product_ASO__c 
                          Where Program__c =: Operation.Program_Product_ASO__r.Program__c And Program__r.isActive__c = true 
                          And Product__r.Schedule_Type__c =: Operation.Program_Product_ASO__r.Product__r.Schedule_Type__c 
                          And Product__r.Interest_Type__c =: Operation.Program_Product_ASO__r.Product__r.Interest_Type__c
                          And Product__r.Interest_Rate__c =: Operation.Program_Product_ASO__r.Product__r.Interest_Rate__c
                          And Product__r.Full_term__c =: lme.Event_Loan_Term__c
                          And Rules_Engine__c = true].size() > 0;
        
    }
}