src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Interest_Daily_Repayment__c</fullName>
        <formula>IF(No_of_Repayments_Daily__c&lt;&gt;0,round((((IF(Annual_Calculation__c,Monthly_Interest__c,(Monthly_Interest__c*12)))/365*Loan_Term_In_Days__c)*Amount/No_of_Repayments_Daily__c),2),null)</formula>
        <label>Interest Daily Repayment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Weekly_Repayment__c</fullName>
        <formula>IF(No_of_Repayments_Weekly__c&lt;&gt;0,round((((IF(Annual_Calculation__c,Monthly_Interest__c,(Monthly_Interest__c*12)))/365*Loan_Term_In_Days__c)*Amount/No_of_Repayments_Weekly__c),2),null)</formula>
        <label>Interest Weekly Repayment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Frequency__c</fullName>
        <formula>TEXT(Program_Product_ASO__r.Product__r.Schedule_Type__c )</formula>
        <label>Loan Frequency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Interest__c</fullName>
        <formula>Program_Product_ASO__r.Product__r.Interest_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Loan Interest</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Term__c</fullName>
        <formula>TEXT(Program_Product_ASO__r.Product__r.Full_Term__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Loan Term</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Repayments_Daily__c</fullName>
        <formula>if(
isnumber(left(text(Requested_Loan_Term__c),2)),
CASE(
VALUE( MID(TEXT( Requested_Loan_Term__c ), 0, 2) ), 
03, 62,
04, 84,
05, 106, 
06, 126,
07, 149,
08, 170, 
09, 192, 
12, 259, 
0),
null
)</formula>
        <inlineHelpText>Number of repayments to be made each working day (5 days / week)</inlineHelpText>
        <label>No. of Repayments (Daily)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Repayments_Weekly__c</fullName>
        <formula>if(
isnumber(left(text(Requested_Loan_Term__c),2)),
CASE(VALUE( MID(TEXT( Requested_Loan_Term__c ), 0, 2) ), 
03, 13,
04, 18,
05, 22, 
06, 26,
07, 30,
08, 35, 
09, 39, 
12, 52, 
0),
null
)</formula>
        <label>No. of Repayments (Weekly)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Principal_Daily_Repayment__c</fullName>
        <formula>IF(
 No_of_Repayments_Daily__c &lt;&gt; 0 , 
 round((Amount /  No_of_Repayments_Daily__c),2),
 null
)</formula>
        <label>Principal Daily Repayment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Principal_Weekly_Repayment__c</fullName>
        <formula>IF (
 No_of_Repayments_Weekly__c &lt;&gt; 0 ,
 round((Amount /  No_of_Repayments_Weekly__c),2),
 null
)</formula>
        <label>Principal Weekly Repayment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Program__c</field>
                <operation>equals</operation>
                <valueField>Program_Product_ASO__c.Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program_Product_ASO__c.Rules_Engine__c</field>
                <operation>notEqual</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>contains</operation>
                <valueField>Program__c.Country_Mapping__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation_Total_Repaid_Daily__c</fullName>
        <formula>Amount +  Interest_Amount__c</formula>
        <label>Quotation Total Repaid (Daily)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quotation_Total_Repaid_Weekly__c</fullName>
        <formula>Amount +  Interest_Amount__c</formula>
        <label>Quotation Total Repaid (Weekly)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Repayable_Daily__c</fullName>
        <formula>Principal_Daily_Repayment__c + Interest_Daily_Repayment__c</formula>
        <label>Total Amount Repayable (Daily)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Repayable_Weekly__c</fullName>
        <formula>Interest_Weekly_Repayment__c  +  Principal_Weekly_Repayment__c</formula>
        <label>Total Amount Repayable (Weekly)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <label>Schedule Type</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>PPAS</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Loan_OpportunitySelectProduct_Controller.cls
public class Loan_OpportunitySelectProduct_Controller {

    public Opportunity opp {get;set;}    
    public ID oppID {get;set;}
    public String selectedProduct {get;set;}
    public Boolean isWeekly {get;set;}
    
    public Loan_OpportunitySelectProduct_Controller(ApexPages.StandardController stdController){
		oppID = stdController.getID();
        opp = [Select ID,Program__c,Program_Product_ASO__r.Product__r.Schedule_Type__c, Program_Product_ASO__c,
               No_of_Repayments_Daily__c,Principal_Daily_Repayment__c,Interest_Daily_Repayment__c,Total_Amount_Repayable_Daily__c,Quotation_Total_Repaid_Daily__c,
               No_of_Repayments_Weekly__c,Principal_Weekly_Repayment__c,Interest_Weekly_Repayment__c,Total_Amount_Repayable_Weekly__c,Quotation_Total_Repaid_Weekly__c,
               Loan_Frequency__c,Loan_Interest__c,Loan_Term__c,Amount
               From Opportunity where id =: oppID][0];
        if(opp.Program_Product_ASO__r.Product__r.Schedule_Type__c == 'Weekly') isWeekly = true; 
        else if (opp.Program_Product_ASO__r.Product__r.Schedule_Type__c == 'Daily') isWeekly = false;
        selectedProduct = opp.Program_Product_ASO__c;
    }
    
    
    
    public List<SelectOption> getProducts () {
        List<SelectOption> optns = new List<SelectOption>();
        List<Program_Product_ASO__c> aso = new List<Program_Product_ASO__c>();
        
        aso = [Select id,Product__c, Product__r.Name From Program_Product_ASO__c where Program__c = :opp.Program__c];
         optns.add(new SelectOption('','--None--'));
        for(Program_Product_ASO__c pp:aso){
            optns.add(new SelectOption(pp.id,pp.Product__r.Name));
            
        }
        return optns;
    }
    
    public PageReference save(){
        system.debug('Opportunity save:'+ opp);
        opp.Program_Product_ASO__c = selectedProduct;
        update opp;
        
        System.debug('Dani' + UserInfo.getSessionId());
        
        PageReference ref = new PageReference('/'+opp.id);
        ref.setRedirect(true);
        return ref;     
    }
    
}