src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Hong Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philippines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Program__c</field>
                <operation>equals</operation>
                <valueField>Program_Product_ASO__c.Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program_Product_ASO__c.Rules_Engine__c</field>
                <operation>notEqual</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>contains</operation>
                <valueField>Program__c.Country_Mapping__c</valueField>
            </filterItems>
            <filterItems>
                <field>Program__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UK</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UK</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>PPAS</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Loan_OppSelectProd_Controller_Test.cls
@isTest
public class Loan_OppSelectProd_Controller_Test {
    public static testmethod void testIt(){
        Program__c prog = new Program__c(Country__c = 'UK1');
        insert prog;
        Product2 prod = new Product2(Country__c = 'UK1');
        insert prod;    
        Program_Product_ASO__c ppas1 = new Program_Product_ASO__c(Program__c = prog.id, Product__c = prod.Id);
        insert ppas1; 
        
        Opportunity opp = new Opportunity(Program__c = prog.id, Name = 'MiroOppSelectProdTest', StageName = 'In Progress', CloseDate = Date.today().addDays(10));
        insert opp;
        
        ApexPages.StandardController controller = new ApexPages.StandardController(opp);
        Loan_OpportunitySelectProduct_Controller ctrl1 = new Loan_OpportunitySelectProduct_Controller(controller);
        ctrl1.getProducts ();
        
        ctrl1.selectedProduct = ppas1.id;
        
        ctrl1.save();
        
        List<Opportunity> result = [Select ID,Program_Product_ASO__c From Opportunity Where id = :opp.Id];
        
        System.assertEquals(true, result[0].Program_Product_ASO__c == ppas1.id);
    }
}