src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UK</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Full_Term__c</fullName>
        <label>Full_Term</label>
        <picklist>
            <picklistValues>
                <fullName>03 (090 days)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>04 (120 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 (150 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 (180 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 (210 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 (240 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09 (270 days)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 (365 days)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <defaultValue>$Setup.IR__c.Annual_UK__c</defaultValue>
        <label>Interest Rate</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Interest_type__c</fullName>
        <label>Interest type</label>
        <picklist>
            <picklistValues>
                <fullName>Flat</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Diminishing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Loan</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <label>Schedule Type</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/Loan_Product_Controller_Test.cls
@isTest
public class Loan_Product_Controller_Test {

    static testMethod void myUnitTest(){ 
        Product2 p = new Product2();
            p.Country__c ='UK1';
            p.Full_Term__c ='06 (180 days)';
            p.Product_Type__c = 'Loan';
            p.Interest_Type__c = 'Flat';
            p.Schedule_Type__c='Diminishing';
            p.Interest_Rate__c= 40;
            
        insert p;
        ApexPages.StandardController controller = new ApexPages.StandardController(p);
        Loan_Product_Controller ctrl1 = new Loan_Product_Controller(controller);
        
        ApexPages.currentPage().getParameters().put('id', p.id);

        Loan_Product_Controller ctrl = new Loan_Product_Controller(controller);
        ctrl.newRec();
        ctrl.save();
        ctrl.p.id=null;
        ctrl.p.Interest_Rate__c = 11;
        ctrl.save();
        ctrl.cancel();
        system.assertEquals(true, ctrl.p!=null);
        Loan_Product_Controller ctrl2 = new Loan_Product_Controller(controller);
        ctrl2.deleteRecord();
    }
}