src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>It determines the duration of a program’s validity</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <recordTypes>
        <fullName>UK</fullName>
        <active>true</active>
        <label>UK</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>PPAS</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reward__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reward</label>
        <type>Checkbox</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reward__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>It will contain the percentage or fixed commission amount</description>
        <label>Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calculation_method__c</fullName>
        <description>It specify the calculation that will need to be applied for the commission amount</description>
        <label>Calculation method</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Product_ASO__c</fullName>
        <label>Program Product ASO</label>
        <referenceTo>Program_Product_ASO__c</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Commission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incentive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>It determines whether the commission is paid at disbursal or at the end of the loan</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>At start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At end</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Split</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Loan_Reward_Controller_Test.cls
@isTest
public class Loan_Reward_Controller_Test {
     static testMethod void myUnitTest(){
     Product2 prod = new Product2(Name='UK-Loan-Miro');
     insert prod;
     Program__c prog = new Program__c(Name='UK-Miro');
     insert prog;
     Program_Product_ASO__c aso = new Program_Product_ASO__c(Program__c = prog.id, Product__c = prod.id);
     insert aso;
     Reward__c re = new Reward__c(Program_Product_ASO__c=aso.id); 
     insert re;
        
		ApexPages.StandardController controller = new ApexPages.StandardController(aso);
        Loan_Reward_Controller ctrl1 = new Loan_Reward_Controller(controller);
        
        ApexPages.currentPage().getParameters().put('id', aso.id);

        Loan_Reward_Controller ctrl = new Loan_Reward_Controller(controller);        
        //ctrl.getPPAS();             
        ctrl.newRec();       
        ctrl.newRecord(); 
        ctrl.getPrograms();
        ctrl.getProducts();
         
        ctrl.c.Amount__c = 11;
        ctrl.c.Calculation_method__c = 'Fixed';
        ctrl.c.Type__c = 'Split';
        ctrl.c.Start_Date__c = Date.today();
        ctrl.c.Source__c = 'Commission';     
         
        ctrl.i.Amount__c = 12;
        ctrl.i.Calculation_method__c = 'Fixed';
        ctrl.i.Type__c = 'Split';
        ctrl.i.Start_Date__c = Date.today();
        ctrl.i.Source__c = 'Incentive'; 
         
        ctrl.save();
        ctrl.cancel();
        ctrl.refresh();
        
        ctrl.countIdChosen=0;
        //ctrl.delRow();
        
        system.assertEquals(true, ctrl.c != null);
         ctrl.delRowComm();
         ctrl.delRowInc();
         ctrl.deleteRecord();
    }
}