src/objects/Program_Product_ASO__c.object
<CustomObject>
    <description>A Joined Table for assigning different products to a program</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Product ASO</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Loan_Program_Product_Redirect.cls
public with sharing class Loan_Program_Product_Redirect {
    
    private Program_Product_ASO__c Rec; 
    
    public Loan_Program_Product_Redirect(ApexPages.StandardController controller){
        this.Rec = (Program_Product_ASO__c)controller.getRecord();
    }
    
    Public PageReference RedirectToProductView(){
        Program_Product_ASO__c Rec = [Select Product__c from Program_Product_ASO__c Where Id=: this.Rec.id limit 1];
        PageReference ref = new PageReference('/apex/Loan_Product?id='+Rec.Product__c+'&sfdc.override=1');
        ref.setredirect(true);
        return ref;
    }
}