src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UK</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>It determines the duration of a program’s validity</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner_name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Salesforce account object (channel partner type)</description>
        <label>Partner Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner UK, Partner HK, Partner SG, Partner PP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>It determines the duration of a program’s validity</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <recordTypes>
        <fullName>UK</fullName>
        <active>true</active>
        <label>UK</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AMP_LoanProgramEmailAlertSchedular_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class AMP_LoanProgramEmailAlertSchedular_Test {

    static testMethod void TestAMPLoanProgramEmailAlertSchedular() {
        // TO DO: implement unit test
        
        Account Acnt;
        Program__c LoanProgram;
        
        Profile testProfile = [SELECT Id 
                           FROM profile
                           WHERE Name = 'System Administrator' 
                           LIMIT 1];            
       
       	User testadminuser = new User(alias = 'hasrole', email='userwithrole@roletest1.com',
                                    emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                                    localesidkey='en_US', profileid = testProfile.Id, 
                                    timezonesidkey='America/Los_Angeles', username='userwithrole@testorg.com');
       
        
        System.runAs(testadminuser) {			
            test.startTest();
            	Acnt = new Account(name = 'TEST ACCOUNT');
	            Database.insert(Acnt);
	            
	            LoanProgram = new Program__c(
	            	Start_Date__c	= System.today(),	            	 
	            	Partner_name__c	= Acnt.Id, 
	            	End_Date__c		= System.today().addDays(5), 
	            	Country__c		= 'UK'
	            );	            
	            Database.insert(LoanProgram);
				system.schedule('AMP Test Loan Program Email Alerts', '0 0 9 ? * MON-FRI', new AMP_LoanProgramEmailAlertSchedular());	                    
        	test.stopTest();
        }
        
        
    }
}